# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/analyze/sensitivity.ipynb.

# %% ../../nbs/analyze/sensitivity.ipynb #imports
from __future__ import annotations
import torch
import torch.nn as nn
import numpy as np
from copy import deepcopy
from dataclasses import dataclass, field, asdict
from typing import Callable, Any, Literal
from collections import OrderedDict
from contextlib import contextmanager
from functools import partial
from fastcore.basics import store_attr

from ..sparse.all import Sparsifier
from ..prune.all import Pruner
from ..core.all import large_final, Criteria, Granularities
from ..core.ratio import as_fraction

# %% auto #0
__all__ = ['LayerSensitivity', 'SensitivityResult', 'SensitivityAnalyzer', 'analyze_sensitivity']

# %% ../../nbs/analyze/sensitivity.ipynb #dataclasses
@dataclass(slots=True)
class LayerSensitivity:
    """Sensitivity result for a single layer."""
    name: str
    layer_type: str              # e.g., "Conv2d", "Linear"
    params: int
    baseline_metric: float       # metric before compression
    compressed_metric: float     # metric after compression
    delta: float                 # metric change (positive = degradation)
    group_id: int | None = None  # pruning: dependency-group id, shared by coupled layers
    group_members: list[str] = field(default_factory=list)  # names of all layers co-pruned with this one
    prunable: bool = True        # False if the layer could not be pruned — not "robust"

    def as_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return asdict(self)


@dataclass(slots=True)
class SensitivityResult:
    """Structured result from sensitivity analysis."""
    compression_type: str                   # "sparsity", "pruning", "quantization"
    compression_level: float                # fraction for sparsity/pruning (0.5 = 50%), bit width for quantization
    baseline_metric: float
    layers: list[LayerSensitivity]
    metric_name: str = "accuracy"
    higher_is_better: bool = True
    
    def as_dict(self) -> dict[str, Any]:
        """Convert to flat dictionary."""
        return {
            "compression_type": self.compression_type,
            "compression_level": self.compression_level,
            "baseline_metric": self.baseline_metric,
            "metric_name": self.metric_name,
            "higher_is_better": self.higher_is_better,
            "layers": [l.as_dict() for l in self.layers],
        }

    def _level_str(self) -> str:
        """The compression level as displayed: a percentage, or a bit width for quantization."""
        if self.compression_type.startswith("quantization"):
            return f"{int(self.compression_level)} bits"
        return f"{self.compression_level:.2%}"
    
    def top(
        self,
        n: int = 5,
        *,
        most_sensitive: bool = True,   # True=highest delta (fragile), False=lowest (robust)
    ) -> list[LayerSensitivity]:
        """Return top N most or least sensitive layers; a layer that could not be pruned is excluded —
        a no-op prune is not evidence of robustness, so it never ranks as compressible."""
        candidates = [l for l in self.layers if l.prunable]
        sorted_layers = sorted(candidates, key=lambda x: x.delta, reverse=most_sensitive)
        return sorted_layers[:n]
    
    def summary(
        self,
        *,
        top: int = 5,  # number of layers to show per category
    ) -> None:
        """Print a formatted summary of sensitivity analysis."""
        print(f"{'═' * 60}")
        print(f"Sensitivity Analysis: {self.compression_type} @ {self._level_str()}")
        print(f"{'═' * 60}")
        print(f"  Baseline {self.metric_name}: {self.baseline_metric:.4f}")
        print(f"  Layers analyzed: {len(self.layers)}")
        print()

        def _line(i, layer):
            sign = "+" if layer.delta > 0 else ""
            grp = f"  [group {layer.group_id}]" if layer.group_id is not None else ""
            print(f"     {i}. {layer.name:30} Δ={sign}{layer.delta:.4f}{grp}")

        print(f"  🔴 Most Sensitive (fragile):")
        for i, layer in enumerate(self.top(top, most_sensitive=True), 1):
            _line(i, layer)
        print()
        
        print(f"  🟢 Most Robust (compressible):")
        for i, layer in enumerate(self.top(top, most_sensitive=False), 1):
            _line(i, layer)

        not_prunable = [l for l in self.layers if not l.prunable]
        if not_prunable:
            print()
            print(f"  ⚪ Not prunable in isolation ({len(not_prunable)}):")
            for i, layer in enumerate(not_prunable[:top], 1):
                print(f"     {i}. {layer.name:30} (group {layer.group_id})")
    
    def to_dataframe(self):
        """Convert to pandas DataFrame."""
        import pandas as pd
        rows = [layer.as_dict() for layer in self.layers]
        return pd.DataFrame(rows)
    
    def to_layer_targets(
        self,
        model: nn.Module,        # model (used for parameter counts)
        target: float = 0.5,     # target mean compression, a fraction in [0, 1] (0.4 = 40%)
        min_ratio: float = 0.,   # minimum compression for any layer
        max_ratio: float = 0.9,  # maximum compression for any layer
        gamma: float = 1.0,      # exponent for sensitivity scaling (higher = more differentiation)
    ) -> dict[str, float]:
        """Convert sensitivity to non-uniform per-layer compression targets, as fractions.
        Coupled layers are solved as a SINGLE knob; not-prunable layers receive `min_ratio`.
        """
        if not self.layers:
            return {}
        
        target = as_fraction(target, 'target')
        smin = as_fraction(min_ratio, 'min_ratio')
        smax = as_fraction(max_ratio, 'max_ratio')

        prunable = [l for l in self.layers if l.prunable]
        not_prunable = [l for l in self.layers if not l.prunable]
        groups: OrderedDict[Any, dict] = OrderedDict()
        for l in prunable:
            key = l.group_id if l.group_id is not None else ("solo", l.name)
            g = groups.setdefault(key, {"names": [], "params": 0.0, "delta": 0.0})
            g["names"].append(l.name)
            g["params"] += float(l.params)
            g["delta"] = max(g["delta"], max(0.0, l.delta))  # delta is shared within a group

        targets: dict[str, float] = {l.name: round(smin, 4) for l in not_prunable}
        if not groups:
            return targets

        deltas = np.array([g["delta"] for g in groups.values()], dtype=float)
        weights = np.array([g["params"] for g in groups.values()], dtype=float)
        group_names = [g["names"] for g in groups.values()]

        if weights.sum() == 0:
            for names in group_names:
                for n in names: targets[n] = round(target, 4)
            return targets
        
        if np.allclose(deltas, deltas[0]):
            s0 = np.full_like(deltas, target)
        else:
            norm = (deltas - deltas.min()) / (np.ptp(deltas) + 1e-12)
            inv = (1.0 - norm) ** gamma
            s0 = smin + (smax - smin) * inv
        
        # Binary search for lambda to hit target weighted mean
        W = weights.sum()
        tgt = target * W
        
        def f(lam):
            s = np.clip(s0 + lam, smin, smax)
            return float(np.dot(weights, s))
        
        lam_lo, lam_hi = -1.0, 1.0
        while f(lam_lo) > tgt:
            lam_lo *= 2
        while f(lam_hi) < tgt:
            lam_hi *= 2
        
        for _ in range(60):
            lam_mid = 0.5 * (lam_lo + lam_hi)
            if f(lam_mid) < tgt:
                lam_lo = lam_mid
            else:
                lam_hi = lam_mid
        
        final_s = np.clip(s0 + 0.5 * (lam_lo + lam_hi), smin, smax)

        for names, s in zip(group_names, final_s):
            for n in names:
                targets[n] = round(float(s), 4)
        return targets
    
    def plot(
        self,
        figsize: tuple = (12, 5),  # figure size (width, height)
    ) -> None:
        """Plot sensitivity as a bar chart."""
        import matplotlib.pyplot as plt
        
        names = [l.name for l in self.layers]
        deltas = np.array([l.delta for l in self.layers], dtype=float)
        
        norm = (deltas - deltas.min()) / (np.ptp(deltas) + 1e-9)
        colors = plt.cm.RdYlGn_r(norm)  # Red=sensitive, Green=robust
        
        plt.figure(figsize=figsize)
        plt.bar(range(len(deltas)), deltas, color=colors)
        plt.axhline(0, color='gray', linewidth=1.2, linestyle='--')
        plt.xticks(range(len(names)), names, rotation=60, ha='right')
        plt.ylabel(f"{self.metric_name} drop (Δ)")
        plt.title(f"Layer Sensitivity to {self.compression_type} @ {self._level_str()}", 
                  pad=12, weight='bold')
        plt.grid(axis='y', linestyle=':', alpha=0.6)
        plt.tight_layout()
        plt.show()

# %% ../../nbs/analyze/sensitivity.ipynb #analyzer
class SensitivityAnalyzer:
    """Analyze per-layer sensitivity to sparsity, structural pruning and quantization.
    `level` is a fraction in [0, 1] (0.5 = 50%) for sparsity and pruning, a bit width for quantization.
    """
    
    VALID_COMPRESSIONS = frozenset({"sparsity", "pruning", "quantization"})
    COMPRESSIBLE_LAYERS = Granularities.available_modules()
    
    def __init__(
        self,
        model: nn.Module,
        sample: torch.Tensor,                          # example input (for Pruner dependency analysis)
        eval_fn: Callable[[nn.Module], float],
        *,
        criteria: Criteria = large_final,              # fasterai criteria for importance scoring
        higher_is_better: bool = True,
        metric_name: str = "accuracy",
        device: str | torch.device | None = None,
        calibration_data: torch.Tensor | None = None,  # for observer-based quantization
    ):
        store_attr()
        self.device = device or next(model.parameters()).device
        self._results: SensitivityResult | None = None
        self._sparsifier: Sparsifier | None = None
        self._activation_hooks: list[Any] = []
        self._activation_quantize_config: dict[str, bool] = {}

    @staticmethod
    def _out_dim(
        module: nn.Module,
    ) -> int | None:
        """Output channels (Conv) or features (Linear) of a layer."""
        return getattr(module, 'out_channels', None) or getattr(module, 'out_features', None)

    @staticmethod
    @contextmanager
    def _quiet():
        """Silence the per-construction notices fasterai's Pruner prints (ignore / per-layer info)."""
        import io, contextlib
        with contextlib.redirect_stdout(io.StringIO()):
            yield
    
    def _get_compressible_layers(
        self,
        layer_types: type | tuple[type, ...] | None = None,
    ) -> list[tuple[str, nn.Module]]:
        """Get all compressible layers (Conv2d, Linear, etc.), optionally filtered to `layer_types`."""
        if layer_types is None:
            types = self.COMPRESSIBLE_LAYERS
        else:
            types = (layer_types,) if isinstance(layer_types, type) else tuple(layer_types)
        return [
            (name, module) 
            for name, module in self.model.named_modules()
            if isinstance(module, self.COMPRESSIBLE_LAYERS) and isinstance(module, types)
            and hasattr(module, 'weight') and module.weight is not None
        ]
    
    def _init_sparsifier(
        self,
        granularity: str = "weight",
    ) -> None:
        """Initialize fasterai Sparsifier (saves initial weights for all layers)."""
        if self._sparsifier is None:
            self._sparsifier = Sparsifier(
                self.model,
                granularity=granularity,
                context='local',
                criteria=self.criteria,
            )
    
    def _cleanup_sparsifier(self) -> None:
        """Remove sparsifier buffers from model."""
        if self._sparsifier is not None:
            self._sparsifier._clean_buffers()
            self._sparsifier = None
    
    def _restore_layer(
        self,
        module: nn.Module,
    ) -> None:
        """Restore a single layer from saved initial weights."""
        if hasattr(module, '_init_weights'):
            module.weight.data.copy_(module._init_weights)
        if hasattr(module, '_init_biases') and module._init_biases is not None:
            module.bias.data.copy_(module._init_biases)
        if hasattr(module, '_mask'):
            del module._buffers['_mask']
    
    def _clone_model(self) -> nn.Module:
        """Create a clean copy of the model (avoids deepcopy issues with non-leaf tensors)."""
        import io
        buffer = io.BytesIO()
        torch.save(self.model, buffer)
        buffer.seek(0)
        model_copy = torch.load(buffer, weights_only=False)
        model_copy.eval()
        return model_copy

    def _fresh_copy(self) -> nn.Module:
        """A clean model copy (save/load), falling back to deepcopy if that fails."""
        try:
            return self._clone_model()
        except Exception:
            return deepcopy(self.model)

    def _channel_signature(
        self,
        model: nn.Module,
    ) -> tuple:
        """Tuple of out-channels/out-features for every compressible layer (detects no-op prunes)."""
        return tuple(
            self._out_dim(m)
            for _, m in model.named_modules()
            if isinstance(m, self.COMPRESSIBLE_LAYERS)
        )

    def _build_dependency_groups(
        self,
        model: nn.Module,
    ) -> tuple[dict[str, int], dict[int, list[str]]]:
        """Map each compressible layer to its OUTPUT-coupled dependency group.
        Returns (name->group_id, group_id->member_names); the layers Pruner ignores get no group.
        """
        import torch_pruning as tp
        import warnings
        name_of = {m: n for n, m in model.named_modules()}
        with self._quiet():
            p = Pruner(model, pruning_ratio=0.5, context='local',
                       criteria=self.criteria, example_inputs=self.sample)
        DG = p.pruner.DG
        ignored = set(p.ignored_layers)

        name_to_coupled: dict[str, frozenset] = {}
        for name, mod in model.named_modules():
            if not isinstance(mod, self.COMPRESSIBLE_LAYERS) or mod in ignored:
                continue
            fn = tp.prune_conv_out_channels if isinstance(mod, nn.Conv2d) else tp.prune_linear_out_channels
            coupled = {name}
            try:
                group = DG.get_pruning_group(mod, fn, idxs=list(range(self._out_dim(mod))))
                for dep, _ in group:
                    tmod = dep.target.module
                    if (isinstance(tmod, self.COMPRESSIBLE_LAYERS) and tmod in name_of
                            and tmod not in ignored
                            and getattr(dep.handler, '__name__', '') == 'prune_out_channels'):
                        coupled.add(name_of[tmod])
            except Exception as e:
                # treat as uncoupled; warn for parity with the prune path
                warnings.warn(f"Could not resolve dependency group for {name}: {e}")
            name_to_coupled[name] = frozenset(coupled)

        key_to_gid: dict[frozenset, int] = {}
        name_to_gid: dict[str, int] = {}
        gid_to_members: dict[int, list[str]] = {}
        for name, key in name_to_coupled.items():
            if key not in key_to_gid:
                key_to_gid[key] = len(key_to_gid)
                gid_to_members[key_to_gid[key]] = sorted(key)
            name_to_gid[name] = key_to_gid[key]
        return name_to_gid, gid_to_members

    def _apply_structural_pruning(
        self, 
        target_name: str,
        level: float,
    ) -> tuple[nn.Module, bool]:
        """Prune the target layer on a fresh model copy exactly as a real per-layer prune would.
        Returns (pruned_model, prunable); prunable is False if the prune changed nothing.
        """
        import warnings
        model_copy = self._fresh_copy()
        if target_name not in dict(model_copy.named_modules()):
            return model_copy, False

        before = self._channel_signature(model_copy)
        try:
            with self._quiet():
                pruner = Pruner(
                    model_copy,
                    pruning_ratio={target_name: level},
                    context='local',
                    criteria=self.criteria,
                    example_inputs=self.sample,
                )
                pruner.prune_model()
        except Exception as e:
            warnings.warn(f"Structural pruning failed for {target_name}: {e}")
            # Never evaluate a half-pruned model — return a clean copy marked not-prunable
            return self._fresh_copy(), False

        prunable = self._channel_signature(model_copy) != before
        return model_copy, prunable
    
    def _fake_quantize(
        self,
        t: torch.Tensor,
        bits: int = 8,
        symmetric: bool = True,
        per_channel: bool = False,
        axis: int = 0,
    ) -> torch.Tensor:
        """Fake-quantize a tensor: symmetric or asymmetric, per-channel along `axis` or per-tensor."""
        qmin, qmax = (-(2 ** (bits - 1)), 2 ** (bits - 1) - 1) if symmetric else (0, 2 ** bits - 1)
        per_channel = per_channel and t.dim() > 1
        dims = [d for d in range(t.dim()) if d != axis] if per_channel else list(range(t.dim()))

        if symmetric:
            scale = torch.clamp(t.abs().amax(dim=dims) / qmax, min=1e-8)
            zero_point = torch.zeros_like(scale, dtype=torch.int32)
        else:
            t_min, t_max = t.amin(dim=dims), t.amax(dim=dims)
            scale = torch.clamp((t_max - t_min) / (qmax - qmin), min=1e-8)
            zero_point = torch.clamp(torch.round(-t_min / scale), qmin, qmax).to(torch.int32)

        if per_channel:
            return torch.fake_quantize_per_channel_affine(t, scale, zero_point, axis, qmin, qmax)
        return torch.fake_quantize_per_tensor_affine(t, scale.item(), int(zero_point.item()), qmin, qmax)

    def _apply_weight_quantization(
        self,
        module: nn.Module,
        bits: int = 8,
        per_channel: bool = True,
    ) -> None:
        """Fake-quantize a layer's weights in place."""
        w = module.weight.data
        w.copy_(self._fake_quantize(w, bits, symmetric=True, per_channel=per_channel))

    def _create_activation_quantize_hook(
        self,
        layer_name: str,
        bits: int = 8,
    ):
        """Create a forward hook that quantizes activations."""
        def hook(module, input, output):
            if self._activation_quantize_config.get(layer_name, False):
                return self._fake_quantize(output, bits, symmetric=False)
            return output
        return hook
    
    def _setup_activation_hooks(
        self,
        bits: int = 8,
    ) -> None:
        """Register activation quantization hooks on all layers."""
        self._remove_activation_hooks()
        for name, module in self._get_compressible_layers():
            hook = self._create_activation_quantize_hook(name, bits)
            handle = module.register_forward_hook(hook)
            self._activation_hooks.append(handle)
            self._activation_quantize_config[name] = False
    
    def _remove_activation_hooks(self) -> None:
        """Remove all activation quantization hooks."""
        for handle in self._activation_hooks:
            handle.remove()
        self._activation_hooks = []
        self._activation_quantize_config = {}
    
    @contextmanager
    def _probe_context(
        self,
        compression: str,
        granularity: str,
        bits: int,
        quant_activations: bool,
    ):
        """Install what the probes need, and tear it down even if `eval_fn` raises."""
        if compression == "sparsity":
            self._init_sparsifier(granularity)
        if compression == "quantization" and quant_activations:
            self._setup_activation_hooks(bits)
        try:
            yield
        finally:
            if compression == "sparsity":
                self._cleanup_sparsifier()
            if compression == "quantization" and quant_activations:
                self._remove_activation_hooks()

    def _probe_sparsity(
        self,
        name: str,
        module: nn.Module,
        level: float,
    ) -> tuple[float, bool]:
        """Sparsify one layer, measure, restore."""
        self._sparsifier.sparsify_layer(module, level)
        metric = self.eval_fn(self.model)
        self._restore_layer(module)
        return metric, True

    def _probe_pruning(
        self,
        name: str,
        module: nn.Module,
        level: float,
        *,
        baseline: float,
        gids: dict[str, int],
        cache: dict[int, tuple[float, bool]],
    ) -> tuple[float, bool]:
        """Prune one dependency group on a fresh copy, measured once and shared by its members."""
        gid = gids.get(name)
        if gid is None:
            return baseline, False  # ignored layer (output Linear / attention)
        if gid in cache:
            return cache[gid]
        pruned_model, prunable = self._apply_structural_pruning(name, level)
        metric = self.eval_fn(pruned_model) if prunable else baseline
        del pruned_model
        cache[gid] = (metric, prunable)
        return metric, prunable

    def _probe_quantization(
        self,
        name: str,
        module: nn.Module,
        level: float,
        *,
        bits: int,
        per_channel: bool,
        activations: bool,
    ) -> tuple[float, bool]:
        """Fake-quantize one layer (weights, optionally activations), measure, restore."""
        saved_weight = module.weight.data.clone()
        saved_bias = module.bias.data.clone() if module.bias is not None else None
        self._apply_weight_quantization(module, bits, per_channel=per_channel)
        if activations: self._activation_quantize_config[name] = True
        metric = self.eval_fn(self.model)
        if activations: self._activation_quantize_config[name] = False
        module.weight.data.copy_(saved_weight)
        if saved_bias is not None: module.bias.data.copy_(saved_bias)
        return metric, True

    def _mode_info(self, compression: str, granularity: str, quant_per_channel: bool, quant_activations: bool) -> str:
        """The mode suffix of the progress banner."""
        if compression == "quantization":
            return (f" (per-{'channel' if quant_per_channel else 'tensor'}"
                    f", {'weights+activations' if quant_activations else 'weights only'})")
        detail = "structural group-sensitivity" if compression == "pruning" else f"granularity={granularity}"
        return f" ({detail}, criteria={self.criteria.f.__name__})"

    def analyze(
        self,
        compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",
        level: float = 0.5,
        *,
        granularity: str = "weight",          # granularity for sparsity
        layers: list[str] | None = None,      # specific layer names to analyze (None = all)
        layer_types: type | tuple[type, ...] | None = None,  # restrict to a module type or tuple of types; None = all compressible
        quant_per_channel: bool = True,
        quant_activations: bool = False,
        verbose: bool = True,
    ) -> SensitivityResult:
        """Analyze per-layer sensitivity to compression.
        For pruning, each layer gets the per-layer target `{name: level}`, so Δ predicts a real prune.
        """
        if compression not in self.VALID_COMPRESSIONS:
            raise ValueError(f"compression must be one of {self.VALID_COMPRESSIONS}")

        if compression != "quantization":
            level = as_fraction(level, 'level')
        level_str = f"{int(level)} bits" if compression == "quantization" else f"{level:.2%}"
        bits = int(level) if level > 1 else 8

        self.model.eval()

        if verbose:
            print(f"Computing baseline {self.metric_name}...", end=" ", flush=True)
        baseline = self.eval_fn(self.model)
        if verbose:
            print(f"{baseline:.4f}")
        
        all_layers = self._get_compressible_layers(layer_types)
        if layers is not None:
            all_layers = [(n, m) for n, m in all_layers if n in layers]

        group_gid, group_members = {}, {}
        if compression == "pruning":
            group_gid, group_members = self._build_dependency_groups(self.model)
        
        mode_info = self._mode_info(compression, granularity, quant_per_channel, quant_activations)
        if verbose:
            print(f"Analyzing {len(all_layers)} layers for {compression} @ {level_str}{mode_info}")
        
        probe = {"sparsity": self._probe_sparsity,
                 "pruning": partial(self._probe_pruning, baseline=baseline, gids=group_gid, cache={}),
                 "quantization": partial(self._probe_quantization, bits=bits,
                                         per_channel=quant_per_channel, activations=quant_activations)}[compression]
        results: list[LayerSensitivity] = []

        with self._probe_context(compression, granularity, bits, quant_activations):
            for i, (name, module) in enumerate(all_layers):
                if verbose:
                    print(f"  [{i+1}/{len(all_layers)}] {name}...", end=" ", flush=True)

                compressed_metric, prunable = probe(name, module, level)
                gid = group_gid.get(name)  # None for sparsity/quant and for ignored layers
                delta = baseline - compressed_metric if self.higher_is_better else compressed_metric - baseline

                if verbose:
                    sign = "+" if delta > 0 else ""
                    tag = "" if prunable else " (not prunable)"
                    print(f"Δ={sign}{delta:.4f}{tag}")

                results.append(LayerSensitivity(
                    name=name,
                    layer_type=module.__class__.__name__,
                    params=module.weight.numel(),
                    baseline_metric=baseline,
                    compressed_metric=compressed_metric,
                    delta=delta,
                    group_id=gid,
                    group_members=group_members.get(gid, []),
                    prunable=prunable,
                ))

        compression_desc = compression
        if compression == "quantization":
            compression_desc = f"quantization-{bits}bit" + ("+act" if quant_activations else "")
        
        self._results = SensitivityResult(
            compression_type=compression_desc,
            compression_level=level,
            baseline_metric=baseline,
            layers=results,
            metric_name=self.metric_name,
            higher_is_better=self.higher_is_better,
        )
        
        if verbose:
            print("✓ Analysis complete")
        
        return self._results
    
    def sweep(
        self,
        compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",
        levels: list[float] | None = None,  # compression levels to test; None = [0.25, 0.5, 0.75]
        **kwargs,
    ) -> list[SensitivityResult]:
        """Run sensitivity analysis at multiple compression levels."""
        if levels is None:
            levels = [0.25, 0.5, 0.75]
        results = []
        for level in levels:
            level_str = f"{int(level)} bits" if compression == "quantization" else f"{level:.2%}"
            print(f"\n{'='*60}")
            print(f"Sweep: {compression} @ {level_str}")
            print(f"{'='*60}")
            result = self.analyze(compression, level, **kwargs)
            results.append(result)
        return results

# %% ../../nbs/analyze/sensitivity.ipynb #convenience
def analyze_sensitivity(
    model: nn.Module,
    sample: torch.Tensor,
    eval_fn: Callable[[nn.Module], float],
    compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",
    level: float = 0.5,
    *,
    criteria: Criteria = large_final,
    higher_is_better: bool = True,
    metric_name: str = "accuracy",
    granularity: str = "weight",
    verbose: bool = True,
    **kwargs,
) -> SensitivityResult:
    """One-line sensitivity analysis; arguments as `SensitivityAnalyzer` and `SensitivityAnalyzer.analyze`."""
    analyzer = SensitivityAnalyzer(
        model, sample, eval_fn, 
        criteria=criteria, 
        higher_is_better=higher_is_better,
        metric_name=metric_name,
    )
    return analyzer.analyze(compression, level, granularity=granularity, verbose=verbose, **kwargs)
