# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/analyze/sensitivity.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/analyze/sensitivity.ipynb #sens-stub-3
# Sensitivity analysis moved out of fasterai (now in the higher-level FasterAI workflow package; fasterai holds compression mechanisms only).
_MOVED = {'analyze_sensitivity', 'SensitivityAnalyzer', 'SensitivityResult', 'LayerSensitivity'}
def __getattr__(name):  # PEP 562
    if name in _MOVED:
        raise ImportError(
            f"`{name}` is no longer part of fasterai; sensitivity analysis moved to the "
            f"higher-level FasterAI workflow package. See the FasterAI docs for the new import path."
        )
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
