# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/analyze/sensitivity.ipynb.

# %% ../../nbs/analyze/sensitivity.ipynb #imports
from __future__ import annotations
import torch
import torch.nn as nn
import numpy as np
from copy import deepcopy
from dataclasses import dataclass, field, asdict
from typing import Callable, Any, Literal
from collections import OrderedDict
from contextlib import contextmanager
from fastcore.basics import store_attr

# fasterai imports (relative within fasterai package)
from ..sparse.all import Sparsifier
from ..prune.all import Pruner
from ..core.all import large_final, Criteria, Granularities

# %% auto #0
__all__ = ['LayerSensitivity', 'SensitivityResult', 'SensitivityAnalyzer', 'analyze_sensitivity']

# %% ../../nbs/analyze/sensitivity.ipynb #dataclasses
@dataclass(slots=True)
class LayerSensitivity:
    """Sensitivity result for a single layer."""
    name: str                    # layer name
    layer_type: str              # e.g., "Conv2d", "Linear"
    params: int                  # number of parameters
    baseline_metric: float       # metric before compression
    compressed_metric: float     # metric after compression
    delta: float                 # metric change (positive = degradation)
    group_id: int | None = None  # pruning: dependency-group id (coupled layers share one); None for sparsity/quant
    group_members: list[str] = field(default_factory=list)  # names of all layers co-pruned with this one
    prunable: bool = True        # False if the layer could not be pruned (genuine no-op) — not "robust"

    def as_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return asdict(self)


@dataclass(slots=True)
class SensitivityResult:
    """Structured result from sensitivity analysis."""
    compression_type: str                   # "sparsity", "pruning", "quantization"
    compression_level: float                # e.g., 50 for 50% sparsity
    baseline_metric: float                  # overall baseline metric
    layers: list[LayerSensitivity]          # per-layer results
    metric_name: str = "accuracy"           # name of the metric
    higher_is_better: bool = True           # whether higher metric is better
    _results: list[LayerSensitivity] = field(default=None, init=False, repr=False)  # for top() compatibility
    
    def __post_init__(self):
        self._results = self.layers  # for compatibility with top() pattern
    
    def as_dict(self) -> dict[str, Any]:
        """Convert to flat dictionary."""
        return {
            "compression_type": self.compression_type,
            "compression_level": self.compression_level,
            "baseline_metric": self.baseline_metric,
            "metric_name": self.metric_name,
            "higher_is_better": self.higher_is_better,
            "layers": [l.as_dict() for l in self.layers],
        }
    
    def top(
        self,
        n: int = 5,                    # number of layers to return
        *,
        most_sensitive: bool = True,   # True=highest delta (fragile), False=lowest (robust)
    ) -> list[LayerSensitivity]:
        """Return top N most or least sensitive layers.

        Layers that could not be pruned (`prunable=False`) are excluded — a no-op
        prune is NOT evidence of robustness, so it must never rank as compressible.
        """
        candidates = [l for l in self.layers if l.prunable]
        sorted_layers = sorted(candidates, key=lambda x: x.delta, reverse=most_sensitive)
        return sorted_layers[:n]
    
    def summary(
        self,
        *,
        top: int = 5,  # number of layers to show per category
    ) -> None:
        """Print a formatted summary of sensitivity analysis."""
        print(f"{'═' * 60}")
        print(f"Sensitivity Analysis: {self.compression_type} @ {self.compression_level}%")
        print(f"{'═' * 60}")
        print(f"  Baseline {self.metric_name}: {self.baseline_metric:.4f}")
        print(f"  Layers analyzed: {len(self.layers)}")
        print()

        def _line(i, layer):
            sign = "+" if layer.delta > 0 else ""
            grp = f"  [group {layer.group_id}]" if layer.group_id is not None else ""
            print(f"     {i}. {layer.name:30} Δ={sign}{layer.delta:.4f}{grp}")

        # Most sensitive (fragile) layers
        print(f"  🔴 Most Sensitive (fragile):")
        for i, layer in enumerate(self.top(top, most_sensitive=True), 1):
            _line(i, layer)
        print()
        
        # Most robust layers
        print(f"  🟢 Most Robust (compressible):")
        for i, layer in enumerate(self.top(top, most_sensitive=False), 1):
            _line(i, layer)

        # Layers that could not be pruned in isolation — surfaced, NOT ranked as robust
        not_prunable = [l for l in self.layers if not l.prunable]
        if not_prunable:
            print()
            print(f"  ⚪ Not prunable in isolation ({len(not_prunable)}):")
            for i, layer in enumerate(not_prunable[:top], 1):
                print(f"     {i}. {layer.name:30} (group {layer.group_id})")
    
    def to_dataframe(self):
        """Convert to pandas DataFrame."""
        import pandas as pd
        rows = [layer.as_dict() for layer in self.layers]
        return pd.DataFrame(rows)
    
    def to_layer_targets(
        self,
        model: nn.Module,          # model (used for parameter counts)
        target_pct: float = 50,    # target mean compression percentage
        min_pct: float = 0,        # minimum compression for any layer
        max_pct: float = 90,       # maximum compression for any layer
        gamma: float = 1.0,        # exponent for sensitivity scaling (higher = more differentiation)
    ) -> dict[str, float]:
        """Convert sensitivity to non-uniform per-layer compression targets.
        
        High sensitivity layers get lower compression, robust layers get higher.
        Uses parameter-weighted optimization to hit target_pct exactly.

        Coupled layers (same `group_id`) are optimized as a SINGLE knob — they
        physically share one pruning ratio — then the group's target is expanded
        back to every member, so the returned dict stays per-layer. Layers that
        are not prunable receive `min_pct`.
        """
        if not self.layers:
            return {}
        
        # Convert to fractions
        target = target_pct / 100.0
        smin = min_pct / 100.0
        smax = max_pct / 100.0

        # Collapse to one entry per dependency group (a singleton group per layer when
        # group_id is None, e.g. sparsity/quant). This stops a coupled group of N layers
        # from being double-counted as N independent knobs in the weighted-mean solve.
        prunable = [l for l in self.layers if l.prunable]
        not_prunable = [l for l in self.layers if not l.prunable]
        groups: OrderedDict[Any, dict] = OrderedDict()
        for l in prunable:
            key = l.group_id if l.group_id is not None else ("solo", l.name)
            g = groups.setdefault(key, {"names": [], "params": 0.0, "delta": 0.0})
            g["names"].append(l.name)
            g["params"] += float(l.params)
            g["delta"] = max(g["delta"], max(0.0, l.delta))  # delta is shared within a group

        # Not-prunable layers are protected at min_pct and kept out of the optimization
        targets: dict[str, float] = {l.name: round(float(min_pct), 2) for l in not_prunable}
        if not groups:
            return targets

        deltas = np.array([g["delta"] for g in groups.values()], dtype=float)
        weights = np.array([g["params"] for g in groups.values()], dtype=float)
        group_names = [g["names"] for g in groups.values()]

        if weights.sum() == 0:
            for names in group_names:
                for n in names: targets[n] = target_pct
            return targets
        
        # Normalize sensitivity and invert (high sensitivity -> low compression)
        if np.allclose(deltas, deltas[0]):
            s0 = np.full_like(deltas, target)
        else:
            norm = (deltas - deltas.min()) / (np.ptp(deltas) + 1e-12)
            inv = (1.0 - norm) ** gamma
            s0 = smin + (smax - smin) * inv
        
        # Binary search for lambda to hit target weighted mean
        W = weights.sum()
        tgt = target * W
        
        def f(lam):
            s = np.clip(s0 + lam, smin, smax)
            return float(np.dot(weights, s))
        
        # Find lambda via bisection
        lam_lo, lam_hi = -1.0, 1.0
        while f(lam_lo) > tgt:
            lam_lo *= 2
        while f(lam_hi) < tgt:
            lam_hi *= 2
        
        for _ in range(60):
            lam_mid = 0.5 * (lam_lo + lam_hi)
            if f(lam_mid) < tgt:
                lam_lo = lam_mid
            else:
                lam_hi = lam_mid
        
        final_s = np.clip(s0 + 0.5 * (lam_lo + lam_hi), smin, smax)

        # Expand each group's target back to all its member layers (they share the ratio)
        for names, s in zip(group_names, final_s):
            for n in names:
                targets[n] = round(s * 100, 2)
        return targets
    
    def plot(
        self,
        figsize: tuple = (12, 5),  # figure size (width, height)
    ) -> None:
        """Plot sensitivity as a bar chart."""
        import matplotlib.pyplot as plt
        
        names = [l.name for l in self.layers]
        deltas = np.array([l.delta for l in self.layers], dtype=float)
        
        # Color by sensitivity
        norm = (deltas - deltas.min()) / (np.ptp(deltas) + 1e-9)
        colors = plt.cm.RdYlGn_r(norm)  # Red=sensitive, Green=robust
        
        plt.figure(figsize=figsize)
        plt.bar(range(len(deltas)), deltas, color=colors)
        plt.axhline(0, color='gray', linewidth=1.2, linestyle='--')
        plt.xticks(range(len(names)), names, rotation=60, ha='right')
        plt.ylabel(f"{self.metric_name} drop (Δ)")
        plt.title(f"Layer Sensitivity to {self.compression_type} @ {self.compression_level}%", 
                  pad=12, weight='bold')
        plt.grid(axis='y', linestyle=':', alpha=0.6)
        plt.tight_layout()
        plt.show()

# %% ../../nbs/analyze/sensitivity.ipynb #analyzer
class SensitivityAnalyzer:
    """Analyze per-layer sensitivity to compression methods.
    
    Uses fasterai's Sparsifier for sparsity analysis and Pruner for structural pruning.
    Supports sparsity (weight zeroing), pruning (structural), and quantization.
    """
    
    VALID_COMPRESSIONS = frozenset({"sparsity", "pruning", "quantization"})
    COMPRESSIBLE_LAYERS = Granularities.available_modules()  # Use fasterai's layer registry
    
    def __init__(
        self,
        model: nn.Module,                              # model to analyze
        sample: torch.Tensor,                          # example input (for Pruner dependency analysis)
        eval_fn: Callable[[nn.Module], float],         # evaluation function returning metric
        *,
        criteria: Criteria = large_final,              # fasterai criteria for importance scoring
        higher_is_better: bool = True,                 # whether higher metric values are better
        metric_name: str = "accuracy",                 # name of the metric for display
        device: str | torch.device | None = None,      # device for computation
        calibration_data: torch.Tensor | None = None,  # for observer-based quantization
    ):
        store_attr()
        self.device = device or next(model.parameters()).device
        self._results: SensitivityResult | None = None
        self._sparsifier: Sparsifier | None = None
        self._activation_hooks: list[Any] = []
        self._activation_quantize_config: dict[str, bool] = {}

    @staticmethod
    def _out_dim(
        module: nn.Module,  # layer to inspect
    ) -> int | None:
        """Output channels (Conv) or features (Linear) of a layer."""
        return getattr(module, 'out_channels', None) or getattr(module, 'out_features', None)

    @staticmethod
    @contextmanager
    def _quiet():
        """Silence the per-construction notices fasterai's Pruner prints (ignore / per-layer info)."""
        import io, contextlib
        with contextlib.redirect_stdout(io.StringIO()):
            yield
    
    def _get_compressible_layers(
        self,
        layer_types: type | tuple[type, ...] | None = None,  # a module type or tuple of types to restrict to (None = all compressible)
    ) -> list[tuple[str, nn.Module]]:
        """Get all compressible layers (Conv2d, Linear, etc.), optionally filtered to `layer_types`."""
        if layer_types is None:
            types = self.COMPRESSIBLE_LAYERS
        else:
            types = (layer_types,) if isinstance(layer_types, type) else tuple(layer_types)
        return [
            (name, module) 
            for name, module in self.model.named_modules()
            if isinstance(module, self.COMPRESSIBLE_LAYERS) and isinstance(module, types)
            and hasattr(module, 'weight') and module.weight is not None
        ]
    
    def _init_sparsifier(
        self,
        granularity: str = "weight",  # sparsity granularity
    ) -> None:
        """Initialize fasterai Sparsifier (saves initial weights for all layers)."""
        if self._sparsifier is None:
            self._sparsifier = Sparsifier(
                self.model,
                granularity=granularity,
                context='local',
                criteria=self.criteria,
            )
    
    def _cleanup_sparsifier(self) -> None:
        """Remove sparsifier buffers from model."""
        if self._sparsifier is not None:
            self._sparsifier._clean_buffers()
            self._sparsifier = None
    
    def _apply_sparsity(
        self,
        module: nn.Module,  # layer to sparsify
        level: float,       # sparsity percentage (0-100)
    ) -> None:
        """Apply sparsity using fasterai Sparsifier."""
        self._sparsifier.sparsify_layer(module, level)
    
    def _restore_layer(
        self,
        module: nn.Module,  # layer to restore
    ) -> None:
        """Restore a single layer from saved initial weights."""
        if hasattr(module, '_init_weights'):
            module.weight.data.copy_(module._init_weights)
        if hasattr(module, '_init_biases') and module._init_biases is not None:
            module.bias.data.copy_(module._init_biases)
        if hasattr(module, '_mask'):
            del module._buffers['_mask']
    
    def _clone_model(self) -> nn.Module:
        """Create a clean copy of the model (avoids deepcopy issues with non-leaf tensors)."""
        import io
        buffer = io.BytesIO()
        torch.save(self.model, buffer)
        buffer.seek(0)
        model_copy = torch.load(buffer, weights_only=False)
        model_copy.eval()
        return model_copy

    def _fresh_copy(self) -> nn.Module:
        """A clean model copy (save/load), falling back to deepcopy if that fails."""
        try:
            return self._clone_model()
        except Exception:
            return deepcopy(self.model)

    def _channel_signature(
        self,
        model: nn.Module,  # model to fingerprint
    ) -> tuple:
        """Tuple of out-channels/out-features for every compressible layer (detects no-op prunes)."""
        return tuple(
            self._out_dim(m)
            for _, m in model.named_modules()
            if isinstance(m, self.COMPRESSIBLE_LAYERS)
        )

    def _build_dependency_groups(
        self,
        model: nn.Module,  # model to analyze (groups keyed by layer NAME, stable across clones)
    ) -> tuple[dict[str, int], dict[int, list[str]]]:
        """Map each compressible layer to its OUTPUT-coupled dependency group.

        Residual/skip connections force several layers to share an output-channel count, so
        pruning any one of them prunes all of them — and they yield the SAME accuracy delta.
        We detect these coupled sets (torch-pruning handler `prune_out_channels`) so the result
        can tag coupled layers with a shared `group_id` and so `to_layer_targets()` treats each
        coupled set as a single knob. Layers fasterai's Pruner ignores (output Linear, attention
        qkv) get no group — they are not independently prunable.

        Returns (name->group_id, group_id->member_names).
        """
        import torch_pruning as tp
        import warnings
        name_of = {m: n for n, m in model.named_modules()}
        with self._quiet():
            p = Pruner(model, pruning_ratio=0.5, context='local',
                       criteria=self.criteria, example_inputs=self.sample)
        DG = p.pruner.DG
        ignored = set(p.ignored_layers)

        name_to_coupled: dict[str, frozenset] = {}
        for name, mod in model.named_modules():
            if not isinstance(mod, self.COMPRESSIBLE_LAYERS) or mod in ignored:
                continue
            fn = tp.prune_conv_out_channels if isinstance(mod, nn.Conv2d) else tp.prune_linear_out_channels
            coupled = {name}
            try:
                group = DG.get_pruning_group(mod, fn, idxs=list(range(self._out_dim(mod))))
                for dep, _ in group:
                    tmod = dep.target.module
                    if (isinstance(tmod, self.COMPRESSIBLE_LAYERS) and tmod in name_of
                            and tmod not in ignored
                            and getattr(dep.handler, '__name__', '') == 'prune_out_channels'):
                        coupled.add(name_of[tmod])
            except Exception as e:
                # Treat as uncoupled (its own singleton group); warn for parity with the prune path
                warnings.warn(f"Could not resolve dependency group for {name}: {e}")
            name_to_coupled[name] = frozenset(coupled)

        # Assign a group id per unique coupled-set
        key_to_gid: dict[frozenset, int] = {}
        name_to_gid: dict[str, int] = {}
        gid_to_members: dict[int, list[str]] = {}
        for name, key in name_to_coupled.items():
            if key not in key_to_gid:
                key_to_gid[key] = len(key_to_gid)
                gid_to_members[key_to_gid[key]] = sorted(key)
            name_to_gid[name] = key_to_gid[key]
        return name_to_gid, gid_to_members

    def _apply_structural_pruning(
        self, 
        target_name: str,   # layer to prune — applied EXACTLY as a real per-layer dict prune
        level: float,       # pruning ratio (0-100)
    ) -> tuple[nn.Module, bool]:
        """Prune the target layer on a fresh model copy exactly as a real per-layer prune would.

        Uses fasterai's per-layer dict target `{target_name: level}`, so the measured
        degradation matches what the user gets from `Pruner(model, {target_name: level})`
        or `PruneCallback(pruning_ratio={target_name: level})` — including the residual cascade
        for coupled layers. This is what makes the reported Δ a faithful predictor of a real
        prune. Returns (pruned_model, prunable); prunable is False if the prune changed nothing.
        """
        import warnings
        model_copy = self._fresh_copy()
        if target_name not in dict(model_copy.named_modules()):
            return model_copy, False

        before = self._channel_signature(model_copy)
        try:
            with self._quiet():
                pruner = Pruner(
                    model_copy,
                    pruning_ratio={target_name: level},
                    context='local',
                    criteria=self.criteria,
                    example_inputs=self.sample,
                )
                pruner.prune_model()
        except Exception as e:
            warnings.warn(f"Structural pruning failed for {target_name}: {e}")
            # Never evaluate a half-pruned model — return a clean copy marked not-prunable
            return self._fresh_copy(), False

        prunable = self._channel_signature(model_copy) != before
        return model_copy, prunable
    
    # ─── Quantization helpers ────────────────────────────────────────────────────
    
    def _compute_qparams_symmetric(
        self,
        tensor: torch.Tensor,       # tensor to compute qparams for
        bits: int = 8,              # quantization bits
        per_channel: bool = False,  # per-channel or per-tensor
        channel_axis: int = 0,      # axis for per-channel quantization
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Compute scale and zero_point for symmetric quantization."""
        qmin, qmax = -(2 ** (bits - 1)), 2 ** (bits - 1) - 1
        
        if per_channel and tensor.dim() > 1:
            dims = list(range(tensor.dim()))
            dims.remove(channel_axis)
            amax = tensor.abs()
            for dim in sorted(dims, reverse=True):
                amax = amax.max(dim=dim).values
            scale = amax / qmax
            scale = torch.clamp(scale, min=1e-8)
            zero_point = torch.zeros_like(scale, dtype=torch.int32)
        else:
            amax = tensor.abs().max()
            scale = torch.tensor([max(amax.item() / qmax, 1e-8)], device=tensor.device)
            zero_point = torch.tensor([0], dtype=torch.int32, device=tensor.device)
        
        return scale, zero_point
    
    def _compute_qparams_asymmetric(
        self,
        tensor: torch.Tensor,       # tensor to compute qparams for
        bits: int = 8,              # quantization bits
        per_channel: bool = False,  # per-channel or per-tensor
        channel_axis: int = 0,      # axis for per-channel quantization
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Compute scale and zero_point for asymmetric quantization."""
        qmin, qmax = 0, 2 ** bits - 1
        
        if per_channel and tensor.dim() > 1:
            dims = list(range(tensor.dim()))
            dims.remove(channel_axis)
            t_min, t_max = tensor.clone(), tensor.clone()
            for dim in sorted(dims, reverse=True):
                t_min = t_min.min(dim=dim).values
                t_max = t_max.max(dim=dim).values
        else:
            t_min, t_max = tensor.min(), tensor.max()
        
        scale = (t_max - t_min) / (qmax - qmin)
        scale = torch.clamp(scale, min=1e-8)
        zero_point = torch.clamp(torch.round(-t_min / scale), qmin, qmax).to(torch.int32)
        
        if not per_channel or tensor.dim() <= 1:
            scale = scale.view(1) if scale.dim() == 0 else scale
            zero_point = zero_point.view(1) if zero_point.dim() == 0 else zero_point
        
        return scale, zero_point
    
    def _fake_quantize_per_channel(
        self,
        tensor: torch.Tensor,      # tensor to quantize
        bits: int = 8,             # quantization bits
        symmetric: bool = True,    # symmetric or asymmetric
        channel_axis: int = 0,     # axis for per-channel quantization
    ) -> torch.Tensor:
        """Apply fake quantization (per-channel)."""
        qmin = -(2 ** (bits - 1)) if symmetric else 0
        qmax = (2 ** (bits - 1)) - 1 if symmetric else (2 ** bits) - 1
        
        if symmetric:
            scale, zero_point = self._compute_qparams_symmetric(
                tensor, bits, per_channel=True, channel_axis=channel_axis
            )
        else:
            scale, zero_point = self._compute_qparams_asymmetric(
                tensor, bits, per_channel=True, channel_axis=channel_axis
            )
        
        return torch.fake_quantize_per_channel_affine(
            tensor, scale, zero_point, channel_axis, qmin, qmax
        )
    
    def _fake_quantize_per_tensor(
        self,
        tensor: torch.Tensor,    # tensor to quantize
        bits: int = 8,           # quantization bits
        symmetric: bool = True,  # symmetric or asymmetric
    ) -> torch.Tensor:
        """Apply fake quantization (per-tensor)."""
        qmin = -(2 ** (bits - 1)) if symmetric else 0
        qmax = (2 ** (bits - 1)) - 1 if symmetric else (2 ** bits) - 1
        
        if symmetric:
            scale, zero_point = self._compute_qparams_symmetric(tensor, bits, per_channel=False)
        else:
            scale, zero_point = self._compute_qparams_asymmetric(tensor, bits, per_channel=False)
        
        return torch.fake_quantize_per_tensor_affine(
            tensor, scale.item(), int(zero_point.item()), qmin, qmax
        )
    
    def _apply_weight_quantization(
        self, 
        module: nn.Module,       # layer to quantize
        bits: int = 8,           # quantization bits
        per_channel: bool = True,  # per-channel or per-tensor
    ) -> None:
        """Apply weight quantization using fake_quantize."""
        weight = module.weight.data
        if per_channel and weight.dim() > 1:
            quantized = self._fake_quantize_per_channel(weight, bits, symmetric=True, channel_axis=0)
        else:
            quantized = self._fake_quantize_per_tensor(weight, bits, symmetric=True)
        weight.copy_(quantized)
    
    def _create_activation_quantize_hook(
        self,
        layer_name: str,  # layer name for config lookup
        bits: int = 8,    # quantization bits
    ):
        """Create a forward hook that quantizes activations."""
        def hook(module, input, output):
            if self._activation_quantize_config.get(layer_name, False):
                return self._fake_quantize_per_tensor(output, bits, symmetric=False)
            return output
        return hook
    
    def _setup_activation_hooks(
        self,
        bits: int = 8,  # quantization bits
    ) -> None:
        """Register activation quantization hooks on all layers."""
        self._remove_activation_hooks()
        for name, module in self._get_compressible_layers():
            hook = self._create_activation_quantize_hook(name, bits)
            handle = module.register_forward_hook(hook)
            self._activation_hooks.append(handle)
            self._activation_quantize_config[name] = False
    
    def _remove_activation_hooks(self) -> None:
        """Remove all activation quantization hooks."""
        for handle in self._activation_hooks:
            handle.remove()
        self._activation_hooks = []
        self._activation_quantize_config = {}
    
    # ─── Main analysis method ────────────────────────────────────────────────────
    
    def analyze(
        self,
        compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",  # compression type
        level: float = 50,                    # compression level (% for sparsity/pruning, bits for quant)
        *,
        granularity: str = "weight",          # granularity for sparsity (fasterai granularities)
        layers: list[str] | None = None,      # specific layer names to analyze (None = all)
        layer_types: type | tuple[type, ...] | None = None,  # restrict to a module type or tuple of types, e.g. nn.Conv2d or (nn.Conv2d, nn.Linear) (None = all compressible)
        quant_per_channel: bool = True,       # use per-channel quantization
        quant_activations: bool = False,      # also quantize activations
        verbose: bool = True,                 # print progress
    ) -> SensitivityResult:
        """Analyze per-layer sensitivity to compression.

        For **pruning**, each layer is pruned with the per-layer target `{name: level}` — the
        exact operation `Pruner`/`PruneCallback` perform — so the reported Δ faithfully predicts
        the degradation of really pruning that layer at `level`. Residual/skip-coupled layers
        prune together and therefore share a Δ (tagged with a common `group_id`); layers that
        cannot be pruned independently (output Linear, attention) are marked `prunable=False`.

        Pass `layer_types` to restrict the analysis to specific module types — a single type or
        a tuple, e.g. `layer_types=nn.Conv2d` analyses only convolutions and skips the
        classifier `Linear`.
        """
        if compression not in self.VALID_COMPRESSIONS:
            raise ValueError(f"compression must be one of {self.VALID_COMPRESSIONS}")
        
        self.model.eval()
        
        if compression == "sparsity":
            self._init_sparsifier(granularity)
        
        if compression == "quantization" and quant_activations:
            bits = int(level) if level > 1 else 8
            self._setup_activation_hooks(bits)
        
        if verbose:
            print(f"Computing baseline {self.metric_name}...", end=" ", flush=True)
        baseline = self.eval_fn(self.model)
        if verbose:
            print(f"{baseline:.4f}")
        
        all_layers = self._get_compressible_layers(layer_types)
        if layers is not None:
            all_layers = [(n, m) for n, m in all_layers if n in layers]

        # Pruning: precompute dependency groups once so coupled layers can share a group_id
        # and each coupled set is only pruned/evaluated a single time (deduped by group id).
        group_gid: dict[str, int] = {}
        group_members: dict[int, list[str]] = {}
        group_cache: dict[int, tuple[float, bool]] = {}
        if compression == "pruning":
            group_gid, group_members = self._build_dependency_groups(self.model)
        
        mode_info = ""
        if compression == "quantization":
            mode_info = f" (per-{'channel' if quant_per_channel else 'tensor'}"
            mode_info += f", {'weights+activations' if quant_activations else 'weights only'})"
        elif compression == "sparsity":
            mode_info = f" (granularity={granularity}, criteria={self.criteria.f.__name__})"
        elif compression == "pruning":
            mode_info = f" (structural group-sensitivity, criteria={self.criteria.f.__name__})"
        
        if verbose:
            unit = 'bits' if compression == 'quantization' else '%'
            print(f"Analyzing {len(all_layers)} layers for {compression} @ {level}{unit}{mode_info}")
        
        results: list[LayerSensitivity] = []
        
        for i, (name, module) in enumerate(all_layers):
            if verbose:
                print(f"  [{i+1}/{len(all_layers)}] {name}...", end=" ", flush=True)

            prunable = True
            gid = group_gid.get(name)  # None for sparsity/quant and for ignored (output/attention) layers
            if compression == "sparsity":
                self._apply_sparsity(module, level)
                compressed_metric = self.eval_fn(self.model)
                self._restore_layer(module)
                param_count = module.weight.numel()
                
            elif compression == "pruning":
                if gid is None:
                    # ignored layer (output Linear / attention) — not independently prunable
                    compressed_metric, prunable = baseline, False
                elif gid in group_cache:
                    compressed_metric, prunable = group_cache[gid]  # coupled member: reuse the group's prune
                else:
                    pruned_model, prunable = self._apply_structural_pruning(name, level)
                    compressed_metric = self.eval_fn(pruned_model) if prunable else baseline
                    del pruned_model
                    group_cache[gid] = (compressed_metric, prunable)
                param_count = module.weight.numel()
                
            elif compression == "quantization":
                saved_weight = module.weight.data.clone()
                saved_bias = module.bias.data.clone() if module.bias is not None else None
                
                bits = int(level) if level > 1 else 8
                self._apply_weight_quantization(module, bits, per_channel=quant_per_channel)
                
                if quant_activations:
                    self._activation_quantize_config[name] = True
                
                compressed_metric = self.eval_fn(self.model)
                
                if quant_activations:
                    self._activation_quantize_config[name] = False
                
                module.weight.data.copy_(saved_weight)
                if saved_bias is not None:
                    module.bias.data.copy_(saved_bias)
                param_count = module.weight.numel()
            
            if self.higher_is_better:
                delta = baseline - compressed_metric
            else:
                delta = compressed_metric - baseline
            
            if verbose:
                sign = "+" if delta > 0 else ""
                tag = "" if prunable else " (not prunable)"
                print(f"Δ={sign}{delta:.4f}{tag}")
            
            results.append(LayerSensitivity(
                name=name,
                layer_type=module.__class__.__name__,
                params=param_count,
                baseline_metric=baseline,
                compressed_metric=compressed_metric,
                delta=delta,
                group_id=gid,
                group_members=group_members.get(gid, []),
                prunable=prunable,
            ))
        
        if compression == "sparsity":
            self._cleanup_sparsifier()
        if compression == "quantization" and quant_activations:
            self._remove_activation_hooks()
        
        compression_desc = compression
        if compression == "quantization":
            compression_desc = f"quantization-{int(level) if level > 1 else 8}bit"
            if quant_activations:
                compression_desc += "+act"
        
        self._results = SensitivityResult(
            compression_type=compression_desc,
            compression_level=level,
            baseline_metric=baseline,
            layers=results,
            metric_name=self.metric_name,
            higher_is_better=self.higher_is_better,
        )
        
        if verbose:
            print(f"✓ Analysis complete")
        
        return self._results
    
    def sweep(
        self,
        compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",  # compression type
        levels: list[float] | None = None,  # compression levels to test (default: [25, 50, 75])
        **kwargs,
    ) -> list[SensitivityResult]:
        """Run sensitivity analysis at multiple compression levels."""
        if levels is None:
            levels = [25, 50, 75]
        results = []
        for level in levels:
            print(f"\n{'='*60}")
            unit = 'bits' if compression == 'quantization' else '%'
            print(f"Sweep: {compression} @ {level}{unit}")
            print(f"{'='*60}")
            result = self.analyze(compression, level, **kwargs)
            results.append(result)
        return results

# %% ../../nbs/analyze/sensitivity.ipynb #convenience
def analyze_sensitivity(
    model: nn.Module,                    # model to analyze
    sample: torch.Tensor,                # example input tensor
    eval_fn: Callable[[nn.Module], float],  # evaluation function returning metric
    compression: Literal["sparsity", "pruning", "quantization"] = "sparsity",  # compression type
    level: float = 50,                   # compression level (% for sparsity/pruning, bits for quant)
    *,
    criteria: Criteria = large_final,    # fasterai criteria for importance scoring
    higher_is_better: bool = True,       # whether higher metric values are better
    metric_name: str = "accuracy",       # name of the metric for display
    granularity: str = "weight",         # granularity for sparsity
    verbose: bool = True,                # print progress
    **kwargs,
) -> SensitivityResult:
    """One-line sensitivity analysis using fasterai compression methods."""
    analyzer = SensitivityAnalyzer(
        model, sample, eval_fn, 
        criteria=criteria, 
        higher_is_better=higher_is_better,
        metric_name=metric_name,
    )
    return analyzer.analyze(compression, level, granularity=granularity, verbose=verbose, **kwargs)
