# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/criteria.ipynb.

# %% ../../nbs/core/criteria.ipynb #hungarian-american
from __future__ import annotations
import torch
import torch.nn as nn
import torch.nn.functional as F
from fastcore.basics import *
from fastcore.imports import *
from .granularity import *
from typing import Callable, Any
from enum import Enum, auto

# %% auto #0
__all__ = ['EPS', 'random', 'large_final', 'squared_final', 'small_final', 'large_init', 'small_init', 'large_init_large_final',
           'small_init_small_final', 'magnitude_increase', 'movement', 'updating_magnitude_increase',
           'updating_movement', 'updating_movmag', 'criterias', 'wanda', 'Reducer', 'Normalizer', 'Criteria',
           'magnitude_criteria', 'init_based_criteria', 'update_based_criteria', 'available_criterias',
           'activation_criteria', 'grad_crit']

# %% ../../nbs/core/criteria.ipynb #7739ca4c-6644-4f19-9c15-d1bb57c2cf29
EPS = torch.finfo(torch.float32).eps

# %% ../../nbs/core/criteria.ipynb #fa09b055-e69f-450a-b054-1b6305fe5b79
class Reducer:
    @staticmethod
    def sum(scores, dim):
        return scores[None].sum(dim=dim, keepdim=True).squeeze(0)
    
    @staticmethod
    def mean(scores, dim):
        return scores[None].mean(dim=dim, keepdim=True).squeeze(0)

# %% ../../nbs/core/criteria.ipynb #2b7fd75e-e0de-4e86-9522-f52e5a2c0c26
class Normalizer:
    @staticmethod
    def sum(scores):
        return scores / scores.sum()
    
    @staticmethod
    def standardization(scores):
        return (scores - scores.min()) / (scores.max() - scores.min() + EPS)
    
    @staticmethod
    def mean(scores):
        return scores / scores.mean()
    
    @staticmethod
    def max(scores):
        return scores / scores.max()
    
    @staticmethod
    def gaussian(scores):
        return (scores - scores.mean()) / (scores.std() + EPS)

# %% ../../nbs/core/criteria.ipynb #01499c0f
_DATA_FNS = {
    'l2_norm': lambda x, dim: x.pow(2).sum(dim=dim),
    'max':     lambda x, dim: x.abs().amax(dim=dim),
    'mean':    lambda x, dim: x.abs().mean(dim=dim),
}

class Criteria():
    def __init__(self, 
                 f:Callable[[torch.Tensor], torch.Tensor],                                         # Function that transforms weights (e.g., torch.abs, torch.square)
                 reducer: Callable = Reducer.mean,                                                 # Method to reduce dimensions ('mean' or 'sum')
                 normalizer: Callable | None = None,                                               # Method to normalize scores (None, 'sum', 'standardization', 'mean', 'max', 'gaussian')
                 needs_init:bool=False,                                                            # Whether this criteria needs the initial weights
                 needs_update:bool=False,                                                          # Whether this criteria needs to track weight updates between iterations
                 output_fn: Callable[[torch.Tensor, torch.Tensor], torch.Tensor] | None = None,    # Function to combine current and reference weights
                 return_init=False,                                                                # Whether to return the transformed initial weights instead of final output
                 scale: dict[nn.Module, torch.Tensor] | None = None,                               # Per-layer scale factors (e.g., activation norms for Wanda)
                 needs_data: bool = False,                                                         # Whether this criteria needs calibration data
                 data_fn: str = 'l2_norm',                                                         # Activation statistic to collect: 'l2_norm', 'max', 'mean'
    ):
        "Evaluates neural network parameters based on various criteria for pruning"
        store_attr()
        assert (needs_init and needs_update)==False, "The init values will be overwritten by the updating ones."

    def calibrate(self,
                  model: nn.Module,                         # Model to calibrate
                  data,                                     # Calibration data (tensor, list of batches, or DataLoader)
                  layer_type: type[nn.Module] = nn.Conv2d,  # Layer types to collect activations for
                  n_batches: int = 5,                       # Number of batches to process
    ) -> None:
        "Collect per-channel activation statistics via forward hooks"
        device = next(model.parameters()).device
        accum_fn = _DATA_FNS[self.data_fn]
        state = {}

        # Register hooks
        hooks = []
        for m in model.modules():
            if isinstance(m, layer_type):
                state[m] = {'acc': torch.zeros(m.weight.shape[1], device=device), 'n': 0}
                def make_hook(module):
                    def hook(mod, inp):
                        x = inp[0].detach()
                        dims = [i for i in range(x.dim()) if i != 1]
                        state[module]['acc'] += accum_fn(x, dims)
                        state[module]['n'] += x.shape[0]
                    return hook
                hooks.append(m.register_forward_pre_hook(make_hook(m)))

        # Forward pass
        model.eval()
        with torch.no_grad():
            if isinstance(data, torch.Tensor):
                model(data.to(device))
            else:
                for n, batch in enumerate(data):
                    if n >= n_batches: break
                    xb = batch[0] if isinstance(batch, (tuple, list)) else batch
                    model(xb.as_subclass(torch.Tensor).to(device))

        for h in hooks: h.remove()

        # Finalize: for l2_norm take sqrt of mean, for others just mean
        finalize = (lambda acc, n: (acc / max(n, 1)).sqrt()) if self.data_fn == 'l2_norm' \
                   else (lambda acc, n: acc / max(n, 1))
        self.scale = {m: finalize(s['acc'], s['n']) for m, s in state.items()}

    @torch.no_grad()
    def __call__(self, 
                 m: nn.Module,  # The module to compute scores for
                 g: str,        # Granularity specification
                 squeeze=False  # Whether to squeeze singleton dimensions
    ) -> torch.Tensor:
        "Compute criteria scores for module weights"
        try:
            dim = listify(Granularities.get_dim(m, g))
        except KeyError:
            raise ValueError(f'Invalid granularity "{g}" for module type {type(m).__name__}')
            
        if self.needs_update and not hasattr(m, '_old_weights'):
            m.register_buffer("_old_weights", m._init_weights.clone())
            
        wf = self.f(m.weight)
        
        if self.needs_init: wi = self.f(m._init_weights)
        if self.needs_update: wi = self.f(m._old_weights)
        
        if self.output_fn: scores = self.output_fn(wf, wi)
        elif self.return_init: scores = wi
        else: scores = wf

        if self.scale and m in self.scale:
            scores = torch.einsum('oi..., i -> oi...', scores, self.scale[m])
            
        scores = self._rescale(scores)
        if hasattr(m, '_mask'): scores.mul_(m._mask)
        scores = self._reduce(scores, dim)
        scores = self._normalize(scores)
        if squeeze: scores = scores[None].squeeze((0,*dim))
        return scores
    
    def _reduce(self, scores, dim):
        "Reduce scores along specified dimensions"
        return self.reducer(scores, dim)
            
    def _normalize(self, scores):
        "Normalize scores using the specified method"
        if self.normalizer is None: return scores
        return self.normalizer(scores)

    def _rescale(self, scores):
        "Ensure all scores are positive to maintain pruning behavior"
        min_val = scores.min()
        if min_val < 0: scores.add_(-min_val)
        scores.add_(EPS)
        return scores

    def update_weights(self, m):
        "Update the reference weights for criteria that track changes"
        if self.needs_update: 
            m._old_weights = m.weight.data.clone()

# %% ../../nbs/core/criteria.ipynb #abfb02c7-d6b7-4666-aff4-449745f06ac0
def magnitude_criteria(transform_fn, **kwargs):
     "Create a criteria based on weight magnitude transformation."
     return Criteria(transform_fn, **kwargs)

# %% ../../nbs/core/criteria.ipynb #handled-episode
random = magnitude_criteria(torch.randn_like)

# %% ../../nbs/core/criteria.ipynb #loaded-clearance
large_final = magnitude_criteria(torch.abs)

# %% ../../nbs/core/criteria.ipynb #d2f2add2
squared_final = magnitude_criteria(torch.square)

# %% ../../nbs/core/criteria.ipynb #going-cooperative
small_final = magnitude_criteria(compose(torch.abs, torch.neg))

# %% ../../nbs/core/criteria.ipynb #11e2e298-cfd1-4c92-bf40-344a3ed7b1f9
def init_based_criteria(transform_fn, output_fn=None, return_init=False, **kwargs):
     "Create a criteria that compares current weights to initial weights."
     return Criteria(transform_fn, needs_init=True, output_fn=output_fn, return_init=return_init, **kwargs)

# %% ../../nbs/core/criteria.ipynb #communist-planet
large_init = init_based_criteria(torch.abs, return_init=True)

# %% ../../nbs/core/criteria.ipynb #suspended-responsibility
small_init = init_based_criteria(compose(torch.abs, torch.neg), return_init=True)

# %% ../../nbs/core/criteria.ipynb #cosmetic-producer
large_init_large_final = init_based_criteria(torch.abs, output_fn=torch.min)

# %% ../../nbs/core/criteria.ipynb #romance-intervention
small_init_small_final = init_based_criteria(torch.abs, output_fn=lambda x,y: torch.neg(torch.max(x,y)))

# %% ../../nbs/core/criteria.ipynb #middle-deficit
magnitude_increase = init_based_criteria(torch.abs, output_fn= torch.sub)

# %% ../../nbs/core/criteria.ipynb #given-america
movement = init_based_criteria(noop, output_fn= lambda x,y: torch.abs(torch.sub(x,y)))

# %% ../../nbs/core/criteria.ipynb #620b7160-f05e-4fa8-ba48-3953bd15751d
def update_based_criteria(transform_fn, output_fn=None, **kwargs):
     "Create a criteria that compares current weights to previous iteration weights."
     return Criteria(transform_fn, needs_update=True, output_fn=output_fn, **kwargs)

# %% ../../nbs/core/criteria.ipynb #c06a5dbe
updating_magnitude_increase = update_based_criteria(torch.abs, output_fn= lambda x,y: torch.sub(x,y))

# %% ../../nbs/core/criteria.ipynb #superb-witness
updating_movement = update_based_criteria(noop, output_fn= lambda x,y: torch.abs(torch.sub(x,y)))

# %% ../../nbs/core/criteria.ipynb #b3c1d918
updating_movmag = update_based_criteria(noop, output_fn=lambda x,y: torch.abs(torch.mul(x, torch.sub(x,y))))

# %% ../../nbs/core/criteria.ipynb #151a382e
criterias = (
    'random',              # Random scores
    'large_final',         # Large absolute weight values
    'small_final',         # Small absolute weight values
    'squared_final',       # Squared weight values
    'large_init',          # Large initial weight values
    'small_init',          # Small initial weight values
    'large_init_large_final',  # Minimum of initial and final magnitude
    'small_init_small_final',  # Maximum of initial and final magnitude (negated)
    'magnitude_increase',      # Increase in magnitude from init
    'movement',                # Absolute change from init
    'updating_magnitude_increase',  # Increase in magnitude from previous step
    'updating_movement',           # Absolute change from previous step
    'movmag',                      # Movement * magnitude from init
    'updating_movmag'              # Movement * magnitude from previous step
 )

def available_criterias():
    "Return the list of available criteria names"
    return criterias

# %% ../../nbs/core/criteria.ipynb #i52myvrfz6
def activation_criteria(transform_fn, data_fn='l2_norm', **kwargs):
    "Create a criteria that uses activation statistics to weight scores"
    return Criteria(transform_fn, needs_data=True, data_fn=data_fn, **kwargs)

# %% ../../nbs/core/criteria.ipynb #y090ywrz0h
wanda = activation_criteria(torch.abs)

# %% ../../nbs/core/criteria.ipynb #1a59b37f
def grad_crit(
    m: nn.Module,  # module to compute gradient-based importance for
    g: str,        # granularity specification
) -> torch.Tensor:
    """First order Taylor expansion criterion for weight importance (Nvidia Taylor Pruning)."""
    try:
        dim = listify(Granularities.get_dim(m, g))
    except KeyError:
        raise ValueError(f'Invalid granularity "{g}" for module type {type(m).__name__}')
    
    if m.weight.grad is not None:
        return (m.weight * m.weight.grad)[None].pow(2).mean(dim=dim, keepdim=True).squeeze(0)
    else:
        return m.weight[None].pow(2).mean(dim=dim, keepdim=True).squeeze(0)
