# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/parametrize.ipynb.

# %% ../../nbs/core/parametrize.ipynb #imports
from __future__ import annotations

import torch
import torch.nn as nn
from torch.nn.utils import parametrize

# %% auto #0
__all__ = []

# %% ../../nbs/core/parametrize.ipynb #helpers
def _is_parametrized(m: nn.Module) -> bool:
    "Whether something computes `m.weight` from a master parameter"
    return parametrize.is_parametrized(m, 'weight')


def _master(m: nn.Module):
    "The parameter `m.weight` is computed from, or `m.weight` itself when nothing parametrizes it"
    return m.parametrizations.weight.original if _is_parametrized(m) else m.weight


def _plain_modules(
    model: nn.Module,
):
    "The modules of `model`, without the containers a parametrization inserts under the one it rewrites"
    for name, m in model.named_modules():
        if 'parametrizations' not in name.split('.'): yield m


def _unparametrize(
    m: nn.Module,
    leave_parametrized: bool = False,  # Keep the computed weight; False restores the master
) -> None:
    "Drop the weight parametrization, if there is one, and make `m.weight` an ordinary parameter again"
    if not _is_parametrized(m): return
    # a module parametrizing a second tensor is left to torch, whose removal deletes the property from
    # the injected class: a deepcopy of THAT module breaks, exactly as it would without this helper
    if len(m.parametrizations) > 1:
        parametrize.remove_parametrizations(m, 'weight', leave_parametrized)
        return
    master = m.parametrizations.weight.original
    if leave_parametrized:
        with torch.no_grad(): master.set_(m.weight.detach())  # the same object, so no optimizer rebinding
    del m._modules['parametrizations']
    # torch's own removal deletes the property from the injected class, which a deepcopy of this module
    # SHARES: giving the plain class back instead leaves every copy of it working
    m.__class__ = m.__class__.__bases__[0]
    if isinstance(master, nn.Parameter): m.register_parameter('weight', master)
    else: m.register_buffer('weight', master)
