# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/ratio.ipynb.

# %% ../../nbs/core/ratio.ipynb #imports
from __future__ import annotations

import warnings
from numbers import Real

# %% auto #0
__all__ = ['as_fraction']

# %% ../../nbs/core/ratio.ipynb #as-fraction
_FRACTION = "a fraction in [0, 1] (0.4 = 40%)"


def as_fraction(x, name: str, layer: str | None = None, allow_zero: bool = True) -> float:
    "Read a compression ratio as a fraction in [0, 1]; a value in (1, 100] is read as a percent for one release"
    where = f"{name} for layer '{layer}'" if layer is not None else name
    if isinstance(x, bool) or not isinstance(x, Real):
        raise TypeError(f"{where} must be a number, {_FRACTION}, got {x!r}")
    x = float(x)
    if not (0 <= x <= 100):
        raise ValueError(f"{where} must be {_FRACTION}, got {x!r}")
    if x > 1:
        warnings.warn(f"{where}={x!r} looks like a percent; this argument is {_FRACTION}; "
                      f"read as {x!r}/100 = {x / 100!r} for one release — pass the fraction",
                      FutureWarning, stacklevel=2)
        x = x / 100
    if x == 0 and not allow_zero:
        raise ValueError(f"{where} must be {_FRACTION} and above 0 — a ratio of 0 removes nothing")
    return x
