# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/sparse/sparsifier.ipynb.

# %% ../../nbs/sparse/sparsifier.ipynb #686a522f
from __future__ import annotations
import copy
import torch
import torch.nn as nn
from fastcore.basics import store_attr, true
from typing import Type
from ..core.criteria import *
from ..core.ratio import as_fraction
from einops import rearrange

# %% auto #0
__all__ = ['Sparsifier']

# %% ../../nbs/sparse/sparsifier.ipynb #c15c6bb1
class Sparsifier():
    "Class providing sparsifying capabilities"
    def __init__(self, 
                 model: nn.Module,
                 granularity: str,                        # Granularity of sparsification (e.g., 'weight', 'filter')
                 context: str,                            # 'global' or 'local'
                 criteria: Criteria,                      # Criteria to determine which weights to keep
                 nm: bool = False,                        # Use an N:M sparsity pattern (forces 2:4)
                 layer_type: Type[nn.Module] = nn.Conv2d,
                 data = None,                             # Calibration data for activation-based criteria (e.g., wanda)
    ):
        if nm: print('Sparsity automatically set to 50% with 2:4 pattern')
        store_attr('model,granularity,context,criteria,nm,layer_type')
        self._save_weights()
        self._reset_threshold()
        if getattr(self.criteria, 'needs_data', False):
            if data is None:
                raise ValueError(f"Criteria requires calibration data. Pass data= to Sparsifier.")
            self.criteria.calibrate(model, data, layer_type)

    def _iter_layers(self, 
                     filter_type: str = 'layer_type',
                     model: nn.Module | None = None
    ):
        model = model or self.model
        for m in model.modules():
            if filter_type == 'layer_type' and isinstance(m, self.layer_type):
                yield m
            elif filter_type == 'has_weight' and hasattr(m, 'weight'):
                yield m

    def _iter_named_layers(self):
        for name, m in self.model.named_modules():
            if isinstance(m, self.layer_type):
                yield name, m

    def _to_sparsity_dict(self, 
                          sparsity: float | dict
    ) -> dict:
        "Convert any sparsity input to a {module: fraction} dict"
        if not isinstance(sparsity, dict):
            sp = as_fraction(sparsity, 'sparsity')
            return {m: sp for m in self._iter_layers()}

        name_to_module = dict(self.model.named_modules())
        resolved = {}
        for key, sp in sparsity.items():
            if isinstance(key, str):
                sp = as_fraction(sp, 'sparsity', layer=key)
                if key in name_to_module: resolved[name_to_module[key]] = sp
                else: print(f"Warning: Layer '{key}' not found in model, skipping")
            elif isinstance(key, nn.Module):
                resolved[key] = as_fraction(sp, 'sparsity', layer=key.__class__.__name__)
        return resolved

    def sparsify_layer(self, 
                       m: nn.Module,
                       sparsity: float,             # Target sparsity, a fraction in [0, 1] (0.4 = 40%)
                       round_to: int | None = None  # Round to a multiple of this value
    ) -> None:
        "Apply sparsification to a single layer"
        sparsity  = as_fraction(sparsity, 'sparsity')
        scores    = self.criteria(m, self.granularity)
        threshold = self._compute_threshold(scores, sparsity, round_to)
        mask      = self._compute_mask(scores, threshold)
        m.register_buffer('_mask', mask)
        self._apply(m)
        self.criteria.update_weights(m)

    def sparsify_model(self, 
                       sparsity: float | dict,        # Target sparsity, a fraction in [0, 1] (0.4 = 40%), or a per-layer dict
                       round_to: int | None = None    # Round to a multiple of this value
    ) -> None:
        "Apply sparsification to all matching layers in the model"
        self._reset_threshold()
        
        if isinstance(sparsity, dict) and self.context == 'global':
            raise ValueError("Dict-based sparsity requires 'local' context")
        
        sparsity_map = self._to_sparsity_dict(sparsity)
        
        mods = list(self.model.modules())
        for name, m in self._iter_named_layers():
            if m not in sparsity_map:
                continue
            sp = sparsity_map[m]
            self.sparsify_layer(m, sp, round_to)
            # heuristic: the BN is assumed to be the next module in registration order
            mod_idx = mods.index(m)
            if mod_idx + 1 < len(mods) and isinstance(mods[mod_idx + 1], nn.modules.batchnorm._BatchNorm):
                self.sparsify_batchnorm(m, mods[mod_idx + 1])
                
    def sparsify_batchnorm(self, 
                          m: nn.Module,       # The layer before batch norm
                          bn: nn.Module
    ) -> None:
        "Apply filter pruning to batch norm parameters if appropriate"
        mask = getattr(m, "_mask", None)
        if self.granularity == 'filter' and true(mask):
            bn.weight.data.mul_(mask.squeeze())
            bn.bias.data.mul_(mask.squeeze())
            
    def _apply_masks(self) -> None:
        for m in self._iter_layers():
            self._apply(m)
        
    def _apply(self, 
              m: nn.Module
    ) -> None:
        mask = getattr(m, "_mask", None)
        if true(mask): m.weight.data.mul_(mask)
        if self.granularity == 'filter' and true(m.bias):
            if true(mask): m.bias.data.mul_(mask.squeeze())
    
    def _reset_weights(self, 
                      model: nn.Module | None = None
    ) -> None:
        "Reset weights to their initial values"
        model = model or self.model
        for m in self._iter_layers('has_weight', model):
            init_weights = getattr(m, "_init_weights", m.weight)
            init_biases = getattr(m, "_init_biases", m.bias)
            with torch.no_grad():
                if true(m.weight): m.weight.copy_(init_weights)
                if true(m.bias): m.bias.copy_(init_biases)
            self._apply(m)
            if isinstance(m, nn.modules.batchnorm._BatchNorm): m.reset_parameters()
                
    def _save_weights(self) -> None:
        "Save initial weights of the model, detached so the model stays copyable"
        for m in self._iter_layers('has_weight'):
            m.register_buffer("_init_weights", m.weight.detach().clone())
            bias = getattr(m, 'bias', None)
            if true(bias): m.register_buffer("_init_biases", bias.detach().clone())
                    
    def save_model(self, 
                  path: str,
                  model: nn.Module | None = None        # Model to save; None = self.model
    ) -> None:
        "Save model without sparsification buffers"
        model = model or self.model
        tmp_model = copy.deepcopy(model)
        self._reset_weights(tmp_model)
        self._clean_buffers(tmp_model)
        torch.save(tmp_model, path)

    def _clean_buffers(self, 
                      model: nn.Module | None = None
    ) -> None:
        "Remove internal buffers used for sparsification"
        model = model or self.model
        for m in self._iter_layers('has_weight', model):
            if hasattr(m, '_mask'): del m._buffers["_mask"]
            if hasattr(m, '_init_weights'): del m._buffers["_init_weights"]
            if hasattr(m, '_init_biases'): del m._buffers["_init_biases"]
                    
    def _reset_threshold(self) -> None:
        "Reset the threshold used for global pruning"
        self.threshold = None
            
    def _rounded_sparsity(self, 
                         n_to_keep: int,
                         round_to: int
    ) -> int:
        "Round the number of elements to keep to a multiple of round_to"
        if round_to == 0:
            raise ValueError("round_to must be non-zero")
        return max(round_to * torch.ceil(n_to_keep / round_to), round_to)
    
    @staticmethod
    def _kth_value(scores: torch.Tensor, fraction: float) -> torch.Tensor:
        "Find the value at a given fraction (like quantile, but no size limit)"
        k = max(1, int(fraction * scores.numel()))
        return scores.kthvalue(k).values

    def _compute_threshold(self, scores: torch.Tensor, sparsity: float, round_to: int | None) -> torch.Tensor:
        if self.context == 'global':
            if self.threshold is None: 
                global_scores = torch.cat([self.criteria(m, self.granularity).view(-1) for m in self._iter_layers()])
                self.threshold = self._kth_value(global_scores.view(-1), sparsity)
        elif self.context == 'local': 
            self.threshold = self._kth_value(scores.view(-1), sparsity)
        else: 
            raise ValueError(f'Invalid context: {self.context}. Must be "global" or "local"')
            
        if round_to:
            n_to_keep = sum(scores.ge(self.threshold)).squeeze()
            self.threshold = torch.topk(scores.squeeze(), int(self._rounded_sparsity(n_to_keep, round_to)))[0].min()
        return self.threshold
    
    def _compute_mask(self, 
                     scores: torch.Tensor,
                     threshold: torch.Tensor
    ) -> torch.Tensor:
        if self.nm: return self._apply_nm_sparsity(scores)
        if threshold > scores.max(): threshold = scores.max()
        return scores.ge(threshold).to(dtype=scores.dtype)

    def _apply_nm_sparsity(self, 
                          scores: torch.Tensor
    ) -> torch.Tensor:
        "Apply the 2:4 structured sparsity pattern"
        out_channels, in_channels, kernel_height, kernel_width = scores.shape
    
        if in_channels % 4 != 0 or in_channels * kernel_height * kernel_width % 16 != 0:
            print(f"Skipping 2:4 sparsity, Cin * Kh * Kw is not a multiple of 16")
            return torch.ones_like(scores)
    
        blocked_scores = rearrange(scores, 'o (b c) h w -> h w o b c', c=4)
        threshold = blocked_scores.topk(k=2, dim=-1).values[..., -1:]
        mask = (blocked_scores >= threshold).float()
        return rearrange(mask, 'h w o b c -> o (b c) h w')

    def print_sparsity(self) -> None:
        "Print sparsity report for all layers"
        total_params = 0
        total_zeros = 0
        
        print("\nSparsity Report:")
        print("-" * 80)
        print(f"{'Layer':<30} {'Type':<15} {'Params':<10} {'Zeros':<10} {'Sparsity':<10}")
        print("-" * 80)
        
        for name, m in self._iter_named_layers():
            zeros = torch.sum(m.weight == 0).item()
            total = m.weight.nelement()
            sparsity_pct = 100.0 * zeros / total if total > 0 else 0
            
            print(f"{name:<30} {m.__class__.__name__:<15} "
                  f"{total:<10,d} {zeros:<10,d} {sparsity_pct:>8.2f}%")
            
            total_params += total
            total_zeros += zeros
        
        print("-" * 80)
        overall_sparsity = 100.0 * total_zeros / total_params if total_params > 0 else 0
        print(f"{'Overall':<30} {'all':<15} {total_params:<10,d} "
              f"{total_zeros:<10,d} {overall_sparsity:>8.2f}%")
