# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/export/onnx_exporter.ipynb.

# %% ../../nbs/export/onnx_exporter.ipynb #imports
from __future__ import annotations

import warnings
from dataclasses import asdict, dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

import numpy as np
import torch
import torch.nn as nn

from ..core.precision import quant_spec

# %% auto #0
__all__ = ['export_onnx', 'ONNXModel', 'verify_onnx', 'export_qdq', 'QDQStats', 'qdq_stats', 'verify_qdq']

# %% ../../nbs/export/onnx_exporter.ipynb #dep-checks
@lru_cache(maxsize=None)
def _has_package(name: str) -> bool:
    "Check if a package is available (cached)"
    from importlib.util import find_spec
    return find_spec(name) is not None


def _require(*packages: str, install_hint: str | None = None) -> None:
    "Raise ImportError if any package is missing"
    missing = [p for p in packages if not _has_package(p)]
    if missing:
        hint = install_hint or f"pip install {' '.join(missing)}"
        raise ImportError(f"Missing packages: {missing}. Install with: {hint}")

# %% ../../nbs/export/onnx_exporter.ipynb #export-onnx
def export_onnx(
    model: nn.Module,
    sample: torch.Tensor,                 # Example input for tracing (with batch dim)
    output_path: str | Path,              # Output .onnx file path
    *,
    opset_version: int = 17,
    quantize: bool = False,               # Apply INT8 quantization after export
    quantize_mode: str = "dynamic",       # "dynamic" (no calibration) or "static"
    calibration_data: Iterable | None = None,  # DataLoader for static quantization
    optimize: bool = True,                # Run ONNX graph optimizer
    dynamic_batch: bool = True,           # Allow variable batch size at runtime
    input_names: list[str] | None = None,
    output_names: list[str] | None = None,
) -> Path:
    "Export a PyTorch model to ONNX format with optional quantization"
    _require("onnx", install_hint="pip install onnx onnxruntime")
    import onnx
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    input_names = input_names or ["input"]
    output_names = output_names or ["output"]
    
    # Quantization requires fixed batch size for shape inference
    dynamic_axes = None
    if dynamic_batch and not quantize:
        dynamic_axes = {
            input_names[0]: {0: "batch_size"},
            output_names[0]: {0: "batch_size"},
        }
    
    model.eval()
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=torch.jit.TracerWarning)
        warnings.filterwarnings("ignore", category=UserWarning)
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        torch.onnx.export(
            model, sample, str(output_path),
            opset_version=opset_version,
            input_names=input_names,
            output_names=output_names,
            dynamic_axes=dynamic_axes,
            do_constant_folding=True,
            dynamo=False,  # Use legacy TorchScript exporter for broader op support
        )
    
    if optimize and _has_package("onnxoptimizer"):
        import onnxoptimizer
        onnx_model = onnx.load(str(output_path))
        onnx_model = onnxoptimizer.optimize(onnx_model)
        onnx.save(onnx_model, str(output_path))
    
    if quantize:
        output_path = _quantize_onnx(output_path, quantize_mode, calibration_data, input_names[0])
    
    return output_path

# %% ../../nbs/export/onnx_exporter.ipynb #quantize-helper
def _quantize_onnx(
    onnx_path: Path,
    mode: str,
    calibration_data: Iterable | None,
    input_name: str,
) -> Path:
    "Apply INT8 quantization to an ONNX model"
    _require("onnxruntime", install_hint="pip install onnxruntime")
    
    from onnxruntime.quantization import QuantFormat, QuantType, quantize_dynamic, quantize_static, shape_inference
    
    preprocessed = onnx_path.with_stem(f"{onnx_path.stem}_preprocessed")
    shape_inference.quant_pre_process(str(onnx_path), str(preprocessed))
    
    quantized = onnx_path.with_stem(f"{onnx_path.stem}_int8")
    
    if mode == "dynamic":
        quantize_dynamic(str(preprocessed), str(quantized), weight_type=QuantType.QUInt8)
    elif mode == "static":
        if calibration_data is None:
            raise ValueError("Static quantization requires calibration_data")
        
        from onnxruntime.quantization import CalibrationDataReader
        
        class _DataReader(CalibrationDataReader):
            def __init__(self, data_iter, name):
                self.it, self.name = iter(data_iter), name
            def get_next(self):
                try:
                    batch = next(self.it)
                    if isinstance(batch, (tuple, list)): batch = batch[0]
                    return {self.name: batch.numpy()}
                except StopIteration:
                    return None
        
        quantize_static(
            str(preprocessed), str(quantized),
            calibration_data_reader=_DataReader(calibration_data, input_name),
            quant_format=QuantFormat.QDQ,
            activation_type=QuantType.QUInt8,
            weight_type=QuantType.QInt8,
        )
    else:
        raise ValueError(f"Unknown quantize_mode: {mode}. Use 'dynamic' or 'static'.")
    
    preprocessed.unlink(missing_ok=True)
    return quantized

# %% ../../nbs/export/onnx_exporter.ipynb #onnx-model
class ONNXModel:
    "Wrapper for ONNX Runtime inference with PyTorch-like interface"
    
    def __init__(self, path: str | Path, device: str = "cpu"):
        _require("onnxruntime", install_hint="pip install onnxruntime")
        import onnxruntime as ort
        
        self.path, self.device = Path(path), device
        providers = ["CUDAExecutionProvider", "CPUExecutionProvider"] if device == "cuda" else ["CPUExecutionProvider"]
        self.session = ort.InferenceSession(str(self.path), providers=providers)
        self.input_name = self.session.get_inputs()[0].name
        self.output_name = self.session.get_outputs()[0].name
    
    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        "Run inference on input tensor"
        x_np = x.cpu().numpy() if x.is_cuda else x.numpy()
        result = torch.from_numpy(self.session.run([self.output_name], {self.input_name: x_np})[0])
        return result.cuda() if self.device == "cuda" else result
    
    def warmup(self, sample: torch.Tensor, n: int = 10) -> None:
        "Run warmup iterations to stabilize inference timing"
        for _ in range(n): self(sample)
    
    def __repr__(self) -> str:
        return f"ONNXModel(path='{self.path}', device='{self.device}')"

# %% ../../nbs/export/onnx_exporter.ipynb #verify-onnx
def verify_onnx(
    model: nn.Module,
    onnx_path: str | Path,
    sample: torch.Tensor,
    rtol: float = 1e-3,
    atol: float = 1e-5,
) -> bool:
    "Verify ONNX model outputs match PyTorch model within tolerance"
    model.eval()
    with torch.no_grad():
        pt_out = model(sample).cpu().numpy()
    onnx_out = ONNXModel(onnx_path)(sample.cpu()).numpy()
    return np.allclose(pt_out, onnx_out, rtol=rtol, atol=atol)

# %% ../../nbs/export/onnx_exporter.ipynb #88b15f63
_INT8 = 3  # onnx.TensorProto.INT8

_WEIGHT_SOURCE_OPS = ("DequantizeLinear", "QuantizeLinear", "Cast")


def _set_eval(model: nn.Module) -> None:
    "Put `model` in eval mode, tolerating exported graph modules (they reject `.eval()`)"
    try: model.eval()
    except NotImplementedError: pass  # a torch.export'd module is already in inference mode


def _check_exportable(model: nn.Module) -> None:
    "Refuse a precision this export cannot write, reading the spec `Quantizer` left on the model"
    spec = quant_spec(model)
    if spec is None or spec.exports: return  # untagged models are exported as they always were
    raise ValueError(
        f"export_qdq cannot write this model: it was quantized {spec.label} with "
        f"backend='{spec.backend}'. {spec.note} Quantize with Quantizer(backend='pt2e') for a graph "
        "this export can write.")


def _pt2e_translation_table() -> dict:
    "ONNX translations for the `quantized_decomposed` q/dq operators produced by the pt2e flow"
    _require("onnxscript", install_hint="pip install onnxscript")
    from onnxscript import opset18 as op

    # Plain functions: an `@onnxscript.script` wrapper would return a tuple the consuming operator rejects.
    def quantize_per_tensor(x, scale, zero_point, quant_min: int, quant_max: int, dtype: int):
        # the Cast: pt2e stores zero-points as int64, ONNX wants them in the quantized dtype
        return op.QuantizeLinear(x, scale, op.Cast(zero_point, to=_INT8))

    def dequantize_per_tensor(x, scale, zero_point, quant_min: int, quant_max: int, dtype: int):
        return op.DequantizeLinear(x, scale, op.Cast(zero_point, to=_INT8))

    def quantize_per_channel(x, scales, zero_points, axis: int, quant_min: int, quant_max: int, dtype: int):
        return op.QuantizeLinear(x, scales, op.Cast(zero_points, to=_INT8), axis=axis)

    def dequantize_per_channel(x, scales, zero_points, axis: int, quant_min: int, quant_max: int, dtype: int):
        return op.DequantizeLinear(x, scales, op.Cast(zero_points, to=_INT8), axis=axis)

    ops = torch.ops.quantized_decomposed
    table = {
        ops.quantize_per_tensor.default: quantize_per_tensor,
        ops.dequantize_per_tensor.default: dequantize_per_tensor,
        ops.quantize_per_channel.default: quantize_per_channel,
        ops.dequantize_per_channel.default: dequantize_per_channel,
    }
    # The `.tensor` overloads take the scale/zero-point as tensors rather than as python scalars
    for name, translation in (("quantize_per_tensor", quantize_per_tensor),
                              ("dequantize_per_tensor", dequantize_per_tensor)):
        overload = getattr(getattr(ops, name), "tensor", None)
        if overload is not None: table[overload] = translation
    return table


def _graph_constants(graph) -> dict:
    "Every tensor an ONNX graph carries as a constant, by name, as the TensorProto that holds it"
    constants = {init.name: init for init in graph.initializer}
    for node in graph.node:  # a producer may emit a constant as a Constant node rather than an initializer
        if node.op_type == "Constant":
            for attr in node.attribute:
                if attr.name == "value": constants[node.output[0]] = attr.t
    return constants


def _producers(graph) -> dict:
    "The node that writes each value of an ONNX graph, by value name"
    return {output: node for node in graph.node for output in node.output}


# ONNX counterpart of the quantizer's `_CONV_EPILOGUE_TARGETS`; shorter because pt2e folds the bn in.
_CONV_EPILOGUE_OPS = ("Relu",)


def _direct_conv_add_edges(graph) -> int:
    "How many `Add` inputs this graph takes from a `Conv`, with no Q/DQ pair on the way"
    producers = _producers(graph)
    consumers: dict[str, int] = {}
    for node in graph.node:
        for name in node.input: consumers[name] = consumers.get(name, 0) + 1

    def source(name: str):
        "The node whose result reaches `name`, walked back through the convolution's own epilogue"
        # same single-consumer rule as the annotation-time matcher
        node = producers.get(name)
        while (node is not None and node.op_type in _CONV_EPILOGUE_OPS and node.input
               and consumers.get(node.output[0], 0) == 1):
            node = producers.get(node.input[0])
        return node

    return sum(1 for node in graph.node if node.op_type == "Add" for name in node.input
               if getattr(source(name), "op_type", None) == "Conv")


def _weight_dims(name: str,
                 dims_by_name: dict[str, tuple[int, ...]],
                 producers: dict) -> tuple[int, ...] | None:
    "Shape of the weight tensor reaching `name`, walked back through the nodes that de-quantize it"
    seen = set()
    while name not in dims_by_name:
        if name in seen: return None  # a cycle: give up rather than spin
        seen.add(name)
        node = producers.get(name)
        if node is None or node.op_type not in _WEIGHT_SOURCE_OPS or not node.input: return None
        name = node.input[0]
    return dims_by_name[name]


def _set_conv_kernel_shape(graph) -> int:
    "Write the optional `kernel_shape` attribute on the Conv nodes that lack it, and count them"
    from onnx import helper

    # shapes come off the TensorProto: correct even when the weights live in an external file
    dims_by_name = {name: tuple(t.dims) for name, t in _graph_constants(graph).items()}
    producers = _producers(graph)
    written = 0
    for node in graph.node:
        if node.op_type != "Conv": continue
        if any(attr.name == "kernel_shape" for attr in node.attribute): continue
        if len(node.input) < 2: continue
        weight = _weight_dims(node.input[1], dims_by_name, producers)
        if weight is None or len(weight) < 3: continue  # unknown weight shape: leave the node alone
        node.attribute.append(helper.make_attribute("kernel_shape", list(weight[2:])))
        written += 1
    return written


def _discard(output_path: Path, proto) -> None:
    "Delete a produced graph and the external-data file it references, so a refusal keeps nothing"
    for location in {entry.value for init in proto.graph.initializer
                     for entry in init.external_data if entry.key == "location"}:
        sidecar = (output_path.parent / location).resolve()
        # never follow a `location` out of the directory we wrote to
        if sidecar.is_relative_to(output_path.parent.resolve()): sidecar.unlink(missing_ok=True)
    output_path.unlink(missing_ok=True)


def _refusal(output_path: Path, proto, message: str, error: type[Exception] = ValueError) -> Exception:
    "Discard the produced graph and return the refusal that says so, for the caller to raise"
    _discard(output_path, proto)
    return error(f"{message} No file was kept.")


def _accept_produced(produced: int) -> str:
    "The sentence pointing a refusal at the opset the exporter produced"
    return f"Pass opset_version={produced} to accept the graph as it was produced."


def _declared_opset(proto) -> int | None:
    "The opset a graph declares for the default ONNX domain, or None when it declares none"
    return next((o.version for o in proto.opset_import if o.domain in ("", "ai.onnx")), None)


def _check_produced_opset(proto, requested: int, output_path: Path) -> None:
    "Refuse a produced graph that does not declare the opset that was asked for, keeping none of it"
    produced = _declared_opset(proto)
    if produced == requested: return
    if produced is None:
        raise _refusal(
            output_path, proto,
            f"export_qdq produced a graph that declares no opset for the default ONNX domain, so "
            f"there is nothing to check the requested opset {requested} against.")
    raise _refusal(
        output_path, proto,
        f"export_qdq was asked for opset {requested}, and the graph it produced declares opset "
        f"{produced}: the ONNX version converter could not rewrite this graph to opset {requested}, "
        f"and torch.onnx kept the opset the exporter emitted. Pass opset_version={produced} to accept "
        f"that graph, or export a model whose operators the converter can convert.")


def _check_produced_placement(proto, model: nn.Module, output_path: Path) -> None:
    "Refuse a produced graph that contradicts the Q/DQ placement the model's spec records"
    # `getattr`: no spec at all, or a spec pickled before this field existed (its slot unpickles UNSET).
    if getattr(quant_spec(model), 'qdq_placement', None) != 'skip_conv_add': return
    if _direct_conv_add_edges(proto.graph): return
    raise _refusal(
        output_path, proto,
        "export_qdq produced a graph that contradicts the model it exported: that model records "
        "qdq_placement='skip_conv_add', which leaves the residual branch's convolution reaching its "
        "addition unquantized, and in the produced file every `Add` reads its inputs through a Q/DQ "
        "pair — not one of them reads a `Conv`, directly or through that convolution's own "
        "activation.")


def _drop_unused_constant(graph, name: str) -> bool:
    "Remove a graph constant nothing reads any more, and say whether it was removed"
    # This graph's own nodes only: nothing a pt2e QDQ export writes reads a constant from a subgraph.
    if any(name in node.input for node in graph.node): return False
    if any(value.name == name for value in (*graph.input, *graph.output)): return False
    for index, initializer in enumerate(graph.initializer):
        if initializer.name == name:
            del graph.initializer[index]
            return True
    for index, node in enumerate(graph.node):
        if node.op_type == "Constant" and node.output and node.output[0] == name:
            del graph.node[index]
            return True
    return False


def _lower_reducemean_axes(graph) -> int:
    "Move each `ReduceMean`'s constant `axes` INPUT into the `axes` ATTRIBUTE, and count the nodes moved"
    from onnx import helper, numpy_helper

    constants = _graph_constants(graph)
    sources = []
    for node in graph.node:
        if node.op_type != "ReduceMean" or len(node.input) < 2: continue  # already in attribute form
        source, name = node.input[1], node.name or node.op_type
        if source not in constants:
            raise ValueError(
                f"export_qdq cannot lower node '{name}' to the requested opset: its `axes` input "
                f"'{source}' is computed while the graph runs rather than being a graph constant, and an "
                f"older opset can only carry axes that are known when the graph is written.")
        axes = [int(axis) for axis in numpy_helper.to_array(constants[source]).reshape(-1)]
        noop = next((a for a in node.attribute if a.name == "noop_with_empty_axes"), None)
        if not axes and noop is not None and noop.i:
            raise ValueError(
                f"export_qdq cannot lower node '{name}' to the requested opset: it reduces nothing (an "
                f"empty `axes` input with `noop_with_empty_axes=1`), which an older opset cannot say — it "
                f"reads an absent `axes` as 'reduce every axis' instead.")
        if noop is not None: node.attribute.remove(noop)
        if axes: node.attribute.append(helper.make_attribute("axes", axes))
        del node.input[1:]
        sources.append(source)
    # after the walk: deleting a Constant node while iterating would skip the one behind it
    for source in dict.fromkeys(sources): _drop_unused_constant(graph, source)
    return len(sources)


def _lower_produced_opset(proto, requested: int, output_path: Path) -> int | None:
    "Rewrite a graph produced at a newer opset into the requested one; None when there was nothing to do"
    produced = _declared_opset(proto)
    if produced is None or produced <= requested: return None
    try:
        lowered = _lower_reducemean_axes(proto.graph)
    except ValueError as error:
        raise _refusal(output_path, proto, f"{error} {_accept_produced(produced)}") from None
    for entry in proto.opset_import:
        if entry.domain in ("", "ai.onnx"): entry.version = requested
    return lowered


def _ort_outputs(path: Path, sample: torch.Tensor) -> list[np.ndarray]:
    "Every output ONNX Runtime produces for `sample`, running the graph on the CPU"
    # not `ONNXModel`: that wrapper reads the FIRST output only
    import onnxruntime as ort

    session = ort.InferenceSession(str(path), providers=["CPUExecutionProvider"])
    feed = {session.get_inputs()[0].name: sample.detach().cpu().numpy()}
    return [np.asarray(output) for output in session.run(None, feed)]


def _output_difference(before: list[np.ndarray],
                       after: list[np.ndarray],
) -> str | None:
    "How two lists of ONNX Runtime outputs differ, or None when they are identical byte for byte"
    def signature(outputs): return [(tuple(o.shape), o.dtype.str) for o in outputs]

    before_signature, after_signature = signature(before), signature(after)
    if before_signature != after_signature: return f"{before_signature} became {after_signature}"
    if all(a.tobytes() == b.tobytes() for a, b in zip(before, after)): return None
    # reached only when some byte differs, so at least one of these arrays has an element to subtract
    deltas = (float(np.abs(a.astype(np.float64) - b.astype(np.float64)).max())
              for a, b in zip(before, after) if a.size)
    return f"max |Δ| = {max(deltas):.3e}"


def _write_lowered(proto, output_path: Path, sample: torch.Tensor, produced: int) -> None:
    "Put a lowered graph in place of the produced one — but only once it has been checked and run"
    import onnx

    requested = _declared_opset(proto)  # what the rewrite relabelled the graph to
    if not _has_package("onnxruntime"):
        raise _refusal(
            output_path, proto,
            f"export_qdq checks a lowered graph by running it, which needs onnxruntime: install it (pip "
            f"install onnxruntime), or pass opset_version={produced} to accept the graph as it was "
            f"produced.",
            error=ImportError)

    # run the produced graph first and alone: a failure here is the exporter's, not the rewrite's
    try:
        produced_out = _ort_outputs(output_path, sample)
    except Exception as error:
        raise _refusal(
            output_path, proto,
            f"export_qdq could not run the graph it PRODUCED — {type(error).__name__}: {error} — so there "
            f"is nothing to check a rewrite to opset {requested} against. Pass "
            f"opset_version={produced} to get that graph as it was produced, unchecked.") from error

    # beside the produced file, so a relative external-data reference still resolves from there
    lowered_path = output_path.with_name(output_path.name + ".lowered")
    try:
        onnx.save(proto, str(lowered_path))
        onnx.checker.check_model(str(lowered_path))
        lowered_out = _ort_outputs(lowered_path, sample)
    except Exception as error:
        lowered_path.unlink(missing_ok=True)
        raise _refusal(
            output_path, proto,
            f"export_qdq rewrote the graph it produced to opset {requested}, and the result "
            f"is not a graph ONNX accepts and runs at that opset — {type(error).__name__}: {error}. Only "
            f"`ReduceMean`'s axes input is lowered here; every other operator has to be one the requested "
            f"opset already knows. {_accept_produced(produced)}") from error

    difference = _output_difference(produced_out, lowered_out)
    if difference is not None:
        lowered_path.unlink(missing_ok=True)
        raise _refusal(
            output_path, proto,
            f"export_qdq rewrote the graph it produced to opset {requested}, and the "
            f"rewritten graph does not compute what the produced one computes ({difference}). The rewrite "
            f"changes how the axes are spelled and nothing else. {_accept_produced(produced)}") from None
    lowered_path.replace(output_path)

# %% ../../nbs/export/onnx_exporter.ipynb #467ceb9a
def export_qdq(
    model: nn.Module,                      # Quantized model, typically from `Quantizer(backend='pt2e')`
    sample: torch.Tensor,                  # Example input (with batch dim); use the calibration batch size
    output_path: str | Path,               # Output .onnx file path
    *,
    opset_version: int = 18,               # ONNX opset the file must declare; a lower one is rewritten and verified
    dynamic_batch: bool = False,           # Ask for a dynamic batch dimension (experimental)
    input_names: list[str] | None = None,
    output_names: list[str] | None = None,
) -> Path:
    "Export a quantized model to ONNX, keeping its Q/DQ node pairs intact"
    _check_exportable(model)
    _require("onnx", "onnxscript", install_hint="pip install onnx onnxscript")
    import onnx

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    input_names = input_names or ["input"]
    output_names = output_names or ["output"]

    dynamic_shapes = None
    if dynamic_batch:
        warnings.warn("dynamic_batch=True is experimental — some consumers mis-handle the "
                      "post-pooling reshape with a dynamic batch.", UserWarning, stacklevel=2)
        dynamic_shapes = ({0: torch.export.Dim("batch")},)

    _set_eval(model)
    program = torch.onnx.export(
        model, (sample,),
        dynamo=True,  # the dynamo exporter is what accepts a custom translation table
        opset_version=opset_version,
        input_names=input_names,
        output_names=output_names,
        dynamic_shapes=dynamic_shapes,
        custom_translation_table=_pt2e_translation_table(),
    )
    program.save(str(output_path))

    # everything below reads the FILE that was produced, not the request
    proto = onnx.load(str(output_path), load_external_data=False)
    produced = _declared_opset(proto)  # read BEFORE the rewrite, which is what makes it declare another
    lowered = _lower_produced_opset(proto, opset_version, output_path)
    _check_produced_opset(proto, opset_version, output_path)
    _check_produced_placement(proto, model, output_path)

    if dynamic_batch and not proto.graph.input[0].type.tensor_type.shape.dim[0].dim_param:
        warnings.warn("The exported graph kept a STATIC batch dimension: a module captured by "
                      "torch.export is specialised to the batch size it was captured with. "
                      "Re-capture the source model with a dynamic batch before quantizing.",
                      UserWarning, stacklevel=2)

    patched = _set_conv_kernel_shape(proto.graph)
    # `lowered` is 0 when nothing moved; only `None` means the rewrite never ran
    if lowered is not None: _write_lowered(proto, output_path, sample, produced)
    elif patched: onnx.save(proto, str(output_path))
    return output_path

# %% ../../nbs/export/onnx_exporter.ipynb #f7838382
@dataclass(slots=True)
class QDQStats:
    "Quantization nodes found in an ONNX graph, and the operator edges that carry no pair"
    n_quantize: int              # number of QuantizeLinear nodes
    n_dequantize: int            # number of DequantizeLinear nodes
    n_per_channel: int           # nodes whose scale holds one value per channel
    n_nonzero_zero_point: int    # nodes whose zero-point is not all zeros
    n_unquantized_conv_add: int  # `Add` inputs read straight from a `Conv`

    def as_dict(self) -> dict[str, int]: return asdict(self)


def qdq_stats(
    onnx_path: str | Path,
) -> QDQStats:
    "Count the Q/DQ nodes of an ONNX graph and check their zero-points"
    _require("onnx", install_hint="pip install onnx")
    import onnx
    from onnx import numpy_helper

    graph = onnx.load(str(onnx_path)).graph
    constants = _graph_constants(graph)  # scales and zero-points may be initializers OR Constant nodes

    def _constant(name, node, role):
        "Value of a graph constant, or a clear error rather than a silently wrong count"
        if name not in constants:
            raise ValueError(f"Cannot read the {role} of node '{node.name or node.op_type}': "
                             f"'{name}' is not a graph constant.")
        return numpy_helper.to_array(constants[name])  # only the few tensors actually looked at

    n_quantize = n_dequantize = n_per_channel = n_nonzero_zero_point = 0
    for node in graph.node:
        if node.op_type == "QuantizeLinear": n_quantize += 1
        elif node.op_type == "DequantizeLinear": n_dequantize += 1
        else: continue
        # axis cannot be used: exporters write it on per-tensor nodes too
        if _constant(node.input[1], node, "scale").size > 1: n_per_channel += 1
        # zero_point is an optional third input: when omitted it is implicitly zero
        zero_point = node.input[2] if len(node.input) > 2 else ""
        if zero_point and np.any(_constant(zero_point, node, "zero_point") != 0): n_nonzero_zero_point += 1
    return QDQStats(n_quantize, n_dequantize, n_per_channel, n_nonzero_zero_point,
                    _direct_conv_add_edges(graph))

# %% ../../nbs/export/onnx_exporter.ipynb #1eaa6ad7
def verify_qdq(
    model: nn.Module,       # Reference PyTorch model (the quantized module that was exported)
    onnx_path: str | Path,
    sample: torch.Tensor,   # Test inputs, batch dimension first
    n_batches: int = 1,     # Split `sample` into this many EQUAL batches
) -> float:
    "Fraction of inputs on which the ONNX graph and the PyTorch model predict the same class"
    _require("onnxruntime", install_hint="pip install onnxruntime")
    if sample.shape[0] == 0: raise ValueError("`sample` is empty: there is nothing to compare.")
    # a static graph rejects a shorter last batch
    if sample.shape[0] % n_batches:
        raise ValueError(f"`sample` holds {sample.shape[0]} inputs, which does not split into "
                         f"{n_batches} equal batches.")
    _set_eval(model)
    onnx_model = ONNXModel(onnx_path)

    agreed = total = 0
    reference = []
    for chunk in torch.split(sample.cpu(), sample.shape[0] // n_batches, dim=0):
        with torch.no_grad(): torch_pred = model(chunk).argmax(-1).cpu().numpy()
        onnx_pred = onnx_model(chunk).numpy().argmax(-1)
        agreed += int((torch_pred == onnx_pred).sum())
        total += torch_pred.size
        reference.append(torch_pred.reshape(-1))

    if len(set(np.concatenate(reference).tolist())) <= 1:
        warnings.warn(
            "The reference model predicts a single class for every input, so this agreement is 1.0 "
            "whatever the ONNX graph computes: the check is vacuous here. Use a trained model and "
            "inputs whose predictions vary, or compare logits directly.", UserWarning, stacklevel=2)
    return agreed / total
