project:
  type: website

format:
  html:
    theme:
      dark: 
        - cosmo
        - custom_dark.scss 
      light: 
        - cosmo
        - custom.scss
    css: styles.css
    toc: true

website:
  google-analytics: "G-424WWZFZ5F"
  twitter-card:
    creator: "@nathanhubens"
    site: "@fasterai" 
  open-graph: true
  repo-actions: [issue]
  page-footer: "&copy; By Nathan Hubens"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Contact Me"
        icon: chat-right-text
        href: "mailto:nathan.hubens@gmail.com?subject=Hello"
      - text: "Report an Issue"
        icon: bug
        href: https://github.com/nathanhubens/fasterai/issues
      - text: "Join the Community"
        icon: discord
        href: https://discord.gg/32BwhJSB9u
    right:
      - icon: github
        href: "https://github.com/nathanhubens/fasterai"
      - icon: twitter
        href: https://twitter.com/fasterai
        aria-label: FasterAI Twitter

  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - overview.ipynb
      - quickstart.ipynb
      - section: Tutorials
        contents:
        - tutorials/walkthrough.ipynb
        - section: Sparse
          contents:
          - tutorials/sparse/schedules.ipynb
          - tutorials/sparse/sparsifier.ipynb
          - tutorials/sparse/sparsify_callback.ipynb
          - tutorials/sparse/lottery_ticket.ipynb
          - tutorials/sparse/transformers.ipynb
        - section: Prune
          contents: 
          - tutorials/prune/prune_callback.ipynb
          - tutorials/prune/YOLOV8.ipynb
        - section: Distill
          contents:
          - tutorials/distill/distill_callback.ipynb
        - section: Regularize
          contents:
          - tutorials/regularize/regularize_callback.ipynb
        - section: Misc
          contents:
          - tutorials/misc/bn_folding.ipynb
          - tutorials/misc/fc_decomposer.ipynb
      - section: Core
        contents:
        - core/granularity.ipynb
        - core/criteria.ipynb
        - core/schedules.ipynb
      - section: Sparse
        contents:
        - sparse/sparsifier.ipynb
        - sparse/sparsify_callback.ipynb
      - section: Prune
        contents: 
        - prune/pruner.ipynb
        - prune/prune_callback.ipynb
      - section: Distill
        contents:
        - distill/distillation_callback.ipynb
      - section: Quantize
        contents:
        - quantize/quantizer.ipynb
        - quantize/quantize_callback.ipynb
      - section: Regularize
        contents:
        - regularize/regularize_callback.ipynb
      - section: Misc
        contents:
        - misc/bn_folding.ipynb
        - misc/fc_decomposer.ipynb

metadata-files: [nbdev.yml]
