project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card:
    creator: "@nathanhubens"
    site: "@fasterai" 
  open-graph: true
  repo-actions: [issue]
  page-footer: "&copy; By Nathan Hubens"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Get Started"
        href: https://nathanhubens.github.io/07e_tutorial.using_fasterai.ipynb
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/fastai/nbdev/issues
          - text: "Contact Me"
            icon: chat-right-text
            href: "mailto:nathan.hubens@gmail.com?subject=Hello"
    right:
      - icon: github
        href: "https://github.com/nathanhubens/fasterai"
      - icon: twitter
        href: https://twitter.com/fasterai
        aria-label: FasterAI Twitter

  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - overview.ipynb
      - quickstart.ipynb
      - section: Tutorials
        contents:
        - section: Sparse
          contents:
          - 07a_tutorial.schedules.ipynb
          - 07b_tutorial.sparsifier.ipynb
          - 07c_tutorial.sparsify_callback.ipynb
          - 07d_tutorial.pruner.ipynb
          - 07e_tutorial.lottery_ticket.ipynb
          - 07f_tutorial.transformers.ipynb
        - section: Distill
          contents:
          - 08a_tutorial.knowledge_distillation.ipynb
        - section: Regularize
          contents:
          - 09a_tutorial.regularizer.ipynb
        - section: Misc
          contents:
          - 010a_tutorial.bn_folding.ipynb
          - 010b_tutorial.fc_decomposer.ipynb
      - section: Core
        contents:
        - 00a_core.granularity.ipynb
        - 00b_core.criteria.ipynb
        - 00c_core.schedules.ipynb
      - section: Sparse
        contents:
        - 01_sparse.sparsifier.ipynb
        - 02_sparse.sparsify_callback.ipynb
        - 03_sparse.pruner.ipynb
      - section: Distill
        contents:
        - 04_distill.knowledge_distillation.ipynb
      - section: Regularize
        contents:
        - 05_regularize.regularizer.ipynb
      - section: Misc
        contents:
        - 06a_misc.bn_folding.ipynb
        - 06b_misc.fc_decomposer.ipynb

metadata-files: [nbdev.yml, sidebar.yml]