# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/quantize/adaround.ipynb.

# %% ../../nbs/quantize/adaround.ipynb #1746d882
from __future__ import annotations
import copy
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils.fusion import fuse_conv_bn_eval

# %% auto #0
__all__ = ['fold_bn', 'weight_scale', 'rtn_quant', 'adaround_layer', 'adaround_quantize', 'adaround_to_onnx']

# %% ../../nbs/quantize/adaround.ipynb #80a30f53
def _set_child(parent, name, new):
    "Replace child module `name` of `parent` (handles Sequential integer indices)."
    if name.isdigit(): parent[int(name)] = new
    else: setattr(parent, name, new)

def fold_bn(model: nn.Module   # model containing Conv2d→BatchNorm2d pairs
    ) -> nn.Module:            # same model with each Conv-BN pair fused in-place
    "Fuse each `Conv2d`→`BatchNorm2d` pair into the conv (eval mode) and replace the BN with Identity."
    for mod in model.modules():
        kids = list(mod.named_children())
        for i in range(len(kids) - 1):
            (n1, c1), (n2, c2) = kids[i], kids[i + 1]
            if isinstance(c1, nn.Conv2d) and isinstance(c2, nn.BatchNorm2d):
                _set_child(mod, n1, fuse_conv_bn_eval(c1, c2))
                _set_child(mod, n2, nn.Identity())
    return model

# %% ../../nbs/quantize/adaround.ipynb #c9f0e214
def weight_scale(W: torch.Tensor,             # weight tensor [out_channels, ...]
                 w_bits: int = 4,             # bit-width (signed)
                 granularity: str = 'channel',  # 'channel' (per-output-channel) or 'tensor'
    ):                                        # (scale, qmin, qmax) — dequant scale and signed clip range
    "Signed weight quantization `scale` and clip range `[qmin, qmax]` on the ONNX/ORT grid."
    qmax =   2 ** (w_bits - 1) - 1                     # INT4 ->  7,  INT8 ->  127
    qmin = -(2 ** (w_bits - 1))                        # INT4 -> -8,  INT8 -> -128 (asymmetric signed grid)
    denom =  2 ** (w_bits - 1) - 0.5                   # INT4 -> 7.5  (matches onnxruntime per-channel int4)
    if granularity == 'channel':
        r = W.detach().abs().reshape(W.shape[0], -1).amax(1).clamp_min(1e-12)
        scale = (r / denom).reshape([-1] + [1] * (W.dim() - 1))
    else:
        scale = W.detach().abs().amax().clamp_min(1e-12) / denom
    return scale, qmin, qmax

def rtn_quant(W: torch.Tensor,                # weight tensor to fake-quantize
              w_bits: int = 4,                # bit-width
              granularity: str = 'channel',   # 'channel' or 'tensor'
    ) -> torch.Tensor:                        # dequantized (fake-quant) weights, same shape
    "Round-to-nearest (RTN) signed fake-quant — the AdaRound baseline (== AdaRound at init)."
    scale, qmin, qmax = weight_scale(W, w_bits, granularity)
    floorWs = torch.floor(W / scale)
    q = floorWs + ((W / scale - floorWs) >= 0.5).float()  # round half up (matches the AdaRound hard round)
    return torch.clamp(q, qmin, qmax) * scale

# %% ../../nbs/quantize/adaround.ipynb #d948dfff
# AdaRound rectified-sigmoid soft rounding (Nagel et al., 2020):
#   h(V) = clamp(sigmoid(V)*(zeta-gamma)+gamma, 0, 1)
#   W_q(V) = s * clamp(floor(W/s) + h(V), qmin, qmax)
_ZETA, _GAMMA = 1.1, -0.1

def _rect_sigmoid(V: torch.Tensor) -> torch.Tensor:
    "Rectified sigmoid squashing `V` into a soft rounding decision in [0, 1]."
    return torch.clamp(torch.sigmoid(V) * (_ZETA - _GAMMA) + _GAMMA, 0, 1)

def _init_V(frac: torch.Tensor) -> torch.Tensor:
    "Initialise `V` so that `h(V) == frac(W/s)` — makes AdaRound identical to RTN at init."
    s0 = ((frac - _GAMMA) / (_ZETA - _GAMMA)).clamp(1e-6, 1 - 1e-6)
    return torch.log(s0 / (1 - s0))

def _hard_quant_from_V(V, floorWs, scale, qmin, qmax):
    "Deployed weights: hard-round the learned soft rounding `h(V)` onto the signed grid."
    h_hard = (_rect_sigmoid(V) >= 0.5).float()
    return scale * torch.clamp(floorWs + h_hard, qmin, qmax)

def _layer_fwd(mod, x, w, b):
    "Forward one Conv2d/Linear layer with an explicit weight/bias (for reconstruction)."
    if isinstance(mod, nn.Conv2d):
        return F.conv2d(x, w, b, mod.stride, mod.padding, mod.dilation, mod.groups)
    return F.linear(x, w, b)

# %% ../../nbs/quantize/adaround.ipynb #ab024063
def adaround_layer(layer: nn.Module,             # Conv2d/Linear whose rounding is optimized
                   x_cal: torch.Tensor,          # cached FP inputs to this layer [N, ...]
                   w_bits: int = 4,              # weight bit-width
                   *,
                   granularity: str = 'channel',  # 'channel' or 'tensor'
                   iters: int = 2000,            # optimization iterations
                   lr: float = 1e-2,             # Adam learning rate
                   lam: float = 0.01,            # rounding-regularizer weight
                   beta_start: float = 20.0,     # anneal start (encourages soft)
                   beta_end: float = 2.0,        # anneal end (encourages binary)
                   warmup: float = 0.2,          # fraction of iters before regularizer turns on
                   batch_size: int = 32,         # minibatch of cached inputs per step
                   device: str | torch.device | None = None,  # compute device (default: layer's)
    ):                                           # (Wq_hard, info) — deployed fake-quant weights + diagnostics
    "Learn per-weight soft rounding for one layer, minimising output reconstruction ‖W_q(V)x − Wx‖² + regularizer."
    device = torch.device(device) if device is not None else layer.weight.device
    W = layer.weight.detach().float().to(device)
    scale, qmin, qmax = weight_scale(W, w_bits, granularity)
    floorWs = torch.floor(W / scale)
    frac = (W / scale) - floorWs                          # in [0, 1)
    V = _init_V(frac).clone().requires_grad_(True)        # init so h(V) == frac  (== RTN)
    opt = torch.optim.Adam([V], lr=lr)
    bias = layer.bias.detach().float().to(device) if layer.bias is not None else None
    N = x_cal.shape[0]
    warm_iters = int(warmup * iters)
    for it in range(iters):
        idx = torch.randint(0, N, (min(batch_size, N),))
        xb = x_cal[idx].to(device, dtype=torch.float32)
        h = _rect_sigmoid(V)
        Wq = scale * torch.clamp(floorWs + h, qmin, qmax)
        out_q = _layer_fwd(layer, xb, Wq, bias)
        with torch.no_grad():
            out_fp = _layer_fwd(layer, xb, W, bias)
        rec = (out_q - out_fp).pow(2).flatten(1).sum(1).mean()  # per-sample SSE, averaged
        if it < warm_iters:
            beta, lam_t = beta_start, 0.0                       # warmup: reconstruction only
        else:
            rel = (it - warm_iters) / max(1, iters - warm_iters)
            beta = beta_end + (beta_start - beta_end) * max(0.0, 1 - rel)
            lam_t = lam
        round_loss = lam_t * (1 - (2 * h - 1).abs().pow(beta)).sum()  # push h -> {0, 1}
        loss = rec + round_loss
        opt.zero_grad(); loss.backward(); opt.step()
    with torch.no_grad():
        h = _rect_sigmoid(V)
        not_binary = ((h > 0.02) & (h < 0.98)).float().mean().item()  # unresolved fraction
        Wq_hard = _hard_quant_from_V(V, floorWs, scale, qmin, qmax)
    return Wq_hard, {'not_binary_frac': not_binary, 'w_bits': w_bits, 'granularity': granularity}

# %% ../../nbs/quantize/adaround.ipynb #10fa2568
def _iter_target_layers(model: nn.Module,                     # model to scan
                        layer_type = (nn.Conv2d, nn.Linear),  # module type(s) to target
    ):
    "Iterate over modules of `layer_type` (the AdaRound analogue of `Sparsifier._iter_layers`)."
    for m in model.modules():
        if isinstance(m, layer_type):
            yield m

def _normalize_calibration(calibration_dl,               # DataLoaders | DataLoader | list of batches
                           n_batches: int | None = None,  # cap on number of batches
    ) -> list:                                           # list of input tensors (xb)
    "Normalise the three accepted calibration inputs to a list of input tensors."
    dl = calibration_dl
    if hasattr(dl, 'valid') and hasattr(dl, 'train'):    # fastai DataLoaders -> use validation dl
        dl = dl.valid
    batches = []
    for b in dl:
        xb = b[0] if isinstance(b, (list, tuple)) else b  # (xb, yb) batch or a bare input tensor
        batches.append(xb)
        if n_batches is not None and len(batches) >= n_batches:
            break
    return batches

@torch.no_grad()
def _capture_inputs(model,                          # (pristine) FP model
                    layers,                         # target layers to hook
                    batches,                        # list of input tensors
                    device,                         # compute device
                    store_dtype = torch.float16,    # cache dtype (saves memory)
    ) -> dict:                                      # {layer: cached inputs [N, ...] on CPU}
    "Cache the FP input tensor to every target layer in a single forward pass."
    cache = {l: [] for l in layers}
    def make_hook(layer):
        def hook(mod, inp):
            cache[layer].append(inp[0].detach().to(store_dtype).cpu())
        return hook
    handles = [l.register_forward_pre_hook(make_hook(l)) for l in layers]
    model.eval()
    for xb in batches:
        model(xb.to(device))
    for h in handles: h.remove()
    return {l: torch.cat(v) for l, v in cache.items()}

# %% ../../nbs/quantize/adaround.ipynb #aeba40b3
def _fake_quant_act(x, scale, qmax):
    "Per-tensor symmetric fake-quant of an activation tensor."
    return torch.clamp(torch.round(x / scale), -qmax, qmax) * scale

@torch.no_grad()
def _calibrate_activations(model,           # weight-quantized model
                           layers,          # target layers
                           batches,         # calibration input tensors
                           act_bits: int,   # activation bit-width
                           device,          # compute device
                           n_batches: int = 8,  # batches used for statistics
    ):
    "Calibrate MSE-optimal per-tensor activation scales and install persistent fake-quant pre-hooks."
    qmax = 2 ** (act_bits - 1) - 1
    samples = {l: [] for l in layers}
    def obs(mod, inp):
        v = inp[0].detach().flatten()
        if v.numel() > 20000:
            v = v[torch.randint(0, v.numel(), (20000,), device=v.device)]
        samples[mod].append(v.float().cpu())
    handles = [l.register_forward_pre_hook(obs) for l in layers]
    model.eval()
    for i, xb in enumerate(batches):
        if i >= n_batches: break
        model(xb.to(device))
    for h in handles: h.remove()
    alphas = [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.4, 0.3]
    def make_hook(scale, qmax):
        def hook(mod, inp):
            return (_fake_quant_act(inp[0], scale, qmax),) + tuple(inp[1:])
        return hook
    for l in layers:
        a = torch.cat(samples[l]); mx = a.abs().max().item()
        best_mse, best_clip = float('inf'), mx
        for al in alphas:                                 # search clip minimising quant MSE
            clip = al * mx
            if clip <= 0: continue
            scale = clip / qmax
            q = torch.clamp(torch.round(a / scale), -qmax, qmax) * scale
            mse = ((q - a) ** 2).mean().item()
            if mse < best_mse: best_mse, best_clip = mse, clip
        l.register_forward_pre_hook(make_hook(max(best_clip, 1e-12) / qmax, qmax))

# %% ../../nbs/quantize/adaround.ipynb #094c67f0
def adaround_quantize(
    model: nn.Module,                              # model whose weights -> INT-`w_bits` with learned rounding
    calibration_dl,                                # fastai DataLoaders | torch DataLoader | list of (xb, yb)/xb batches -- REQUIRED
    w_bits: int = 4,                               # weight bit-width
    granularity: str = 'channel',                  # 'channel' (per-output-channel) or 'tensor'
    act_bits: int | None = None,                   # activation bit-width (None -> weight-only)
    iters: int = 2000,                             # AdaRound optimization iters per layer
    lr: float = 1e-2,                              # Adam learning rate
    fold_batchnorm: bool = True,                   # fuse Conv->BN before quantizing
    layer_type = (nn.Conv2d, nn.Linear),           # module type(s) to quantize
    *,
    lam: float = 0.01,                             # AdaRound rounding-regularizer weight
    batch_size: int = 32,                          # minibatch of cached inputs per AdaRound step
    n_calib_batches: int | None = None,            # cap on calibration batches used
    device: str | torch.device | None = None,      # compute device (default: model's)
    verbose: bool = False,                         # print per-layer progress
) -> nn.Module:                                    # AdaRound fake-quantized model
    """Post-training INT weight quantization with learned rounding (AdaRound, Nagel et al. 2020).

    Signed per-output-channel (or per-tensor) fake-quant whose rounding is *learned* per layer by
    minimising output reconstruction error, recovering most of the INT4 round-to-nearest cliff for
    redundant CNNs (ResNet-class ~ INT8; depthwise-heavy nets stay architecture-dependently lossy).

    Returns an accuracy-faithful **fake-quantized** model (weights quantized then de-quantized
    in-place). It also stashes the exact per-layer quant params on `model._adaround_qparams` so
    `adaround_to_onnx` can write a *faithful* INT4 QDQ ONNX (torchao is the other deployment path). In
    the dimensional `Quantizer` this is `criteria='adaround'`."""
    if calibration_dl is None:
        raise ValueError("adaround_quantize requires calibration data -- pass a DataLoaders, a "
                         "DataLoader, or a list of input batches as `calibration_dl` (got None).")
    if granularity not in ('channel', 'tensor'):
        raise ValueError(f"granularity must be 'channel' or 'tensor', got {granularity!r}.")
    if not 2 <= w_bits <= 8:
        raise ValueError(f"w_bits must be between 2 and 8, got {w_bits}.")
    if act_bits is not None and not 2 <= act_bits <= 8:
        raise ValueError(f"act_bits must be between 2 and 8 (or None), got {act_bits}.")

    qmodel = copy.deepcopy(model).eval()
    device = torch.device(device) if device is not None else next(qmodel.parameters()).device
    qmodel = qmodel.to(device)
    if fold_batchnorm: fold_bn(qmodel)

    batches = _normalize_calibration(calibration_dl, n_calib_batches)
    if len(batches) == 0:
        raise ValueError("calibration_dl yielded no batches.")

    layers = list(_iter_target_layers(qmodel, layer_type))
    layer_names = {m: n for n, m in qmodel.named_modules()}     # module -> dotted name (matches ONNX inits)
    caches = _capture_inputs(qmodel, layers, batches, device)   # FP inputs (parallel AdaRound)

    # stash exact per-layer quant params for faithful INT4 ONNX export (adaround_to_onnx).
    # the scale is *not* recoverable post-hoc: AdaRound bakes W <- scale*int, so capture it here.
    qmodel._adaround_qparams = {}                               # {name: (per-channel scale, qmin, qmax)}
    for i, layer in enumerate(layers):
        scale, qmin, qmax = weight_scale(layer.weight.detach().float(), w_bits, granularity)
        qmodel._adaround_qparams[layer_names[layer]] = (scale.detach().cpu(), int(qmin), int(qmax))
        Wq, info = adaround_layer(layer, caches[layer], w_bits, granularity=granularity,
                                  iters=iters, lr=lr, lam=lam, batch_size=batch_size, device=device)
        layer.weight.data = Wq.to(layer.weight.dtype)
        if verbose:
            print(f"[{i+1}/{len(layers)}] {type(layer).__name__} "
                  f"not_binary={info['not_binary_frac']:.3f}")

    if act_bits is not None:
        _calibrate_activations(qmodel, layers, batches, act_bits, device)
    return qmodel

# %% ../../nbs/quantize/adaround.ipynb #b5556811
def _pack_int4(flat: np.ndarray,  # 1-D array of signed ints in [-8, 7]
    ) -> bytes:                   # packed two-nibbles-per-byte (onnxruntime INT4 raw_data layout)
    "Pack signed int4 values two-per-byte (low nibble first), matching onnxruntime's INT4 initializers."
    v = (flat.astype(np.int32) & 0xF).astype(np.uint8)
    n = v.size; pad = (-n) % 2
    if pad: v = np.concatenate([v, np.zeros(pad, np.uint8)])
    v = v.reshape(-1, 2)
    return (v[:, 0] | (v[:, 1] << 4)).astype(np.uint8).tobytes()

def _unpack_int4(raw: bytes,  # packed int4 bytes (two nibbles per byte)
                 n: int,      # number of int4 values to recover
    ) -> np.ndarray:          # 1-D int8 array of the signed int4 values in [-8, 7]
    "Inverse of `_pack_int4` (sign-extends each 4-bit nibble)."
    b = np.frombuffer(raw, dtype=np.uint8)
    out = np.empty(b.size * 2, dtype=np.int16)
    out[0::2] = b & 0xF
    out[1::2] = (b >> 4) & 0xF
    out = out[:n]
    return np.where(out >= 8, out - 16, out).astype(np.int8)

def adaround_to_onnx(
    model: nn.Module,          # a model returned by `adaround_quantize` (carries `_adaround_qparams`)
    sample: torch.Tensor,      # one example input (batched or [C,H,W]) shaping the ONNX graph
    path: str,                 # output path for the INT4 QDQ ONNX file
    *,
    input_name: str = 'image',   # ONNX graph input name
    calibration_dl = None,       # optional calibration data for activation quant (else synthesized from `sample`)
) -> str:                        # `path` to the written INT4 QDQ ONNX
    """Export an AdaRound model to a *faithful* INT4 QDQ ONNX.

    Standard ONNX exporters recalibrate the weight scale inside `quantize_static`, discarding
    AdaRound's learned up/down rounding (a ~4-7 pt accuracy drop at INT4). This helper instead
    writes AdaRound's **exact** per-channel `scale` and int4 weights into the QDQ initializers, so
    the deployed ONNX carries the *learned* rounding and matches the fake-quant accuracy.

    The graph is produced in three steps: (1) export the fake-quant model to FP32 ONNX (legacy
    exporter, dynamic batch); (2) run onnxruntime `quantize_static` (QDQ, per-channel QInt4 weights,
    QInt8 activations) to get the correct QDQ *structure* with ORT's own (wrong) scales; (3) overwrite
    the weight `_scale` and int4 `_quantized` initializers with AdaRound's exact params from
    `model._adaround_qparams`. Requires `onnx` and `onnxruntime`."""
    qparams = getattr(model, '_adaround_qparams', None)
    if qparams is None:
        raise ValueError("model has no `_adaround_qparams` -- call adaround_quantize first "
                         "(the exact per-layer scales cannot be recovered from the baked weights).")
    try:
        import onnx
        from onnx import numpy_helper
        from onnxruntime.quantization import (quantize_static, QuantType, QuantFormat,
                                              CalibrationDataReader, quant_pre_process,
                                              CalibrationMethod)
    except ImportError as e:
        raise ImportError("adaround_to_onnx requires onnx and onnxruntime. "
                          "Install with: pip install onnx onnxruntime") from e
    import os, tempfile

    orig_device = next(model.parameters()).device
    model.eval().cpu()
    dummy = sample.detach().cpu().float()
    if dummy.dim() == 3: dummy = dummy.unsqueeze(0)

    # AdaRound-baked weights keyed by module name (== _adaround_qparams keys == ONNX init prefixes)
    ada_w = {n: m.weight.detach().float().cpu()
             for n, m in model.named_modules() if isinstance(m, (nn.Conv2d, nn.Linear))}

    # calibration images for the activation-quant statistics -> list of float32 arrays
    if calibration_dl is not None:
        calib = [b.detach().cpu().float().numpy() for b in _normalize_calibration(calibration_dl)]
    else:  # synthesize a few perturbed copies of `sample` so MinMax sees a plausible activation range
        calib = [dummy.numpy()] + [(dummy + 0.1 * torch.randn_like(dummy)).numpy() for _ in range(3)]

    class _DR(CalibrationDataReader):
        def __init__(self): self._it = iter([{input_name: a} for a in calib])
        def get_next(self): return next(self._it, None)

    with tempfile.TemporaryDirectory() as td:
        fp, pre = os.path.join(td, 'fp32.onnx'), os.path.join(td, 'pre.onnx')
        # (1) FP32 ONNX -- dynamo=False (the dynamo exporter breaks ORT's quant_pre_process)
        torch.onnx.export(model, dummy, fp, input_names=[input_name], output_names=['output'],
                          dynamic_axes={input_name: {0: 'batch'}, 'output': {0: 'batch'}},
                          opset_version=18, dynamo=False)
        # (2) standard ORT INT4 QDQ -- correct graph, ORT's (wrong) scales/ints
        quant_pre_process(fp, pre)
        quantize_static(pre, path, _DR(), quant_format=QuantFormat.QDQ, per_channel=True,
                        weight_type=QuantType.QInt4, activation_type=QuantType.QInt8,
                        op_types_to_quantize=['Conv', 'Gemm'],
                        calibrate_method=CalibrationMethod.MinMax)
    model.to(orig_device)

    # (3) overwrite the weight initializers with AdaRound's EXACT int4 + scale
    m = onnx.load(path)
    inits = {i.name: i for i in m.graph.initializer}
    for nm in list(inits):
        if not nm.endswith('.weight_quantized'): continue
        base = nm[:-len('_quantized')]          # '<mod>.weight'
        mod  = base[:-len('.weight')]           # '<mod>'
        if mod not in qparams: continue
        scale, qmin, qmax = qparams[mod]
        scale = scale.detach().cpu()
        inits[base + '_scale'].CopyFrom(
            numpy_helper.from_array(scale.reshape(-1).float().numpy(), base + '_scale'))
        int_ada = torch.round(ada_w[mod].double() / scale.double()).clamp(qmin, qmax).to(torch.int8).numpy()
        t = inits[nm]; t.ClearField('int32_data'); t.raw_data = _pack_int4(int_ada.reshape(-1))
    # drop the value_info that duplicates graph IO (an artifact ORT can leave behind)
    io = {o.name for o in m.graph.output} | {i.name for i in m.graph.input}
    keep = [vi for vi in m.graph.value_info if vi.name not in io]
    del m.graph.value_info[:]; m.graph.value_info.extend(keep)
    onnx.save(m, path)
    return path

