# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/quantize/adaround.ipynb.

# %% ../../nbs/quantize/adaround.ipynb #1746d882
from __future__ import annotations
import copy
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils.fusion import fuse_conv_bn_eval

# %% auto #0
__all__ = ['fold_bn', 'weight_scale', 'rtn_quant', 'adaround_layer', 'adaround_quantize']

# %% ../../nbs/quantize/adaround.ipynb #80a30f53
def _set_child(parent, name, new):
    "Replace child module `name` of `parent` (handles Sequential integer indices)."
    if name.isdigit(): parent[int(name)] = new
    else: setattr(parent, name, new)

def fold_bn(model: nn.Module   # model containing Conv2d→BatchNorm2d pairs
    ) -> nn.Module:            # same model with each Conv-BN pair fused in-place
    "Fuse each `Conv2d`→`BatchNorm2d` pair into the conv (eval mode) and replace the BN with Identity."
    for mod in model.modules():
        kids = list(mod.named_children())
        for i in range(len(kids) - 1):
            (n1, c1), (n2, c2) = kids[i], kids[i + 1]
            if isinstance(c1, nn.Conv2d) and isinstance(c2, nn.BatchNorm2d):
                _set_child(mod, n1, fuse_conv_bn_eval(c1, c2))
                _set_child(mod, n2, nn.Identity())
    return model

# %% ../../nbs/quantize/adaround.ipynb #c9f0e214
def weight_scale(W: torch.Tensor,             # weight tensor [out_channels, ...]
                 w_bits: int = 4,             # bit-width (signed)
                 granularity: str = 'channel',  # 'channel' (per-output-channel) or 'tensor'
    ):                                        # (scale, qmin, qmax) — dequant scale and signed clip range
    "Signed weight quantization `scale` and clip range `[qmin, qmax]` on the ONNX/ORT grid."
    qmax =   2 ** (w_bits - 1) - 1                     # INT4 ->  7,  INT8 ->  127
    qmin = -(2 ** (w_bits - 1))                        # INT4 -> -8,  INT8 -> -128 (asymmetric signed grid)
    denom =  2 ** (w_bits - 1) - 0.5                   # INT4 -> 7.5  (matches onnxruntime per-channel int4)
    if granularity == 'channel':
        r = W.detach().abs().reshape(W.shape[0], -1).amax(1).clamp_min(1e-12)
        scale = (r / denom).reshape([-1] + [1] * (W.dim() - 1))
    else:
        scale = W.detach().abs().amax().clamp_min(1e-12) / denom
    return scale, qmin, qmax

def rtn_quant(W: torch.Tensor,                # weight tensor to fake-quantize
              w_bits: int = 4,                # bit-width
              granularity: str = 'channel',   # 'channel' or 'tensor'
    ) -> torch.Tensor:                        # dequantized (fake-quant) weights, same shape
    "Round-to-nearest (RTN) signed fake-quant — the AdaRound baseline (== AdaRound at init)."
    scale, qmin, qmax = weight_scale(W, w_bits, granularity)
    floorWs = torch.floor(W / scale)
    q = floorWs + ((W / scale - floorWs) >= 0.5).float()  # round half up (matches the AdaRound hard round)
    return torch.clamp(q, qmin, qmax) * scale

# %% ../../nbs/quantize/adaround.ipynb #d948dfff
# AdaRound rectified-sigmoid soft rounding (Nagel et al., 2020):
#   h(V) = clamp(sigmoid(V)*(zeta-gamma)+gamma, 0, 1)
#   W_q(V) = s * clamp(floor(W/s) + h(V), qmin, qmax)
_ZETA, _GAMMA = 1.1, -0.1

def _rect_sigmoid(V: torch.Tensor) -> torch.Tensor:
    "Rectified sigmoid squashing `V` into a soft rounding decision in [0, 1]."
    return torch.clamp(torch.sigmoid(V) * (_ZETA - _GAMMA) + _GAMMA, 0, 1)

def _init_V(frac: torch.Tensor) -> torch.Tensor:
    "Initialise `V` so that `h(V) == frac(W/s)` — makes AdaRound identical to RTN at init."
    s0 = ((frac - _GAMMA) / (_ZETA - _GAMMA)).clamp(1e-6, 1 - 1e-6)
    return torch.log(s0 / (1 - s0))

def _hard_quant_from_V(V, floorWs, scale, qmin, qmax):
    "Deployed weights: hard-round the learned soft rounding `h(V)` onto the signed grid."
    h_hard = (_rect_sigmoid(V) >= 0.5).float()
    return scale * torch.clamp(floorWs + h_hard, qmin, qmax)

def _layer_fwd(mod, x, w, b):
    "Forward one Conv2d/Linear layer with an explicit weight/bias (for reconstruction)."
    if isinstance(mod, nn.Conv2d):
        return F.conv2d(x, w, b, mod.stride, mod.padding, mod.dilation, mod.groups)
    return F.linear(x, w, b)

# %% ../../nbs/quantize/adaround.ipynb #ab024063
def adaround_layer(layer: nn.Module,             # Conv2d/Linear whose rounding is optimized
                   x_cal: torch.Tensor,          # cached FP inputs to this layer [N, ...]
                   w_bits: int = 4,              # weight bit-width
                   *,
                   granularity: str = 'channel',  # 'channel' or 'tensor'
                   iters: int = 2000,            # optimization iterations
                   lr: float = 1e-2,             # Adam learning rate
                   lam: float = 0.01,            # rounding-regularizer weight
                   beta_start: float = 20.0,     # anneal start (encourages soft)
                   beta_end: float = 2.0,        # anneal end (encourages binary)
                   warmup: float = 0.2,          # fraction of iters before regularizer turns on
                   batch_size: int = 32,         # minibatch of cached inputs per step
                   device: str | torch.device | None = None,  # compute device (default: layer's)
    ):                                           # (Wq_hard, info) — deployed fake-quant weights + diagnostics
    "Learn per-weight soft rounding for one layer, minimising output reconstruction ‖W_q(V)x − Wx‖² + regularizer."
    device = torch.device(device) if device is not None else layer.weight.device
    W = layer.weight.detach().float().to(device)
    scale, qmin, qmax = weight_scale(W, w_bits, granularity)
    floorWs = torch.floor(W / scale)
    frac = (W / scale) - floorWs                          # in [0, 1)
    V = _init_V(frac).clone().requires_grad_(True)        # init so h(V) == frac  (== RTN)
    opt = torch.optim.Adam([V], lr=lr)
    bias = layer.bias.detach().float().to(device) if layer.bias is not None else None
    N = x_cal.shape[0]
    warm_iters = int(warmup * iters)
    for it in range(iters):
        idx = torch.randint(0, N, (min(batch_size, N),))
        xb = x_cal[idx].to(device, dtype=torch.float32)
        h = _rect_sigmoid(V)
        Wq = scale * torch.clamp(floorWs + h, qmin, qmax)
        out_q = _layer_fwd(layer, xb, Wq, bias)
        with torch.no_grad():
            out_fp = _layer_fwd(layer, xb, W, bias)
        rec = (out_q - out_fp).pow(2).flatten(1).sum(1).mean()  # per-sample SSE, averaged
        if it < warm_iters:
            beta, lam_t = beta_start, 0.0                       # warmup: reconstruction only
        else:
            rel = (it - warm_iters) / max(1, iters - warm_iters)
            beta = beta_end + (beta_start - beta_end) * max(0.0, 1 - rel)
            lam_t = lam
        round_loss = lam_t * (1 - (2 * h - 1).abs().pow(beta)).sum()  # push h -> {0, 1}
        loss = rec + round_loss
        opt.zero_grad(); loss.backward(); opt.step()
    with torch.no_grad():
        h = _rect_sigmoid(V)
        not_binary = ((h > 0.02) & (h < 0.98)).float().mean().item()  # unresolved fraction
        Wq_hard = _hard_quant_from_V(V, floorWs, scale, qmin, qmax)
    return Wq_hard, {'not_binary_frac': not_binary, 'w_bits': w_bits, 'granularity': granularity}

# %% ../../nbs/quantize/adaround.ipynb #10fa2568
def _iter_target_layers(model: nn.Module,                     # model to scan
                        layer_type = (nn.Conv2d, nn.Linear),  # module type(s) to target
    ):
    "Iterate over modules of `layer_type` (the AdaRound analogue of `Sparsifier._iter_layers`)."
    for m in model.modules():
        if isinstance(m, layer_type):
            yield m

def _normalize_calibration(calibration_dl,               # DataLoaders | DataLoader | list of batches
                           n_batches: int | None = None,  # cap on number of batches
    ) -> list:                                           # list of input tensors (xb)
    "Normalise the three accepted calibration inputs to a list of input tensors."
    dl = calibration_dl
    if hasattr(dl, 'valid') and hasattr(dl, 'train'):    # fastai DataLoaders -> use validation dl
        dl = dl.valid
    batches = []
    for b in dl:
        xb = b[0] if isinstance(b, (list, tuple)) else b  # (xb, yb) batch or a bare input tensor
        batches.append(xb)
        if n_batches is not None and len(batches) >= n_batches:
            break
    return batches

@torch.no_grad()
def _capture_inputs(model,                          # (pristine) FP model
                    layers,                         # target layers to hook
                    batches,                        # list of input tensors
                    device,                         # compute device
                    store_dtype = torch.float16,    # cache dtype (saves memory)
    ) -> dict:                                      # {layer: cached inputs [N, ...] on CPU}
    "Cache the FP input tensor to every target layer in a single forward pass."
    cache = {l: [] for l in layers}
    def make_hook(layer):
        def hook(mod, inp):
            cache[layer].append(inp[0].detach().to(store_dtype).cpu())
        return hook
    handles = [l.register_forward_pre_hook(make_hook(l)) for l in layers]
    model.eval()
    for xb in batches:
        model(xb.to(device))
    for h in handles: h.remove()
    return {l: torch.cat(v) for l, v in cache.items()}

# %% ../../nbs/quantize/adaround.ipynb #aeba40b3
def _fake_quant_act(x, scale, qmax):
    "Per-tensor symmetric fake-quant of an activation tensor."
    return torch.clamp(torch.round(x / scale), -qmax, qmax) * scale

@torch.no_grad()
def _calibrate_activations(model,           # weight-quantized model
                           layers,          # target layers
                           batches,         # calibration input tensors
                           act_bits: int,   # activation bit-width
                           device,          # compute device
                           n_batches: int = 8,  # batches used for statistics
    ):
    "Calibrate MSE-optimal per-tensor activation scales and install persistent fake-quant pre-hooks."
    qmax = 2 ** (act_bits - 1) - 1
    samples = {l: [] for l in layers}
    def obs(mod, inp):
        v = inp[0].detach().flatten()
        if v.numel() > 20000:
            v = v[torch.randint(0, v.numel(), (20000,), device=v.device)]
        samples[mod].append(v.float().cpu())
    handles = [l.register_forward_pre_hook(obs) for l in layers]
    model.eval()
    for i, xb in enumerate(batches):
        if i >= n_batches: break
        model(xb.to(device))
    for h in handles: h.remove()
    alphas = [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.4, 0.3]
    def make_hook(scale, qmax):
        def hook(mod, inp):
            return (_fake_quant_act(inp[0], scale, qmax),) + tuple(inp[1:])
        return hook
    for l in layers:
        a = torch.cat(samples[l]); mx = a.abs().max().item()
        best_mse, best_clip = float('inf'), mx
        for al in alphas:                                 # search clip minimising quant MSE
            clip = al * mx
            if clip <= 0: continue
            scale = clip / qmax
            q = torch.clamp(torch.round(a / scale), -qmax, qmax) * scale
            mse = ((q - a) ** 2).mean().item()
            if mse < best_mse: best_mse, best_clip = mse, clip
        l.register_forward_pre_hook(make_hook(max(best_clip, 1e-12) / qmax, qmax))

# %% ../../nbs/quantize/adaround.ipynb #094c67f0
def adaround_quantize(
    model: nn.Module,                              # model whose weights -> INT-`w_bits` with learned rounding
    calibration_dl,                                # fastai DataLoaders | torch DataLoader | list of (xb, yb)/xb batches -- REQUIRED
    w_bits: int = 4,                               # weight bit-width
    granularity: str = 'channel',                  # 'channel' (per-output-channel) or 'tensor'
    act_bits: int | None = None,                   # activation bit-width (None -> weight-only)
    iters: int = 2000,                             # AdaRound optimization iters per layer
    lr: float = 1e-2,                              # Adam learning rate
    fold_batchnorm: bool = True,                   # fuse Conv->BN before quantizing
    layer_type = (nn.Conv2d, nn.Linear),           # module type(s) to quantize
    *,
    lam: float = 0.01,                             # AdaRound rounding-regularizer weight
    batch_size: int = 32,                          # minibatch of cached inputs per AdaRound step
    n_calib_batches: int | None = None,            # cap on calibration batches used
    device: str | torch.device | None = None,      # compute device (default: model's)
    verbose: bool = False,                         # print per-layer progress
) -> nn.Module:                                    # AdaRound fake-quantized model
    """Post-training INT weight quantization with learned rounding (AdaRound, Nagel et al. 2020).

    Signed per-output-channel (or per-tensor) fake-quant whose rounding is *learned* per layer by
    minimising output reconstruction error, recovering most of the INT4 round-to-nearest cliff for
    redundant CNNs (ResNet-class ~ INT8; depthwise-heavy nets stay architecture-dependently lossy).

    Returns an accuracy-faithful **fake-quantized** model (weights quantized then de-quantized
    in-place). Real INT4-kernel export (torchao / ONNX-QDQ) is the deployment follow-up. In the
    dimensional `Quantizer` this is `criteria='adaround'`."""
    if calibration_dl is None:
        raise ValueError("adaround_quantize requires calibration data -- pass a DataLoaders, a "
                         "DataLoader, or a list of input batches as `calibration_dl` (got None).")
    if granularity not in ('channel', 'tensor'):
        raise ValueError(f"granularity must be 'channel' or 'tensor', got {granularity!r}.")
    if not 2 <= w_bits <= 8:
        raise ValueError(f"w_bits must be between 2 and 8, got {w_bits}.")
    if act_bits is not None and not 2 <= act_bits <= 8:
        raise ValueError(f"act_bits must be between 2 and 8 (or None), got {act_bits}.")

    qmodel = copy.deepcopy(model).eval()
    device = torch.device(device) if device is not None else next(qmodel.parameters()).device
    qmodel = qmodel.to(device)
    if fold_batchnorm: fold_bn(qmodel)

    batches = _normalize_calibration(calibration_dl, n_calib_batches)
    if len(batches) == 0:
        raise ValueError("calibration_dl yielded no batches.")

    layers = list(_iter_target_layers(qmodel, layer_type))
    caches = _capture_inputs(qmodel, layers, batches, device)  # FP inputs (parallel AdaRound)

    for i, layer in enumerate(layers):
        Wq, info = adaround_layer(layer, caches[layer], w_bits, granularity=granularity,
                                  iters=iters, lr=lr, lam=lam, batch_size=batch_size, device=device)
        layer.weight.data = Wq.to(layer.weight.dtype)
        if verbose:
            print(f"[{i+1}/{len(layers)}] {type(layer).__name__} "
                  f"not_binary={info['not_binary_frac']:.3f}")

    if act_bits is not None:
        _calibrate_activations(qmodel, layers, batches, act_bits, device)
    return qmodel
