# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/quantize/fake_quantize_callback.ipynb.

# %% ../../nbs/quantize/fake_quantize_callback.ipynb #imports
from __future__ import annotations
import torch
import torch.nn as nn
from dataclasses import replace
from fastai.callback.all import *
from fastcore.basics import store_attr
from torch.nn.utils import parametrize
from ..core.parametrize import _is_parametrized, _master, _unparametrize
from ..core.precision import FAKE_SPEC_ATTR
from .fake_quantizer import (FakeQuantizer, _ActRounder, _fake_quantize, _qrange,
                                              _scale_zero)

# %% auto #0
__all__ = ['FakeQuantizeCallback']

# %% ../../nbs/quantize/fake_quantize_callback.ipynb #klass
_DEFAULT_AVERAGING = 0.01  # the constant torch's `MovingAverageMinMaxObserver` uses


class _FakeQuantWeight(nn.Module):
    "Weight parametrization: the module computes its weight by rounding a floating-point master"
    def __init__(self, bits: int, symmetric: bool, qscheme: str, group_size: int | None):
        super().__init__()
        store_attr()

    def forward(self, w):
        q = _fake_quantize(w.detach(), self.bits, self.symmetric, self.qscheme, self.group_size)
        return w + (q - w.detach())  # the value the post-training path writes, passing the gradient on


class _ActObserver:
    "Forward hook rounding a module's output onto a grid it keeps observing, until the scales are frozen"
    def __init__(self, bits: int, symmetric: bool, averaging: float | None):
        store_attr()
        self.frozen, self.enabled = False, True

    def __call__(self, mod, inp, out):
        if not isinstance(out, torch.Tensor): return out
        if (mod.training and not self.frozen) or '_act_scale' not in mod._buffers:
            self._observe(mod, out)
        if not self.enabled: return out  # `FakeQuantizer.calibrate` stands the rounding down to observe
        return torch.fake_quantize_per_tensor_affine(out, mod._act_scale, mod._act_zero_point,
                                                     *_qrange(self.bits, self.symmetric))

    def _observe(self, mod, out) -> None:
        "Move the observed range towards this batch, and rewrite the scales it defines"
        lo, hi = out.detach().amin(), out.detach().amax()
        if '_act_min' in mod._buffers:
            if self.averaging is None:
                lo, hi = torch.minimum(mod._act_min, lo), torch.maximum(mod._act_max, hi)
            else:
                lo, hi = (torch.lerp(mod._act_min, lo, self.averaging),
                          torch.lerp(mod._act_max, hi, self.averaging))
        scale, zero = _scale_zero(lo, hi, self.bits, self.symmetric)
        for name, value in (('_act_min', lo), ('_act_max', hi),
                            ('_act_scale', scale), ('_act_zero_point', zero)):
            mod.register_buffer(name, value, persistent=False)


class FakeQuantizeCallback(Callback):
    """Quantization-aware training on `FakeQuantizer`'s arithmetic: the fit sees rounded weights, the
    optimizer trains floating-point ones.

    `before_fit` parametrizes every weight this rounds, so the forward computes it from a master the
    gradient reaches; `after_fit` bakes the rounding in and leaves the model `quantize_model()` leaves.
    `self.fake_quantizer` is that quantizer, and its `remove()` gives back the master **as the fit left
    it** — the trained weights, not the ones training started from.

    A fit that raises never reaches `after_fit` and leaves the parametrizations in place, on a model
    `torch.save` refuses: `strip()` takes them off and keeps the floating-point weights, `bake()` keeps
    the rounding.

    Nothing here folds or freezes BatchNorm, so the weight ranges rounded are not the ones a deployed
    flow would see. The activation rounding sits on each module's own output, before whatever activation
    function follows it, where an integer runtime fuses the two and rounds once."""
    order = 70  # above SaveModelCallback (61), whose after_fit loads a checkpoint into the model

    def __init__(self,
                 weight_bits: int | None = 8,   # Weight width; None leaves them in floating point
                 act_bits: int | None = None,   # Activation width; None leaves them in floating point
                 qscheme: str = 'per_channel',  # Weight scale axis: 'per_tensor', 'per_channel' or 'per_group'
                 symmetric: bool = True,        # Zero-point 0, or an affine offset
                 group_size: int | None = None, # Weights sharing one scale (qscheme='per_group')
                 observer: str = 'static',      # Activation scales: 'static' (observed, then frozen) or 'dynamic'
                 layer_type: type | tuple = (nn.Conv2d, nn.Linear),  # Module types that carry the rounding
                 layer_bits: dict | None = None,      # {layer_name: width} overriding `weight_bits`
                 layer_act_bits: dict | None = None,  # {layer_name: width} overriding `act_bits`
                 freeze_act_pct: float = 0.9,         # Training fraction after which the activation scales stop moving
                 act_averaging: float | None = _DEFAULT_AVERAGING,  # How far the observed range moves towards each batch; None takes its absolute min and max
                 model: nn.Module | None = None,      # Model to round; None = learn.model
    ):
        "Train through a simulated width, and bake it in when the fit ends"
        store_attr()
        if not 0 <= freeze_act_pct <= 1:
            raise ValueError(f"`freeze_act_pct={freeze_act_pct}` is not a fraction of the training: pass "
                             "a value in [0, 1] (0.9 freezes the scales for the last tenth of the fit).")
        if act_averaging is not None and not 0 < act_averaging <= 1:
            raise ValueError(f"`act_averaging={act_averaging}` is not an averaging constant: pass a value "
                             "in (0, 1], or None to observe the absolute min and max.")
        self.fake_quantizer, self.frozen = None, False
        self._installed, self._baked = False, False

    def before_fit(self) -> None:
        "Build the quantizer, parametrize the weights it rounds, and start observing the activations"
        self._check_alone()
        if self._installed:
            raise RuntimeError("This callback is still installed from a fit that did not finish: call "
                               "strip() for the floating-point weights, or bake() to keep the rounding, "
                               "before fitting again.")
        if self._baked: self.fake_quantizer.remove()  # a second fit resumes from the master the first trained
        self.fake_quantizer = FakeQuantizer(self.model or self.learn.model, self.weight_bits,
                                            self.act_bits, self.qscheme, self.symmetric, self.group_size,
                                            self.observer, self.layer_type, self.layer_bits,
                                            self.layer_act_bits)
        self.frozen, self._baked = False, False
        self._install()
        print(f'Training through {self.fake_quantizer.spec.label}, weights {self.qscheme}')

    def before_batch(self) -> None:
        "Freeze the activation scales once the fit is `freeze_act_pct` through"
        if self.training and self.pct_train >= self.freeze_act_pct: self._freeze_act()

    def after_fit(self) -> None:
        "Bake the rounding in, unless the model was stripped by hand during the fit"
        if self._installed: self.bake()

    def bake(self) -> nn.Module:
        "Round the trained master into an ordinary weight, and leave the model `quantize_model()` leaves"
        if not self._installed:
            raise RuntimeError("Nothing is installed to bake: run a fit with this callback, which "
                               "installs the rounding and bakes it at the end.")
        fq = self.fake_quantizer
        blind = next((n for n, m in fq._named if isinstance(self._rounder(m), _ActObserver)
                      and '_act_scale' not in m._buffers), None)
        if blind is not None:   # refuse before a single weight is written, as `_check_model` does
            raise RuntimeError(f"'{blind}' never saw a training batch, so nothing observed its activation "
                               "range: fit at least one batch, or leave its activations in floating point "
                               "with layer_act_bits.")
        self._freeze_act()  # a threshold a short fit never reached must not leave the scales moving
        for _, m in fq._named:
            if not _is_parametrized(m): continue
            m.register_buffer('_fp_weight', _master(m).detach().clone(), persistent=False)
            _unparametrize(m, leave_parametrized=True)
        for m, (handle, rounder) in list(fq._act_hooks.items()):
            for name in ('_act_min', '_act_max'):
                if name in m._buffers: delattr(m, name)
            if not isinstance(rounder, _ActObserver): continue
            handle.remove()  # the scales are frozen: from here the post-training rounder reads them
            ptq = _ActRounder(rounder.bits, rounder.symmetric, False)
            fq._act_hooks[m] = (m.register_forward_hook(ptq), ptq)
        fq._calibrated, fq._quantized = True, True
        setattr(fq.model, FAKE_SPEC_ATTR, replace(fq.spec, trained=True))
        self._installed, self._baked = False, True
        print(f'Baked in {fq.spec.label}: the model holds its rounded weights, and '
              'fake_quantizer.remove() gives the trained floating-point ones back')
        return fq.model

    def strip(self) -> nn.Module:
        "Drop the rounding and keep the floating-point master — the way back from a fit that raised"
        if self.fake_quantizer is None:
            raise RuntimeError("There is nothing to strip: this callback has not started a fit yet.")
        if self._baked:
            raise RuntimeError("This fit is already baked: call fake_quantizer.remove() for the "
                               "floating-point weights it trained.")
        fq = self.fake_quantizer
        for handle, _ in fq._act_hooks.values(): handle.remove()
        fq._act_hooks = {}
        for _, m in fq._named:
            _unparametrize(m)
            for name in ('_act_min', '_act_max', '_act_scale', '_act_zero_point'):
                if name in m._buffers: delattr(m, name)
        self._installed = False
        return fq.model

    def _install(self) -> None:
        "Parametrize every weight this rounds, and hook every activation it observes"
        fq = self.fake_quantizer
        already = next((n for n, m in fq._named if _is_parametrized(m)), None)
        if already is not None:
            raise RuntimeError(f"'{already}' already computes its weight from a parametrization: remove "
                               "it before training through a simulated width.")
        for _, m in fq._named:
            bits = fq._weight_map[m]
            if bits is not None:
                parametrize.register_parametrization(
                    m, 'weight', _FakeQuantWeight(bits, fq.symmetric, fq.qscheme, fq.group_size))
            act_bits = fq._act_map[m]
            if act_bits is not None:
                rounder = (_ActRounder(act_bits, fq.symmetric, True) if fq.observer == 'dynamic'
                           else _ActObserver(act_bits, fq.symmetric, self.act_averaging))
                fq._act_hooks[m] = (m.register_forward_hook(rounder), rounder)
        self._installed = True

    def _rounder(self, m: nn.Module):
        "The hook rounding this module's output, when it rounds one"
        hook = self.fake_quantizer._act_hooks.get(m)
        return hook[1] if hook else None

    def _freeze_act(self) -> None:
        "Stop the observers moving: from here the fit trains on the scales the model will keep"
        for _, rounder in self.fake_quantizer._act_hooks.values():
            if isinstance(rounder, _ActObserver): rounder.frozen = True
        self.frozen = True

    def _check_alone(self) -> None:
        "Refuse a fit that also carries `QuantizeCallback`, which swaps the model this one parametrizes"
        from fasterai.quantize.quantize_callback import QuantizeCallback
        if any(isinstance(cb, QuantizeCallback) for cb in self.learn.cbs):
            raise ValueError("QuantizeCallback and FakeQuantizeCallback both rewrite the model being "
                             "trained, and the first swaps out what the second parametrizes: keep one.")
