# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/quantize/fake_quantize_callback.ipynb.

# %% ../../nbs/quantize/fake_quantize_callback.ipynb #imports
from __future__ import annotations
import torch
import torch.nn as nn
from collections.abc import Sequence
from dataclasses import replace
from fastai.callback.all import *
from fastcore.basics import store_attr
from torch.nn.utils import parametrize
from ..core.parametrize import _is_parametrized, _master, _unparametrize
from ..core.precision import FAKE_SPEC_ATTR, _type_error
from ..core.schedule import Schedule
from .fake_quantizer import (FakeQuantizer, _ActRounder, _check_bits, _fake_quantize,
                                              _qrange, _scale_zero)

# %% auto #0
__all__ = ['FakeQuantizeCallback']

# %% ../../nbs/quantize/fake_quantize_callback.ipynb #klass
_DEFAULT_AVERAGING = 0.01  # the constant torch's `MovingAverageMinMaxObserver` uses


class _FakeQuantWeight(nn.Module):
    "Weight parametrization: the module computes its weight by rounding a floating-point master"
    def __init__(self, bits: int, symmetric: bool, qscheme: str, group_size: int | None):
        super().__init__()
        store_attr()

    def forward(self, w):
        q = _fake_quantize(w.detach(), self.bits, self.symmetric, self.qscheme, self.group_size)
        return w + (q - w.detach())  # the value the post-training path writes, passing the gradient on


class _ActObserver:
    "Forward hook rounding a module's output onto a grid it keeps observing, until the scales are frozen"
    def __init__(self, bits: int, symmetric: bool, averaging: float | None):
        store_attr()
        self.frozen, self.enabled = False, True

    def __call__(self, mod, inp, out):
        if not isinstance(out, torch.Tensor): return out
        if (mod.training and not self.frozen) or '_act_scale' not in mod._buffers:
            self._observe(mod, out)
        if not self.enabled: return out  # `FakeQuantizer.calibrate` stands the rounding down to observe
        return torch.fake_quantize_per_tensor_affine(out, mod._act_scale, mod._act_zero_point,
                                                     *_qrange(self.bits, self.symmetric))

    def _observe(self, mod, out) -> None:
        "Move the observed range towards this batch, and rewrite the scales it defines"
        lo, hi = out.detach().amin(), out.detach().amax()
        if '_act_min' in mod._buffers:
            if self.averaging is None:
                lo, hi = torch.minimum(mod._act_min, lo), torch.maximum(mod._act_max, hi)
            else:
                lo, hi = (torch.lerp(mod._act_min, lo, self.averaging),
                          torch.lerp(mod._act_max, hi, self.averaging))
        scale, zero = _scale_zero(lo, hi, self.bits, self.symmetric)
        for name, value in (('_act_min', lo), ('_act_max', hi),
                            ('_act_scale', scale), ('_act_zero_point', zero)):
            mod.register_buffer(name, value, persistent=False)


def _check_ladder(axis: str, schedule, widths, target: int | None) -> tuple[int, ...] | None:
    "Validate one width ladder against the schedule stepping it and the width it must end at"
    if schedule is None and widths is None: return None
    if target is None:
        raise ValueError(f"{axis}_bits=None leaves this axis in floating point, so a ladder has no width "
                         f"to lower: name the width to end at with `{axis}_bits=`, or drop the ladder.")
    if widths is None:
        raise ValueError(f"`{axis}_schedule` has no ladder to step through: pass `{axis}_widths=`, the "
                         f"widths to go down through, coarsest first and ending at {axis}_bits={target}.")
    if isinstance(widths, str) or not isinstance(widths, Sequence):
        raise _type_error(f'{axis}_widths', 'a sequence of widths, coarsest first', widths)
    if schedule is None:
        raise ValueError(f"`{axis}_widths={tuple(widths)}` is never stepped through: pass "
                         f"`{axis}_schedule=`, the fasterai `Schedule` whose progress selects the rung.")
    widths = tuple(widths)
    if len(widths) < 2:
        raise ValueError(f"`{axis}_widths={widths}` steps nothing: pass at least two widths, from the "
                         f"coarsest one down to {axis}_bits={target}, or drop `{axis}_schedule`.")
    for i, w in enumerate(widths):
        if w is None:
            raise ValueError(f"`{axis}_widths[{i}]=None` is not a rung: pass a width in [2, 16] there, "
                             f"and {axis}_bits=None if you meant to leave the axis in floating point.")
        _check_bits(f"{axis}_widths[{i}]", w, f"and only {axis}_bits=None leaves an axis in floating point")
    if widths[-1] != target:
        raise ValueError(f"`{axis}_widths={widths}` must end at the width this rounds to: make its last "
                         f"rung {axis}_bits={target}.")
    if any(a <= b for a, b in zip(widths, widths[1:])):
        raise ValueError(f"`{axis}_widths={widths}` does not go down: pass strictly decreasing widths, "
                         "the coarsest one first.")
    return widths


def _rung(ladder: tuple[int, ...], progress: float) -> int:
    "The width a progress in [0, 1] selects, the rungs sharing it equally"
    return ladder[min(max(int(progress * len(ladder)), 0), len(ladder) - 1)]


class FakeQuantizeCallback(Callback):
    """Quantization-aware training on `FakeQuantizer`'s arithmetic: the fit sees rounded weights, the
    optimizer trains floating-point ones.

    `before_fit` parametrizes every weight this rounds, so the forward computes it from a master the
    gradient reaches; `after_fit` bakes the rounding in and leaves the model `quantize_model()` leaves.
    `self.fake_quantizer` is that quantizer, and its `remove()` gives back the master **as the fit left
    it** — the trained weights, not the ones training started from.

    A fit that raises never reaches `after_fit` and leaves the parametrizations in place, on a model
    `torch.save` refuses: `strip()` takes them off and keeps the floating-point weights, `bake()` keeps
    the rounding.

    A schedule can lower the width during the fit rather than rounding at the target from the first
    batch (`weight_schedule` / `weight_widths`, and their activation twins). Whether that is worth
    doing is not measured here.

    Nothing here folds or freezes BatchNorm, so the weight ranges rounded are not the ones a deployed
    flow would see. The activation rounding sits on each module's own output, before whatever activation
    function follows it, where an integer runtime fuses the two and rounds once."""
    order = 70  # above SaveModelCallback (61), whose after_fit loads a checkpoint into the model

    def __init__(self,
                 weight_bits: int | None = 8,   # Weight width; None leaves them in floating point
                 act_bits: int | None = None,   # Activation width; None leaves them in floating point
                 qscheme: str = 'per_channel',  # Weight scale axis: 'per_tensor', 'per_channel' or 'per_group'
                 symmetric: bool = True,        # Zero-point 0, or an affine offset
                 group_size: int | None = None, # Weights sharing one scale (qscheme='per_group')
                 observer: str = 'static',      # Activation scales: 'static' (observed, then frozen) or 'dynamic'
                 layer_type: type | tuple = (nn.Conv2d, nn.Linear),  # Module types that carry the rounding
                 layer_bits: dict | None = None,      # {layer_name: width} overriding `weight_bits`
                 layer_act_bits: dict | None = None,  # {layer_name: width} overriding `act_bits`
                 freeze_act_pct: float = 0.9,         # Training fraction after which the activation scales stop moving
                 act_averaging: float | None = _DEFAULT_AVERAGING,  # How far the observed range moves towards each batch; None takes its absolute min and max
                 weight_schedule: Schedule | None = None,  # Schedule stepping `weight_widths`; None rounds at `weight_bits` from the first batch
                 weight_widths: Sequence[int] | None = None,  # Weight widths to step down through, coarsest first, ending at `weight_bits`
                 act_schedule: Schedule | None = None,     # Schedule stepping `act_widths`; None rounds at `act_bits` from the first batch
                 act_widths: Sequence[int] | None = None,     # Activation widths to step down through, coarsest first, ending at `act_bits`
                 model: nn.Module | None = None,      # Model to round; None = learn.model
    ):
        "Train through a simulated width, and bake it in when the fit ends"
        store_attr()
        if not 0 <= freeze_act_pct <= 1:
            raise ValueError(f"`freeze_act_pct={freeze_act_pct}` is not a fraction of the training: pass "
                             "a value in [0, 1] (0.9 freezes the scales for the last tenth of the fit).")
        if act_averaging is not None and not 0 < act_averaging <= 1:
            raise ValueError(f"`act_averaging={act_averaging}` is not an averaging constant: pass a value "
                             "in (0, 1], or None to observe the absolute min and max.")
        self._ladders = {'weight': _check_ladder('weight', weight_schedule, weight_widths, weight_bits),
                         'act': _check_ladder('act', act_schedule, act_widths, act_bits)}
        self.current_widths = {'weight': weight_bits, 'act': act_bits}
        self._pinned = {'weight': set(), 'act': set()}
        self.fake_quantizer, self.frozen = None, False
        self._installed, self._baked = False, False

    def before_fit(self) -> None:
        "Build the quantizer, parametrize the weights it rounds, and start observing the activations"
        self._check_alone()
        if self._installed:
            raise RuntimeError("This callback is still installed from a fit that did not finish: call "
                               "strip() for the floating-point weights, or bake() to keep the rounding, "
                               "before fitting again.")
        if self._baked: self.fake_quantizer.remove()  # a second fit resumes from the master the first trained
        self.fake_quantizer = FakeQuantizer(self.model or self.learn.model, self.weight_bits,
                                            self.act_bits, self.qscheme, self.symmetric, self.group_size,
                                            self.observer, self.layer_type, self.layer_bits,
                                            self.layer_act_bits)
        self.frozen, self._baked = False, False
        self._install()
        self.current_widths = {'weight': self.weight_bits, 'act': self.act_bits}
        self._pinned = {'weight': self._pin(self.layer_bits), 'act': self._pin(self.layer_act_bits)}
        for axis, sched, ladder in self._scheduled():
            sched.reset()
            self._set_width(axis, ladder[0])   # the fit starts on the coarsest rung, not on the target
        stepping = ', '.join(f'{axis} through {list(ladder)} bits'
                             for axis, _, ladder in self._scheduled())
        print(f'Training through {self.fake_quantizer.spec.label}, weights {self.qscheme}'
              + (f', stepping {stepping}' if stepping else ''))

    def before_batch(self) -> None:
        "Step the scheduled widths, and freeze the activation scales once the fit is `freeze_act_pct` through"
        if not self.training: return
        self._step_widths()
        if self.pct_train >= self.freeze_act_pct: self._freeze_act()

    def after_fit(self) -> None:
        "Bake the rounding in, unless the model was stripped by hand during the fit"
        if self._installed: self.bake()

    def bake(self) -> nn.Module:
        "Round the trained master into an ordinary weight, and leave the model `quantize_model()` leaves"
        if not self._installed:
            raise RuntimeError("Nothing is installed to bake: run a fit with this callback, which "
                               "installs the rounding and bakes it at the end.")
        fq = self.fake_quantizer
        blind = next((n for n, m in fq._named if isinstance(self._rounder(m), _ActObserver)
                      and '_act_scale' not in m._buffers), None)
        if blind is not None:   # refuse before a single weight is written, as `_check_model` does
            raise RuntimeError(f"'{blind}' never saw a training batch, so nothing observed its activation "
                               "range: fit at least one batch, or leave its activations in floating point "
                               "with layer_act_bits.")
        self._freeze_act()  # a threshold a short fit never reached must not leave the scales moving
        for axis, _, ladder in self._scheduled():
            self._set_width(axis, ladder[-1])  # a fit cut short still bakes the width the spec names
        for _, m in fq._named:
            if not _is_parametrized(m): continue
            m.register_buffer('_fp_weight', _master(m).detach().clone(), persistent=False)
            _unparametrize(m, leave_parametrized=True)
        for m, (handle, rounder) in list(fq._act_hooks.items()):
            for name in ('_act_min', '_act_max'):
                if name in m._buffers: delattr(m, name)
            if not isinstance(rounder, _ActObserver): continue
            handle.remove()  # the scales are frozen: from here the post-training rounder reads them
            ptq = _ActRounder(rounder.bits, rounder.symmetric, False)
            fq._act_hooks[m] = (m.register_forward_hook(ptq), ptq)
        fq._calibrated, fq._quantized = True, True
        setattr(fq.model, FAKE_SPEC_ATTR, replace(fq.spec, trained=True,
                                                  weight_widths=self._ladders['weight'],
                                                  act_widths=self._ladders['act']))
        self._installed, self._baked = False, True
        print(f'Baked in {fq.spec.label}: the model holds its rounded weights, and '
              'fake_quantizer.remove() gives the trained floating-point ones back')
        return fq.model

    def strip(self) -> nn.Module:
        "Drop the rounding and keep the floating-point master — the way back from a fit that raised"
        if self.fake_quantizer is None:
            raise RuntimeError("There is nothing to strip: this callback has not started a fit yet.")
        if self._baked:
            raise RuntimeError("This fit is already baked: call fake_quantizer.remove() for the "
                               "floating-point weights it trained.")
        fq = self.fake_quantizer
        for handle, _ in fq._act_hooks.values(): handle.remove()
        fq._act_hooks = {}
        for _, m in fq._named:
            _unparametrize(m)
            for name in ('_act_min', '_act_max', '_act_scale', '_act_zero_point'):
                if name in m._buffers: delattr(m, name)
        self._installed = False
        return fq.model

    def _install(self) -> None:
        "Parametrize every weight this rounds, and hook every activation it observes"
        fq = self.fake_quantizer
        already = next((n for n, m in fq._named if _is_parametrized(m)), None)
        if already is not None:
            raise RuntimeError(f"'{already}' already computes its weight from a parametrization: remove "
                               "it before training through a simulated width.")
        for _, m in fq._named:
            bits = fq._weight_map[m]
            if bits is not None:
                parametrize.register_parametrization(
                    m, 'weight', _FakeQuantWeight(bits, fq.symmetric, fq.qscheme, fq.group_size))
            act_bits = fq._act_map[m]
            if act_bits is not None:
                rounder = (_ActRounder(act_bits, fq.symmetric, True) if fq.observer == 'dynamic'
                           else _ActObserver(act_bits, fq.symmetric, self.act_averaging))
                fq._act_hooks[m] = (m.register_forward_hook(rounder), rounder)
        self._installed = True

    def _rounder(self, m: nn.Module):
        "The hook rounding this module's output, when it rounds one"
        hook = self.fake_quantizer._act_hooks.get(m)
        return hook[1] if hook else None

    def _freeze_act(self) -> None:
        "Stop the observers moving: from here the fit trains on the scales the model will keep"
        for _, rounder in self.fake_quantizer._act_hooks.values():
            if isinstance(rounder, _ActObserver): rounder.frozen = True
        self.frozen = True

    def _scheduled(self):
        "One (axis, schedule, ladder) triple per scheduled axis, and nothing when no width is scheduled"
        for axis, sched in (('weight', self.weight_schedule), ('act', self.act_schedule)):
            if self._ladders[axis] is not None: yield axis, sched, self._ladders[axis]

    def _pin(self, overrides: dict | None) -> set:
        "The modules a per-layer dict named: their width is the one it gave them, all fit"
        by_name = dict(self.fake_quantizer._named)
        return {by_name.get(k) if isinstance(k, str) else k for k in (overrides or {})} - {None}

    @property
    def _final_batch(self) -> bool:
        "Whether this is the fit's last training batch, whose rung the bake keeps"
        return self.epoch == self.n_epoch - 1 and self.iter == self.n_iter - 1

    def _step_widths(self) -> None:
        "Lower each scheduled axis onto the rung its progress selects"
        for axis, sched, ladder in self._scheduled():
            # the rung decides, not `Schedule.changed`, so a schedule shared with another callback that
            # does read it is left exactly as that one expects to find it
            progress = sched.progress(round(self.pct_train, 3))
            # `pct_train` never reaches 1, so the last batch takes the final rung whatever the arithmetic
            bits = ladder[-1] if self._final_batch else _rung(ladder, progress)
            if bits != self.current_widths[axis]: self._set_width(axis, bits)

    def _set_width(self, axis: str, bits: int) -> None:
        "Write one rung onto every rounder the ladder of `axis` moves, and remember it"
        if axis == 'weight': self._set_weight_width(bits)
        else: self._set_act_width(bits)
        self.current_widths[axis] = bits

    def _set_weight_width(self, bits: int) -> None:
        "Round to `bits` every weight on the ladder — the ones `layer_bits` named are not on it"
        for _, m in self.fake_quantizer._named:
            if m in self._pinned['weight'] or not _is_parametrized(m): continue
            for p in m.parametrizations.weight:
                if isinstance(p, _FakeQuantWeight): p.bits = bits

    def _set_act_width(self, bits: int) -> None:
        "Round to `bits` every activation on the ladder, rewriting the scales its observed range defines"
        for m, (_, rounder) in self.fake_quantizer._act_hooks.items():
            if m in self._pinned['act']: continue
            rounder.bits = bits
            # the observed range is width-independent; only the scale it defines has to be rewritten
            if '_act_min' not in m._buffers: continue
            scale, zero = _scale_zero(m._act_min, m._act_max, bits, self.symmetric)
            for name, value in (('_act_scale', scale), ('_act_zero_point', zero)):
                m.register_buffer(name, value, persistent=False)

    def _check_alone(self) -> None:
        "Refuse a fit that also carries `QuantizeCallback`, which swaps the model this one parametrizes"
        from fasterai.quantize.quantize_callback import QuantizeCallback
        if any(isinstance(cb, QuantizeCallback) for cb in self.learn.cbs):
            raise ValueError("QuantizeCallback and FakeQuantizeCallback both rewrite the model being "
                             "trained, and the first swaps out what the second parametrizes: keep one.")
