# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/quantize/quantizer.ipynb.

# %% auto #0
__all__ = ['Quantizer']

# %% ../../nbs/quantize/quantizer.ipynb #80613b7a-9ee9-4729-80e0-a33e6406a83e
import torch
import torch.nn as nn
from fastcore.basics import store_attr
from ..core.precision import QuantSpec, SPEC_ATTR, _resolve_spec
from torch.ao.quantization import QConfig, get_default_qconfig_mapping, get_default_qat_qconfig_mapping
from torch.ao.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx
from torch.ao.quantization.observer import MinMaxObserver, MovingAverageMinMaxObserver
from torch.ao.quantization.fake_quantize import FakeQuantize
from torch.quantization import quantize_dynamic
from torch.ao.quantization.quantization_mappings import get_default_static_quant_module_mappings
from dataclasses import replace
from typing import Any
import warnings
import copy
from tqdm import tqdm

try:
    from torchao.quantization import quantize_, Int8WeightOnlyConfig
    from torchao.quantization import Int8DynamicActivationInt8WeightConfig
    _HAS_TORCHAO = True
    # an import is not enough: the INT4 kernels only fail when one actually runs
    try:
        from torchao.quantization import Int4WeightOnlyConfig
        _m = nn.Linear(128, 128)
        quantize_(_m, Int4WeightOnlyConfig(group_size=128))
        _HAS_INT4 = True
        del _m
    except (ImportError, Exception):
        _HAS_INT4 = False
except ImportError:
    _HAS_TORCHAO = False
    _HAS_INT4 = False

# the recipes whose kernels this environment ships
_TORCHAO_CONFIGS = {}
if _HAS_TORCHAO:
    _TORCHAO_CONFIGS['int8_weight_only'] = Int8WeightOnlyConfig
    _TORCHAO_CONFIGS['int8_dynamic'] = Int8DynamicActivationInt8WeightConfig
if _HAS_INT4:
    _TORCHAO_CONFIGS['int4_weight_only'] = Int4WeightOnlyConfig

_FQN_CONFIG = None          # torchao's {layer name: config} configuration class
_torchao_is_linear = None   # torchao's own "is this a Linear I rewrite?" predicate
_HAS_FQN_CONFIG = False
if _HAS_TORCHAO:
    try:
        from torchao.quantization.quant_api import _is_linear as _torchao_is_linear
        try:
            from torchao.quantization.quant_api import FqnToConfig as _FQN_CONFIG
        except ImportError:  # older torchao shipped the same class under its module-only name
            from torchao.quantization.quant_api import ModuleFqnToConfig as _FQN_CONFIG
        _HAS_FQN_CONFIG = True
    except ImportError:
        pass

_FQN_MISSING = ("A per-layer `weight_bits` dict on backend='torchao' needs a torchao that exposes "
                "`FqnToConfig` (or its older name `ModuleFqnToConfig`). Upgrade torchao, or pass a "
                "single `weight_bits` int.")


def _is_quantized_weight(module: nn.Module) -> bool:
    "Whether torchao replaced this module's weight with one of its own tensor subclasses"
    return type(getattr(module, 'weight', None)).__module__.split('.')[0] == 'torchao'

# %% ../../nbs/quantize/quantizer.ipynb #9aa89c26
try:
    from torch.ao.quantization.quantize_pt2e import prepare_pt2e, prepare_qat_pt2e, convert_pt2e
    from torch.ao.quantization.quantizer import QuantizationSpec, SharedQuantizationSpec
    # private alias: `Quantizer` is the name of THIS module's class
    from torch.ao.quantization.quantizer import Quantizer as _TorchQuantizer
    from torch.ao.quantization.quantizer.xnnpack_quantizer import (XNNPACKQuantizer,
                                                                   get_symmetric_quantization_config)
    from torch.ao.quantization.quantizer.xnnpack_quantizer_utils import QuantizationConfig
    from torch.ao.quantization.observer import (HistogramObserver, PerChannelMinMaxObserver,
                                                MovingAveragePerChannelMinMaxObserver)
    from torch.ao.quantization.fake_quantize import FusedMovingAvgObsFakeQuantize
    from torch.ao.quantization import move_exported_model_to_train, move_exported_model_to_eval
    _HAS_PT2E = True
except ImportError:
    _HAS_PT2E = False
    # so the placement wrapper below can be DEFINED on a build with no pt2e flow
    _TorchQuantizer = object

# %% ../../nbs/quantize/quantizer.ipynb #ff65b476
import types

_INT8_SYM = dict(dtype=torch.int8, quant_min=-127, quant_max=127, is_dynamic=False)
_OBS_EPS = 2 ** -12  # the resolution torch's own presets give the observers and fake-quantizers below
_PT2E_MISSING = "The pt2e backend requires torch.ao.quantization.quantize_pt2e (PyTorch >= 2.1)."


# The two builders below stay unannotated: their types only exist when `_HAS_PT2E`.
def _symmetric_pt2e_config(
    per_channel: bool = True,
    is_qat: bool = False,
):
    "Build a fully-symmetric INT8 `QuantizationConfig` (zero_point == 0 on every quantized tensor)"
    # The stock `get_symmetric_quantization_config()` preset is symmetric for the *weights* only.
    if is_qat:
        activation_observer = weight_observer = MovingAverageMinMaxObserver
        per_channel_weight_observer = MovingAveragePerChannelMinMaxObserver
    else:
        activation_observer = HistogramObserver.with_args(eps=_OBS_EPS)
        weight_observer = MinMaxObserver
        per_channel_weight_observer = PerChannelMinMaxObserver

    def _spec(qscheme, observer, **kwargs):
        # QAT trains THROUGH the quantizer: fake-quantize rounds and passes the gradient
        ctr = FusedMovingAvgObsFakeQuantize.with_args(observer=observer, eps=_OBS_EPS) if is_qat \
            else observer
        return QuantizationSpec(**_INT8_SYM, qscheme=qscheme, observer_or_fake_quant_ctr=ctr, **kwargs)

    activation = _spec(torch.per_tensor_symmetric, activation_observer)
    if per_channel:
        weight = _spec(torch.per_channel_symmetric, per_channel_weight_observer, ch_axis=0)
    else:
        weight = _spec(torch.per_tensor_symmetric, weight_observer)
    return QuantizationConfig(input_activation=activation, output_activation=activation,
                              weight=weight, bias=None, is_qat=is_qat)


_ANNOTATION = 'quantization_annotation'  # torch's own key for the annotation it leaves on a node

_ADD_TARGETS = (torch.ops.aten.add.Tensor, torch.ops.aten.add_.Tensor)
_CONV_TARGETS = (torch.ops.aten.conv1d.default, torch.ops.aten.conv2d.default,
                 torch.ops.aten.conv3d.default, torch.ops.aten.convolution.default)
# PTQ fuses conv+bn before annotating, QAT after; the observer sits on the ReLU
_CONV_EPILOGUE_TARGETS = (torch.ops.aten.batch_norm.default, torch.ops.aten.relu.default,
                          torch.ops.aten.relu_.default)
_MAX_CONV_EPILOGUE = 2  # conv -> bn -> relu: two epilogue nodes, plus the convolution itself (the +1 below)


def _node_annotation(node):
    "The quantization annotation torch left on `node`, or None when it left none"
    return node.meta.get(_ANNOTATION)


def _shared_references(graph_module) -> set:
    "Every edge or node a `SharedQuantizationSpec` points at — a qspec no pass may take away"
    referenced = set()
    for node in graph_module.graph.nodes:
        annotation = _node_annotation(node)
        if annotation is None: continue
        for spec in (*annotation.input_qspec_map.values(), annotation.output_qspec):
            if isinstance(spec, SharedQuantizationSpec): referenced.add(spec.edge_or_node)
    return referenced


def _conv_partition_root(addend):
    "The convolution `addend` is the output of, walked back through bn/relu; None when there is none"
    node = addend
    for _ in range(_MAX_CONV_EPILOGUE + 1):
        if node.op != 'call_function': return None
        if node.target in _CONV_TARGETS: return node
        if node.target not in _CONV_EPILOGUE_TARGETS: return None
        producer = node.args[0] if node.args else None
        if not isinstance(producer, torch.fx.Node) or len(producer.users) != 1: return None
        node = producer
    return None


def _is_conv_addend(addend, add_node, annotation, referenced) -> bool:
    "Whether `addend` is the residual branch of `add_node`: a single-user convolution partition"
    if not isinstance(addend, torch.fx.Node) or addend not in annotation.input_qspec_map: return False
    if len(addend.users) != 1: return False  # its result reaches something besides this add
    own = _node_annotation(addend)
    # a shared or derived spec is defined against another tensor, not this edge
    if own is None or not isinstance(own.output_qspec, QuantizationSpec): return False
    if addend in referenced or (addend, add_node) in referenced: return False
    return _conv_partition_root(addend) is not None


def _conv_add_edges(
    graph_module,
) -> list:
    "Every (add node, residual addend) pair `qdq_placement='skip_conv_add'` leaves unquantized"
    referenced = _shared_references(graph_module)
    edges = []
    for node in graph_module.graph.nodes:
        if node.op != 'call_function' or node.target not in _ADD_TARGETS: continue
        annotation = _node_annotation(node)
        if annotation is None: continue
        # Never both edges of one add, which would leave it with no quantized input: the FIRST wins.
        match = next((a for a in node.args[:2]
                      if _is_conv_addend(a, node, annotation, referenced)), None)
        if match is not None: edges.append((node, match))
    return edges


def _skip_conv_add_annotation(
    graph_module,
) -> tuple[int, int]:
    "Leave every conv→add edge of the graph unquantized; report (edges cleared, additions seen)"
    edges = _conv_add_edges(graph_module)
    n_adds = sum(1 for node in graph_module.graph.nodes
                 if node.op == 'call_function' and node.target in _ADD_TARGETS)
    for add_node, addend in edges:
        del _node_annotation(add_node).input_qspec_map[addend]
        _node_annotation(addend).output_qspec = None
    return len(edges), n_adds


class _PlacementQuantizer(_TorchQuantizer):
    "A pt2e quantizer that annotates like `inner`, then moves the Q/DQ pairs where `placement` says"
    # Wraps XNNPACKQuantizer rather than subclassing it: `prepare_pt2e` reads only the four members below.
    def __init__(self,
                 inner,
                 placement: str,
    ):
        self.inner, self.placement = inner, placement
        self.n_adds = self.n_skipped = 0  # read back by `_prepare_pt2e`, which refuses a zero match

    def transform_for_annotation(self, model):
        "Whatever `inner` does to the graph before it is annotated"
        return self.inner.transform_for_annotation(model)

    def annotate(self, model):
        "Annotate with `inner`, then take the Q/DQ pairs off the edges `placement` names"
        # inner.annotate runs propagate_annotation last, so this pass sees the shared specs too
        model = self.inner.annotate(model)
        self.n_skipped, self.n_adds = _skip_conv_add_annotation(model)
        return model

    def validate(self, model) -> None:
        "Whatever `inner` checks on the annotated graph"
        return self.inner.validate(model)

    @property
    def prepare_obs_or_fq_callback(self):
        "`inner`'s callback, read as an attribute the way `prepare_pt2e` reads it"
        return self.inner.prepare_obs_or_fq_callback


def _pt2e_quantizer(
    spec: QuantSpec | None = None,
):
    "Build the pt2e quantizer that applies `spec`"
    if spec is None: spec = _resolve_spec('pt2e')
    per_channel = spec.qscheme == 'per_channel'
    is_qat = spec.method == 'qat'
    if spec.symmetric:
        config = _symmetric_pt2e_config(per_channel, is_qat)
    else:
        config = get_symmetric_quantization_config(is_per_channel=per_channel, is_qat=is_qat)
    quantizer = XNNPACKQuantizer().set_global(config)
    # `getattr`: a spec pickled before this field existed unpickles with it UNSET
    placement = getattr(spec, 'qdq_placement', None)
    if placement in (None, 'per_op'): return quantizer
    return _PlacementQuantizer(quantizer, placement)


def _model_device(model: nn.Module) -> torch.device:
    "Device on which `model` holds its tensors (CPU when it holds none)"
    tensor = next(model.parameters(), None)
    if tensor is None: tensor = next(model.buffers(), None)
    return tensor.device if tensor is not None else torch.device('cpu')


def _check_placement_applied(
    quantizer,
    spec: QuantSpec,
    verbose: bool,
) -> None:
    "Refuse a Q/DQ placement that matched nothing, so that a recorded placement is one that ran"
    if not isinstance(quantizer, _PlacementQuantizer): return  # 'per_op': nothing to move
    if not quantizer.n_skipped:
        raise ValueError(
            f"qdq_placement='{spec.qdq_placement}' found no conv→add edge to leave unquantized in this "
            f"model: it has {quantizer.n_adds} add node(s), none of them fed by a single-user "
            "convolution partition. It is a residual-network placement — a block whose branch ends in "
            "a convolution feeding the addition. Use qdq_placement='per_op' for this model.")
    if verbose:
        print(f"pt2e: qdq_placement='{spec.qdq_placement}' left {quantizer.n_skipped} of "
              f"{quantizer.n_adds} addition(s) reading a convolution at accumulator precision")


def _prepare_pt2e(
    model: nn.Module,
    example_input: torch.Tensor,
    spec: QuantSpec | None = None,
    verbose: bool = False,
) -> nn.Module:
    "Capture `model` with `torch.export` and insert the INT8 observers `spec` asks for"
    if not _HAS_PT2E:
        raise ImportError(_PT2E_MISSING)
    if spec is None: spec = _resolve_spec('pt2e')
    # `torch.export` captures a STATIC batch size, the one of `example_input`
    example_input = example_input.to(_model_device(model))  # capture where the model already lives
    try:
        exported = torch.export.export(model.eval(), (example_input,))
    except Exception as e:
        raise RuntimeError(
            "pt2e quantization needs a model that torch.export can capture as a single graph. "
            f"Capture failed with {type(e).__name__}: {e}") from e
    # QAT inserts fake-quantize modules where PTQ inserts observers
    prepare = prepare_qat_pt2e if spec.method == 'qat' else prepare_pt2e
    quantizer = _pt2e_quantizer(spec)
    prepared = prepare(exported.module(), quantizer)
    _check_placement_applied(quantizer, spec, verbose)
    return prepared


def _convert_pt2e(
    prepared: nn.Module,
) -> nn.Module:
    "Freeze the observed scales into a quantized graph"
    if not _HAS_PT2E:
        raise ImportError(_PT2E_MISSING)
    return convert_pt2e(prepared)


def _exported_train(self, mode: bool = True) -> nn.Module:
    "`.train()` for a module captured by torch.export, which refuses the eager one"
    return move_exported_model_to_train(self) if mode else move_exported_model_to_eval(self)


def _exported_eval(self) -> nn.Module:
    "`.eval()` for a module captured by torch.export, which refuses the eager one"
    return move_exported_model_to_eval(self)


def _bind_exported_modes(
    graph_module: nn.Module,
) -> nn.Module:
    "Give an exported graph module a working `.train()`/`.eval()`, so a training loop can drive it"
    # Instance methods, so that a deepcopy of the module rebinds them to the copy.
    if not _HAS_PT2E:
        raise ImportError(_PT2E_MISSING)
    graph_module.train = types.MethodType(_exported_train, graph_module)
    graph_module.eval = types.MethodType(_exported_eval, graph_module)
    return graph_module


def _batch_input(batch: Any) -> Any:
    "Input part of a dataloader batch, whether it is a tensor or an (input, target) tuple"
    if isinstance(batch, (list, tuple)) and len(batch) >= 1: batch = batch[0]
    if hasattr(batch, 'data'): batch = batch.data
    return batch


def _first_input(dataloader: Any) -> torch.Tensor:
    "First input tensor of `dataloader` (a fastai `DataLoaders`, a torch loader, or any iterable of batches)"
    batch = dataloader.one_batch() if hasattr(dataloader, 'one_batch') else next(iter(dataloader))
    inputs = _batch_input(batch)
    if not isinstance(inputs, torch.Tensor):
        raise TypeError(f"Calibration data must yield tensors, got {type(inputs).__name__}.")
    return inputs

# %% ../../nbs/quantize/quantizer.ipynb #fb1fd84a-dcf6-4ec5-966e-6fdd01e1d19b
import contextlib

_GRAMMAR_ARGS = ('weight_bits', 'act_bits', 'qscheme', 'group_size', 'symmetric',
                 'qdq_placement')  # the precision arguments
_CONV_TYPES = (nn.Conv1d, nn.Conv2d, nn.Conv3d)
# Embedding/EmbeddingBag are dropped: quantizing them needs an observer this flow never sets.
_NO_DEFAULT_OBSERVER = (nn.Embedding, nn.EmbeddingBag)
_LEGACY_QUANT_TYPES = tuple(t for t in get_default_static_quant_module_mappings()
                            if isinstance(t, type) and issubclass(t, nn.Module)
                            and not issubclass(t, _NO_DEFAULT_OBSERVER))


def _preview(names, limit: int = 6) -> str:
    "The first few of a list of layer names, so an error stays readable on a big model"
    return ', '.join(names[:limit]) + (', ...' if len(names) > limit else '')

class Quantizer:
    def __init__(self, 
                 backend: str = "x86",                   # Target backend: 'x86', 'qnnpack', 'fbgemm', 'onednn', 'torchao', or 'pt2e'
                 method: str = "static",                 # Method: 'static', 'dynamic', 'qat', 'int8_weight_only', 'int8_dynamic'
                 qconfig_mapping: dict | None = None,    # Optional custom quantization config (legacy backends only)
                 custom_configs: dict | None = None,
                 use_per_tensor: bool = False,           # Force per-tensor quantization (legacy backends only)
                 verbose: bool = False,
                 *,
                 weight_bits: int | dict | None = None,  # Weight width, or {layer_name: width}; None = the backend's own
                 act_bits: int | None = None,            # Activation width (16 leaves them in floating point); None = the backend's own
                 qscheme: str | None = None,             # Weight axis: 'per_tensor', 'per_channel' or 'per_group'; None = the backend's own
                 group_size: int | None = None,          # Weights sharing one scale (qscheme='per_group')
                 symmetric: bool | None = None,          # Force a zero-point of 0 everywhere; None = the backend's own
                 qdq_placement: str | None = None,       # Where the Q/DQ pairs sit: 'per_op', 'skip_conv_add' ('pt2e' only); None = the backend's own
    ):
        """Initialize a quantizer with specified backend and options.

        `qdq_placement='skip_conv_add'` is opt-in and changes the arithmetic: it leaves the residual
        branch's convolution feeding its addition without a Q/DQ pair, so that result arrives at
        accumulator precision. What a runtime then does with that graph is the runtime's own
        property, and the effect on a TRAINED model's accuracy is UNMEASURED here."""
        store_attr()
        self._custom_mapping = qconfig_mapping is not None
        if self._custom_mapping and self._asked_precision():
            raise ValueError("`qconfig_mapping` replaces the whole quantization configuration, so the "
                             "precision arguments cannot be applied on top of it. Keep one of the two.")
        self.spec = _resolve_spec(backend, method, weight_bits=weight_bits, act_bits=act_bits,
                                  qscheme=qscheme, group_size=group_size, symmetric=symmetric,
                                  qdq_placement=qdq_placement, use_per_tensor=use_per_tensor)
        self.method = self.spec.method  # on torchao, naming a precision names the recipe that applies it

        if self.spec.layer_bits and self.method == 'dynamic':
            raise ValueError(
                "method='dynamic' quantizes every eligible layer at once: it cannot honor a per-layer "
                "`weight_bits` dict. The methods that can: 'static', 'qat'.")

        if backend == 'torchao':
            if not _HAS_TORCHAO:
                raise ImportError("torchao backend requires torchao. Install with: pip install torchao")
            if self.method not in _TORCHAO_CONFIGS:
                raise ValueError(f"torchao method '{self.method}' is not available in this environment "
                                 f"(its kernels are missing). Available: {list(_TORCHAO_CONFIGS)}")
            if self.spec.layer_bits and not _HAS_FQN_CONFIG: raise ImportError(_FQN_MISSING)
            return

        if backend == 'pt2e':
            if not _HAS_PT2E:
                raise ImportError(_PT2E_MISSING)
            return

        if qconfig_mapping is None:
            if method == "qat":
                self.qconfig_mapping = get_default_qat_qconfig_mapping(backend)
            else:
                self.qconfig_mapping = get_default_qconfig_mapping(backend)
            # The flag REPLACES the default mapping, so only an explicit request may flip it.
            if qscheme == 'per_tensor': self.use_per_tensor = True
            if self.use_per_tensor:
                self._update_qconfig_for_per_tensor()
            for name, bits in (self.spec.layer_bits or {}).items():
                if bits == 16: self.qconfig_mapping.set_module_name(name, None)
        else:
            self.qconfig_mapping = qconfig_mapping

    def _asked_precision(self) -> bool:
        "Whether the caller named any part of the precision grammar"
        return self.use_per_tensor or any(getattr(self, a) is not None for a in _GRAMMAR_ARGS)

    def _covering_names(self, name: str) -> list[str]:
        "The dict entries that can apply to `name`: itself, then the modules containing it"
        # the FX flow resolves a name by walking parents; torchao matches a name exactly
        parts = name.split('.')
        if self.backend == 'torchao': return [name]
        return ['.'.join(parts[:i]) for i in range(len(parts), 0, -1)]

    def _layer_width(self, name: str) -> int:
        "Width `name` ends at: 16 when the dict names it or a module containing it, else the uniform width"
        # Not "most specific wins": only a 16 reaches the mapping; `_check_model` refuses an 8 under one.
        bits = self.spec.layer_bits or {}
        if any(bits.get(n) == 16 for n in self._covering_names(name)): return 16
        return self.spec.weight_bits

    def _quantizable_names(self, model: nn.Module) -> list[str]:
        "Names of the layers this backend rewrites — the only ones a per-layer width can be honored on"
        if self.backend == 'torchao':
            # torchao's OWN predicate, so a request selects exactly the layers its uniform path would.
            if _torchao_is_linear is None:  # a torchao that does not expose its filter: fall back
                return [n for n, m in model.named_modules() if isinstance(m, nn.Linear)]
            return [n for n, m in model.named_modules() if _torchao_is_linear(m, n)]
        return [n for n, m in model.named_modules() if isinstance(m, _LEGACY_QUANT_TYPES)]

    def _nameable_names(self, quantizable: list[str]) -> set[str]:
        "Names a per-layer width may carry: a layer this backend rewrites, or a module holding some"
        names = set(quantizable)
        if self.backend == 'torchao': return names
        for n in quantizable:
            parts = n.split('.')
            names.update('.'.join(parts[:i]) for i in range(1, len(parts)))
        return names

    def _check_model(self, model: nn.Module) -> None:
        "Refuse a model the resolved precision cannot be applied to, before it is touched"
        if not (self.spec.layer_bits or self.backend == 'torchao'): return
        named = dict(model.named_modules())
        missing = [n for n in (self.spec.layer_bits or {}) if n not in named]
        if missing:
            raise ValueError(f"`weight_bits` names layers this model does not have: {missing}. "
                             "Use the names `model.named_modules()` reports.")
        quantizable = self._quantizable_names(model)
        if self.backend == 'torchao':
            convs = [n for n, m in named.items() if isinstance(m, _CONV_TYPES)]
            if not quantizable:
                skipped = [n for n, m in named.items() if isinstance(m, nn.Linear)]
                why = (f"the only one(s) it has are Linear layers torchao skips ({_preview(skipped)})"
                       if skipped else f"this model has none ({len(convs)} convolution(s))")
                raise ValueError(
                    f"backend='torchao' rewrites Linear layers only, and {why}: quantization would "
                    "leave every layer in floating point. Use backend='x86' (or 'pt2e') for a "
                    "convolutional model.")
            if self.spec.qscheme == 'per_group' and convs:
                raise ValueError(
                    f"per-group quantization rewrites Linear layers only, and this model has "
                    f"{len(convs)} convolution(s) ({_preview(convs, 3)}) that would silently stay in "
                    "floating point. Quantize a convolutional model per channel (qscheme='per_channel').")
        if not self.spec.layer_bits: return
        nameable = self._nameable_names(quantizable)
        elsewhere = [n for n in self.spec.layer_bits if n not in nameable]
        if elsewhere:
            if self.backend == 'torchao':
                rewrites = ("Linear layers only, and never `MultiheadAttention.out_proj` (torchao's own "
                            "filter skips it)")
            else:
                rewrites = ("the module types its default qconfig mapping rewrites, and the modules "
                            "holding them")
            raise ValueError(
                f"`weight_bits` names layers backend='{self.backend}' does not quantize: {elsewhere}. "
                f"It rewrites {rewrites}, so a width on any other module would be ignored. The "
                f"{len(quantizable)} layer(s) it can be given: {_preview(quantizable)}.")
        shadowed = [n for n, b in self.spec.layer_bits.items() if b == 8 and self._layer_width(n) == 16]
        if shadowed:
            raise ValueError(
                f"`weight_bits` asks for 8 on {shadowed}, inside a module it also leaves at 16: the FX "
                "flow honors the outer 16, so the 8 would be ignored. Drop the outer 16 and name the "
                "layers to keep in floating point one by one.")
        if quantizable and all(self._layer_width(n) == 16 for n in quantizable):
            raise ValueError(
                f"`weight_bits` leaves all {len(quantizable)} layer(s) backend='{self.backend}' "
                "quantizes in floating point: `quantize` would hand back an unquantized model "
                "carrying a quantized model's provenance. Name at least one layer 8, or do not "
                "quantize this model.")

    def _tag(self, quantized: nn.Module, source: nn.Module) -> nn.Module:
        "Record on the quantized model which precision cell produced it"
        # `is not`: the legacy paths hand the SOURCE model back when they fail
        if quantized is not source and not self._custom_mapping: setattr(quantized, SPEC_ATTR, self.spec)
        return quantized

    @contextlib.contextmanager
    def _quantized_engine(self):
        "Context manager to temporarily set the quantization backend engine."
        old_engine = torch.backends.quantized.engine
        torch.backends.quantized.engine = self.backend
        try:
            yield
        finally:
            torch.backends.quantized.engine = old_engine

    def _update_qconfig_for_per_tensor(self):
        "Replace per-channel with per-tensor quantization to avoid conversion issues"
        if self.verbose:
            print("Using per-tensor quantization instead of per-channel")
            
        if self.method == "qat":            
            weight_observer = MinMaxObserver.with_args(
                dtype=torch.qint8,
                qscheme=torch.per_tensor_symmetric,
                quant_min=-128,
                quant_max=127
            )
            activation_observer = MovingAverageMinMaxObserver.with_args(
                averaging_constant=0.01,
                quant_min=0,
                quant_max=255
            )
            per_tensor_qconfig = QConfig(
                activation=FakeQuantize.with_args(
                    observer=activation_observer, quant_min=0, quant_max=255),
                weight=FakeQuantize.with_args(
                    observer=weight_observer, quant_min=-128, quant_max=127))
        else:
            activation_observer = MinMaxObserver.with_args(
                dtype=torch.quint8, qscheme=torch.per_tensor_affine, quant_min=0, quant_max=255)
            weight_observer = MinMaxObserver.with_args(
                dtype=torch.qint8, qscheme=torch.per_tensor_symmetric, quant_min=-128, quant_max=127)
            per_tensor_qconfig = QConfig(activation=activation_observer, weight=weight_observer)
            
        self.qconfig_mapping.global_qconfig = per_tensor_qconfig

    def _apply_custom_configs(self):
        "Apply custom quantization configurations to specific modules"
        if not self.custom_configs: return
        for module_name, config in self.custom_configs.items():
            if self.verbose: print(f"Setting custom config for {module_name}")
            self.qconfig_mapping.set_module_name(module_name, config)
    
    def _prepare_model(self, model, example_inputs):
        "Prepare model for quantization based on selected method"
        model = model.cpu()
        model = model.train() if self.method == "qat" else model.eval()
        
        try:
            with self._quantized_engine():
                if self.method == "static":
                    return prepare_fx(model, self.qconfig_mapping, example_inputs)
                elif self.method == "qat":
                    return prepare_qat_fx(model, self.qconfig_mapping, example_inputs)
                else:
                    raise ValueError(f"Unknown quantization method: {self.method}")
        except Exception as e:
            raise RuntimeError(f"Error preparing model for quantization: {e}") from e
    
    def _calibrate_model(self, model, dataloader, max_samples=None, device='cpu'):
        "Calibrate the model on CPU (PyTorch quantization is CPU-only)."
        try: model.eval()
        except NotImplementedError: pass  # an exported graph module is already in inference mode
        device = torch.device(device)
        model = model.to(device)
        
        num_samples = getattr(dataloader, 'n', None)
        if max_samples is not None and num_samples is not None:
            num_samples = min(num_samples, max_samples)
        
        data_iter = dataloader if not self.verbose else tqdm(
            dataloader, desc="Calibrating", total=num_samples//dataloader.bs if num_samples else None)
        
        samples_seen = 0
        with torch.no_grad():
            for i, batch in enumerate(data_iter):
                inputs = _batch_input(batch)
                if isinstance(inputs, (list, tuple)):
                    inputs = [x.to(device) if isinstance(x, torch.Tensor) else x for x in inputs]
                else:
                    inputs = inputs.to(device)
                model(inputs)
                batch_size = inputs.shape[0] if isinstance(inputs, torch.Tensor) else inputs[0].shape[0]
                samples_seen += batch_size
                if max_samples is not None and samples_seen >= max_samples: break
    
    def _quantize_dynamic(self, model):
        "Quantize a model with dynamic quantization"
        try:
            model_copy = copy.deepcopy(model).cpu().eval()
            qconfig_spec = {nn.Linear, nn.LSTM, nn.GRU, nn.RNN}
            with self._quantized_engine():
                return quantize_dynamic(model_copy, qconfig_spec=qconfig_spec, dtype=torch.qint8, inplace=False)
        except Exception as e:
            print(f"Dynamic quantization failed with error: {e}")
            return model

    def _torchao_config(self):
        "torchao configuration for the resolved precision"
        config = _TORCHAO_CONFIGS[self.method]
        return config(group_size=self.spec.group_size) if self.spec.qscheme == 'per_group' else config()

    def _torchao_fqn_config(self, model: nn.Module):
        "One torchao entry per Linear layer: the shared config where the width is 8, `None` where it is 16"
        # EXPLICIT expansion, one entry per layer: torchao's `_default` key is deprecated.
        config = self._torchao_config()
        entries = {n: None if self._layer_width(n) == 16 else config
                   for n in self._quantizable_names(model)}
        return _FQN_CONFIG(entries)  # positional: older torchao names this field `module_fqn_to_config`

    def _quantize_torchao(self, model):
        "Quantize a model using torchao backend"
        model = copy.deepcopy(model).eval()
        per_layer = bool(self.spec.layer_bits)  # `__init__` refused this without the torchao it needs
        config = self._torchao_fqn_config(model) if per_layer else self._torchao_config()
        if self.verbose:
            if per_layer:
                names = self._quantizable_names(model)
                floats = [n for n in names if self._layer_width(n) == 16]
                print(f"torchao: applying {self.method} to {len(names) - len(floats)}/{len(names)} Linear "
                      f"layers ({len(floats)} left in floating point: {', '.join(floats) or 'none'})")
            else:
                print(f"torchao: applying {self.method} ({type(config).__name__})")
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            try:
                # `quantize_` refuses a per-layer configuration together with ANY filter
                if per_layer: quantize_(model, config, filter_fn=None)
                else: quantize_(model, config)
            except ImportError as e:
                raise ImportError(f"torchao method '{self.method}' requires additional dependencies: {e}")
        if self.verbose:
            n = sum(1 for m in model.modules() if _is_quantized_weight(m))
            print(f"torchao: quantized {n} layers")
        return model

    def _quantize_pt2e(self, model, calibration_dl, max_calibration_samples, device):
        "Quantize a model with the pt2e flow: INT8 in the precision the spec asks for"
        if self.method != "static":
            raise ValueError(f"pt2e backend does not support method='{self.method}'. "
                             "`Quantizer.quantize` runs method='static' (post-training quantization on "
                             "calibration data); pt2e QAT happens inside a training loop, so it is run "
                             "by QuantizeCallback(backend='pt2e').")
        if calibration_dl is None:
            raise ValueError("pt2e backend requires calibration_dl: static quantization needs calibration data.")

        if self.verbose: print("pt2e: capturing the model with torch.export")
        prepared = _prepare_pt2e(model, _first_input(calibration_dl), self.spec, verbose=self.verbose)

        if self.verbose: print(f"pt2e: calibrating with up to {max_calibration_samples} samples")
        self._calibrate_model(prepared, calibration_dl, max_samples=max_calibration_samples, device=device)

        if self.verbose: print("pt2e: converting to a quantized graph")
        return _convert_pt2e(prepared)

    def quantize(self, 
                model: nn.Module,
                calibration_dl: Any = None,              # Dataloader for calibration (required by 'static', 'qat' and 'pt2e')
                max_calibration_samples: int = 100,
                device: str | torch.device = 'cpu'
    ) -> nn.Module:
        "Quantize a model using the specified backend and method."
        self._check_model(model)

        if self.backend == 'torchao':
            return self._tag(self._quantize_torchao(model), model)

        # self-contained: a failure surfaces instead of falling through to the legacy flow below
        if self.backend == 'pt2e':
            return self._tag(self._quantize_pt2e(model, calibration_dl, max_calibration_samples, device), model)

        if self.method == "dynamic":
            if self.verbose: print(f"Performing dynamic quantization with {self.backend} backend")
            self._apply_custom_configs()
            return self._tag(self._quantize_dynamic(model), model)
        
        self._apply_custom_configs()
        example_batch = _first_input(calibration_dl)
        
        try:
            if self.verbose: print(f"Preparing model for {self.method} quantization with {self.backend} backend")
            model_prepared = self._prepare_model(model, example_batch.cpu())
            
            if self.method in ["static", "qat"]:
                if self.verbose: print(f"Calibrating with up to {max_calibration_samples} samples")
                self._calibrate_model(model_prepared, calibration_dl, max_samples=max_calibration_samples, device=device)
            
            if self.verbose: print("Converting to quantized model")
            try:
                with self._quantized_engine():
                    quantized_model = convert_fx(model_prepared)
            except RuntimeError as e:
                if "Unsupported qscheme: per_channel_affine" in str(e) and not self.use_per_tensor:
                    if self.verbose: print("Encountered per_channel_affine error, retrying with per-tensor")
                    self.use_per_tensor = True
                    self._update_qconfig_for_per_tensor()
                    # the spec follows the retry: the provenance must describe what actually ran
                    self.spec = replace(self.spec, qscheme='per_tensor')
                    return self.quantize(model, calibration_dl, max_calibration_samples, device)
                else:
                    raise e
            
            if self.verbose: print("Quantization complete")
            return self._tag(quantized_model, model)
            
        except Exception as e:
            print(f"Error during quantization: {e}")
            if self.verbose:
                import traceback
                traceback.print_exc()
            return model
