# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/prune/prune_callback.ipynb.

# %% auto #0
__all__ = ['PruneCallback']

# %% ../../nbs/prune/prune_callback.ipynb #7d58c624
from fastai.vision.all import *
from fastai.callback.all import *
from .pruner import *
from .pruner import _check_pruning_ratio   # private: one shared percent validator
from ..core.criteria import *
from ..core.schedule import *

import torch
import torch.nn as nn
import torch.nn.functional as F

# %% ../../nbs/prune/prune_callback.ipynb #50598138-7d55-4774-b711-114c1c42dce8
class PruneCallback(Callback):
    def __init__(self,
                 pruning_ratio,  # Target pruning ratio in percent (40 = 40% of channels/filters), or dict[layer_name, percent] for per-layer targets, where 0 = skip this layer (requires context='local')
                 schedule,       # When to prune, from `fasterai.core.schedule` (e.g. one_shot, agp)
                 context,        # 'local' (per-layer) or 'global' (across the whole model); per-layer dict requires 'local'
                 criteria,       # How to select filters to prune, from `fasterai.core.criteria`
                 *args,
                 **kwargs
    ):
        store_attr()
        self.sparsity_levels = []
        self._is_per_layer = False
        self._ratio_fraction = None   # 0-1 form of a scalar target, from the ONE validator
        self.extra_args = args
        self.extra_kwargs = kwargs
        # Fail at construction, not ten minutes into a fit
        self._validate_pruning_ratio()

    def _build_pruning_schedule(self, sched_func):
        "Create a schedule function compatible with torch-pruning's Pruner"
        start_val, end_val = self.schedule.start_val, self.schedule.end_val
        def scheduler(pruning_ratio, steps, start=start_val, end=end_val):
            return [
                sched_func(start, end, i / float(steps)) * pruning_ratio
                for i in range(steps + 1)
            ]
        return scheduler

    def _validate_pruning_ratio(self) -> None:
        "Validate pruning_ratio (a PERCENT), supporting both a single value and a per-layer dict"
        self._is_per_layer = isinstance(self.pruning_ratio, dict)
        if self._is_per_layer:
            # Per-layer targets compare each layer independently — global context is incompatible
            if self.context != 'local':
                raise ValueError("Per-layer pruning_ratio dict requires context='local' "
                                 "(global context compares importance across layers).")
            # `Pruner._resolve_pruning_ratio_dict` converts each value; here we only validate.
            # allow_zero: an explicit 0% target means "leave this layer alone".
            for layer, ratio in self.pruning_ratio.items():
                _check_pruning_ratio(ratio, layer=layer, allow_zero=True)
        else:
            # Keep the fraction the validator computed: this callback never divides by 100 itself
            self._ratio_fraction = _check_pruning_ratio(self.pruning_ratio)

    def before_fit(self) -> None:
        "Setup pruner before training"
        n_batches_per_epoch = len(self.learn.dls.train)
        total_training_steps = n_batches_per_epoch * self.learn.n_epoch
        self._validate_pruning_ratio()

        self.example_inputs, _ = self.learn.dls.one_batch()

        # Build schedule function for torch-pruning compatibility
        pruning_schedule = self._build_pruning_schedule(self.schedule.sched_func)
        # sparsity_levels (for logging) tracks a single global ratio as a 0-1 fraction; for
        # per-layer dicts torch-pruning schedules each layer independently, so there is no
        # single level.
        self.sparsity_levels = ([] if self._is_per_layer
                                else pruning_schedule(self._ratio_fraction, total_training_steps))

        self.pruner = Pruner(
            self.learn.model,
            criteria=self.criteria,
            pruning_ratio=self.pruning_ratio,   # a percent — Pruner owns the conversion
            context=self.context,
            iterative_steps=total_training_steps, 
            schedule=pruning_schedule,
            *self.extra_args, 
            **self.extra_kwargs
        )
        
    def before_step(self) -> None:
        "Apply pruning before optimizer step"
        if self.training: 
            self.pruner.prune_model()

    def after_epoch(self) -> None:
        "Log the pruning ratio reached after each epoch"
        if self._is_per_layer:
            print(f'Pruning {len(self.pruning_ratio)} layers to per-layer targets (epoch {self.epoch})')
            return
        completed_steps = (self.epoch + 1) * len(self.learn.dls.train)
        # Bounds check for sparsity_levels access
        if completed_steps > 0 and completed_steps <= len(self.sparsity_levels):
            current_ratio = self.sparsity_levels[completed_steps - 1]
            print(f'Pruning ratio at the end of epoch {self.epoch}: {current_ratio*100:.2f}%')
