# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/prune/pruner.ipynb.

# %% auto #0
__all__ = ['Pruner']

# %% ../../nbs/prune/pruner.ipynb #e1b7a541
import warnings
import torch
import torch.nn as nn
import torch_pruning as tp
from torch_pruning.pruner import function

from fastcore.basics import store_attr
from ..core.criteria import *
from ..core.parametrize import _is_parametrized
from ..core.ratio import as_fraction
from fastai.vision.all import *


from torch_pruning.pruner.algorithms.scheduler import linear_scheduler
from torch.fx import symbolic_trace

# %% ../../nbs/prune/pruner.ipynb #7d1d9daa
class _GroupNormPruner(tp.pruner.GroupNormPruner):
    "`GroupNormPruner` restricted to the groups this pruner will prune, skipping constant-importance ones"
    _skipped = None  # groups skipped by the current `regularize`, None outside it

    def _targeted(self, group):
        # same lookup as `BasePruner._prune`: the first out-channel layer with its own ratio decides, else the default ratio
        m = next((m for dep, _ in group for m, fn in ((dep.source.module, dep.trigger), (dep.target.module, dep.handler))
                  if m in self._layer_to_scope and self.DG.is_out_channel_pruning_fn(fn)), group[0].dep.target.module)
        return self.get_target_pruning_ratio(m, step=self.iterative_steps) > 0

    def estimate_importance(self, group):
        imp = super().estimate_importance(group)
        if self._skipped is None or imp.max() > imp.min(): return imp
        self._skipped += 1
        return torch.full_like(imp, float('nan'))  # the parent skips a nan group; a constant one would give it nan gammas

    @torch.no_grad()
    def regularize(self, model, alpha=2**4, bias=False):
        self._groups = [g for g in self._groups if self._targeted(g)]
        self._skipped = 0
        super().regularize(model, alpha=alpha, bias=bias)
        if self._groups and self._skipped == len(self._groups): warnings.warn("Every group has a constant importance: no penalty was applied.")
        self._skipped = None

# %% ../../nbs/prune/pruner.ipynb #63acddeb-f30e-448b-a397-d4cac2adba7a
from copy import copy
from ..core.schedule import Schedule

class Pruner():
    "Structured pruning for neural networks using torch_pruning"
    def __init__(self,
                 model,
                 pruning_ratio,               # Filters to remove, a fraction in [0, 1] (0.4 = 40%), or a per-layer dict
                 context,                     # 'local' (per-layer) or 'global' (across the whole model)
                 criteria,                    # How to select filters to prune, from `fasterai.core.criteria`
                 schedule=linear_scheduler,   # How the ratio progresses over the pruning steps
                 ignored_layers=None,         # Layers to leave untouched; None = output Linear and attention qkv
                 example_inputs=torch.randn(1, 3, 224, 224),  # Input used to trace layer dependencies
                 *args,
                 reg: float = 0.,             # Group penalty coefficient applied by `regularize`; 0 = no penalty
                 alpha: float = 4,            # The least important channel of a group gets 2**alpha times the penalty of the most important
                 **kwargs                     # Passed to the torch-pruning pruner
    ):
        if not any(p.requires_grad for p in model.parameters()):
            raise ValueError("No parameter requires grad: call model.requires_grad_(True) before pruning.")
        parametrized = next((n for n, m in model.named_modules() if _is_parametrized(m)), None)
        if parametrized is not None:
            raise ValueError(f"'{parametrized}' computes its weight from a parametrization (e.g. "
                             "FakeQuantizeCallback's rounding), which torch-pruning cannot rewrite: bake "
                             "or strip it before pruning.")
        if reg < 0: raise ValueError(f"reg must be >= 0, got {reg}.")
        store_attr()
        self.example_inputs = example_inputs.as_subclass(torch.Tensor).clone().to(next(model.parameters()).device)  # a subclass breaks the dependency trace, the clone escapes inference mode
        self.num_heads = {}
        self._original_params = sum(p.numel() for p in model.parameters())
        if not self.ignored_layers: self.get_ignored_layers(self.model)

        self.pruning_ratio_dict = None
        if isinstance(self.pruning_ratio, dict):
            self.pruning_ratio = {k: as_fraction(v, 'pruning_ratio', layer=k if isinstance(k, str) else type(k).__name__)
                                  for k, v in self.pruning_ratio.items()}
            self.pruning_ratio_dict = self._resolve_pruning_ratio_dict(self.pruning_ratio)
            self.default_pruning_ratio = as_fraction(kwargs.pop('default_pruning_ratio', 0.), 'default_pruning_ratio')
            print(f"Using per-layer pruning with {len(self.pruning_ratio_dict)} layer-specific ratios")
        else:
            self.pruning_ratio = as_fraction(self.pruning_ratio, 'pruning_ratio', allow_zero=False)
            self.default_pruning_ratio = self.pruning_ratio

        tp_schedule = self._to_tp_scheduler(self.schedule)
        if reg: pruner_cls, kwargs = _GroupNormPruner, {**kwargs, 'reg': reg}
        else:   pruner_cls = tp.pruner.MetaPruner

        self.pruner = pruner_cls(
            self.model,
            example_inputs=self.example_inputs,
            importance=self.group_importance,
            pruning_ratio=self.default_pruning_ratio,
            pruning_ratio_dict=self.pruning_ratio_dict,
            ignored_layers=self.ignored_layers,
            global_pruning=self.context == 'global',
            num_heads=self.num_heads,
            iterative_pruning_ratio_scheduler=tp_schedule,
            *args,
            **kwargs
        )

    def _to_tp_scheduler(self, schedule):
        "torch-pruning scheduler from a Schedule, `start_pct`/`end_pct` honoured; callables pass through"
        if not isinstance(schedule, Schedule): return schedule
        def scheduler(pruning_ratio, steps):
            s = copy(schedule)
            return [s.progress(i / steps) * pruning_ratio for i in range(steps + 1)]
        return scheduler

    def _resolve_pruning_ratio_dict(self, ratio_dict):
        "Convert layer name strings to module references for torch-pruning"
        name_to_module = dict(self.model.named_modules())
        resolved = {}
        for key, ratio in ratio_dict.items():
            if isinstance(key, str):
                if key in name_to_module: resolved[name_to_module[key]] = ratio
                else: print(f"Warning: Layer '{key}' not found in model, skipping")
            elif isinstance(key, nn.Module):
                resolved[key] = ratio
        return resolved
          
    def prune_model(self):
        "Execute one pruning step and restore attention layer configurations"
        self.pruner.step()
        self.restore_attention_layers()
        if self.reg: self.pruner.update_regularizer()

    def regularize(self,
                   scale: float = 1.,  # Multiplies the penalty, for gradients that are scaled (AMP loss scale, accumulation)
    ):
        "Add the group penalty to the current gradients, between `backward` and the optimizer step"
        if not self.reg: raise ValueError("regularize() needs a penalty: build the Pruner with reg > 0.")
        self.pruner.reg = self.reg * scale
        self.pruner.regularize(self.model, alpha=2**self.alpha)


    def get_linear_layers_to_ignore(self, 
                                    model: nn.Module
    ):
        "Find and ignore output Linear layers to preserve model output dimensions"
        try:
            traced = symbolic_trace(model)
            for node in traced.graph.nodes:
                if node.op == "output":
                    for input_node in node.all_input_nodes:
                        if input_node.target:
                            module = dict(model.named_modules()).get(input_node.target)
                            if isinstance(module, torch.nn.Linear):
                                self.ignored_layers.append(module)
                                print(f"Ignoring output layer: {input_node.target}")
        except Exception as e:
            print(f"Could not trace model for output layer detection: {e}")


    def get_attention_layers_to_ignore(self, 
                                       model: nn.Module
    ):
        "Find and ignore attention layers (qkv projections) to preserve attention structure"
        for module in model.modules():
            if hasattr(module, 'num_heads'):
                if hasattr(module, 'qkv'):
                    self.ignored_layers.append(module.qkv)
                    self.num_heads[module.qkv] = module.num_heads
                    print(f"Attention layer ignored: {module.qkv}, num_heads={module.num_heads}")
                elif hasattr(module, 'qkv_proj'):
                    self.ignored_layers.append(module.qkv_proj)
                    self.num_heads[module.qkv_proj] = module.num_heads
                    print(f"Attention layer ignored: {module.qkv_proj}, num_heads={module.num_heads}")

    
    def get_ignored_layers(self, 
                           model: nn.Module
    ):
        "Build list of layers to ignore during pruning"
        self.ignored_layers = []
        self.get_linear_layers_to_ignore(model)
        self.get_attention_layers_to_ignore(model)
        print(f"Total ignored layers: {len(self.ignored_layers)}")
    
                
    def restore_attention_layers(self):
        "Restore num_heads and head_dim attributes after pruning attention layers"
        for m in self.model.modules():
            if hasattr(m, 'num_heads'):
                if hasattr(m, 'qkv'):
                    m.num_heads = self.num_heads[m.qkv]
                    m.head_dim = m.qkv.out_features // (3 * m.num_heads)
                elif hasattr(m, 'qkv_proj'):
                    m.num_heads = self.num_heads[m.qkv_proj]
                    m.head_dim = m.qkv_proj.out_features // (3 * m.num_heads)


    def group_importance(self, group):
        "Compute importance scores for a dependency group"
        handler_map = {
            function.prune_conv_out_channels: 'filter',
            function.prune_linear_out_channels: 'row',
            function.prune_linear_in_channels: 'column',
            function.prune_conv_in_channels: 'shared_kernel',
        }
    
        group_imp = []
        group_idxs = []
    
        for i, (dep, idxs) in enumerate(group):
            if dep.handler in handler_map:
                impo = self.criteria(dep.target.module, handler_map.get(dep.handler), squeeze=True)
                group_imp.append(impo)
                group_idxs.append(group[i].root_idxs)
    
        if len(group_imp) == 0:
            return torch.tensor([])
            
        reduced_imp = torch.zeros_like(group_imp[0])
    
        for i, (imp, root_idxs) in enumerate(zip(group_imp, group_idxs)):
            imp = imp.to('cpu')
            reduced_imp = reduced_imp.to('cpu')
            reduced_imp.scatter_add_(0, torch.tensor(root_idxs, device=imp.device), imp)
    
        reduced_imp /= len(group_imp)
    
        return reduced_imp.to(group_imp[0].device)

    def print_sparsity(self) -> None:
        "Print pruning report showing channel counts and parameter reduction"
        total_params = 0
        
        print("\nPruning Report:")
        print("-" * 85)
        print(f"{'Layer':<35} {'Type':<12} {'In Ch':<8} {'Out Ch':<8} {'Params':<12}")
        print("-" * 85)
        
        for name, m in self.model.named_modules():
            if isinstance(m, (nn.Conv2d, nn.Linear)):
                params = sum(p.numel() for p in m.parameters())
                total_params += params
                
                if isinstance(m, nn.Conv2d):
                    in_ch, out_ch = m.in_channels, m.out_channels
                    layer_type = "Conv2d"
                else:
                    in_ch, out_ch = m.in_features, m.out_features
                    layer_type = "Linear"
                
                print(f"{name:<35} {layer_type:<12} {in_ch:<8} {out_ch:<8} {params:<12,}")
        
        print("-" * 85)
        reduction = 100 * (1 - total_params / self._original_params) if self._original_params > 0 else 0
        print(f"{'Total':<35} {'':<12} {'':<8} {'':<8} {total_params:<12,}")
        print(f"{'Original':<35} {'':<12} {'':<8} {'':<8} {self._original_params:<12,}")
        print(f"{'Reduction':<35} {'':<12} {'':<8} {'':<8} {reduction:>10.2f}%")
