# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/regularize/group_regularize_callback.ipynb.

# %% ../../nbs/regularize/group_regularize_callback.ipynb #imports
from __future__ import annotations
from copy import copy

from fastai.callback.core import Callback
from fastai.callback.fp16 import MixedPrecision, NonNativeMixedPrecision
from torch.amp import GradScaler
from ..core.schedule import Schedule
from ..prune.pruner import Pruner
from ..prune.prune_callback import PruneCallback

# %% auto #0
__all__ = ['GroupRegularizeCallback']

# %% ../../nbs/regularize/group_regularize_callback.ipynb #group-reg-cb
class GroupRegularizeCallback(Callback):
    "Add `pruner`'s group penalty to the gradients at every optimizer step, so training pushes coupled channels towards zero before `pruner.prune_model()` removes them"
    order = MixedPrecision.order - 2  # after GradientAccumulation skips a batch, before MixedPrecision unscales
    def __init__(self,
                 pruner: Pruner,                    # Built with `reg > 0` on the model the Learner trains
                 schedule: Schedule | None = None,  # Ramps the penalty: `pruner.reg * progress`
                 verbose: bool = False,             # Print the penalty after each epoch
    ):
        if not pruner.reg: raise ValueError("GroupRegularizeCallback needs a penalty: build the Pruner with reg > 0.")
        self.pruner, self.schedule, self.verbose, self.scale = pruner, copy(schedule), verbose, 1.

    def before_fit(self):
        if self.pruner.model is not self.learn.model: raise ValueError("The Pruner was built on another model than learn.model: build it on learn.model.")
        if any(isinstance(cb, NonNativeMixedPrecision) for cb in self.learn.cbs): raise ValueError("NonNativeMixedPrecision is not supported: use MixedPrecision (learn.to_fp16()).")
        if any(isinstance(cb, PruneCallback) for cb in self.learn.cbs): raise ValueError("PruneCallback cannot run in the same fit: fit with GroupRegularizeCallback, then call pruner.prune_model().")

    def before_step(self):
        self.scale = self.schedule.progress(self.pct_train) if self.schedule is not None else 1.
        if not self.scale: return
        scaler = getattr(self.learn, 'scaler', None)
        loss_scale = scaler.get_scale() if isinstance(scaler, GradScaler) else 1.
        self.pruner.regularize(scale=self.scale * loss_scale)

    def after_epoch(self):
        if self.verbose: print(f"Group penalty: {self.pruner.reg * self.scale:.2e}")
