# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/misc/conv_decomposer.ipynb.

# %% auto #0
__all__ = ['Conv_Decomposer']

# %% ../../nbs/misc/conv_decomposer.ipynb #imports
import torch
import torch.nn as nn
import copy

# %% ../../nbs/misc/conv_decomposer.ipynb #conv-decomposer
def _unfold(tensor, mode):
    "Unfold a tensor along a mode into a matrix"
    return tensor.moveaxis(mode, 0).flatten(1)

def _partial_tucker(weight, ranks, n_iter=5):
    "Partial Tucker decomposition on modes [0, 1] via alternating SVD (HOOI)"
    # Initialize factors from SVD of mode unfoldings
    U0 = torch.linalg.svd(_unfold(weight, 0), full_matrices=False)[0][:, :ranks[0]]
    U1 = torch.linalg.svd(_unfold(weight, 1), full_matrices=False)[0][:, :ranks[1]]

    for _ in range(n_iter):
        # Project out mode 0 using U0, then update U1
        proj = torch.einsum('oihw, or -> rihw', weight, U0)
        U1 = torch.linalg.svd(_unfold(proj, 1), full_matrices=False)[0][:, :ranks[1]]
        # Project out mode 1 using U1, then update U0
        proj = torch.einsum('oihw, is -> oshw', weight, U1)
        U0 = torch.linalg.svd(_unfold(proj, 0), full_matrices=False)[0][:, :ranks[0]]

    # Core = W ×₀ U0ᵀ ×₁ U1ᵀ
    core = torch.einsum('oihw, or, is -> rshw', weight, U0, U1)
    return core, [U0, U1]


class Conv_Decomposer:
    "Decompose Conv2d layers using Tucker decomposition to reduce parameters and FLOPs"

    def __init__(self): pass

    def decompose(self,
                  model: nn.Module,              # The model to decompose
                  percent_removed: float = 0.5,  # Fraction of rank to remove per mode [0, 1)
    ) -> nn.Module:
        "Recursively decompose all eligible Conv2d layers in the model"
        if not (0 <= percent_removed < 1):
            raise ValueError(f"percent_removed must be in range [0, 1), got {percent_removed}")

        new_model = copy.deepcopy(model)
        for name in list(new_model._modules):
            module = new_model._modules[name]
            if len(list(module._modules)) > 0:
                new_model._modules[name] = self.decompose(module, percent_removed)
            elif isinstance(module, nn.Conv2d) and module.groups == 1 and min(module.kernel_size) > 1:
                new_model._modules[name] = self.Tucker(module, percent_removed)
        return new_model

    def Tucker(self,
               layer: nn.Conv2d,          # The Conv2d layer to decompose
               percent_removed: float,    # Fraction of rank to remove per mode
    ) -> nn.Sequential:
        "Perform Tucker decomposition on a single Conv2d layer"
        W = layer.weight.data
        C_out, C_in = W.shape[:2]

        R_out = max(1, int((1 - percent_removed) * C_out))
        R_in  = max(1, int((1 - percent_removed) * C_in))

        core, (U_out, U_in) = _partial_tucker(W, [R_out, R_in])
        # core: (R_out, R_in, H, W), U_out: (C_out, R_out), U_in: (C_in, R_in)

        # 1. Pointwise input compression: (C_in → R_in)
        first = nn.Conv2d(C_in, R_in, 1, bias=False)
        first.weight.data = U_in.t().unsqueeze(-1).unsqueeze(-1)

        # 2. Spatial convolution at reduced rank: (R_in → R_out)
        middle = nn.Conv2d(R_in, R_out, layer.kernel_size, stride=layer.stride,
                           padding=layer.padding, dilation=layer.dilation, bias=False)
        middle.weight.data = core

        # 3. Pointwise output expansion: (R_out → C_out)
        last = nn.Conv2d(R_out, C_out, 1, bias=layer.bias is not None)
        last.weight.data = U_out.unsqueeze(-1).unsqueeze(-1)
        if layer.bias is not None:
            last.bias.data = layer.bias.data

        return nn.Sequential(first, middle, last)
