# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/misc/conv_decomposer.ipynb.

# %% auto #0
__all__ = ['VALID_METHODS', 'Conv_Decomposer']

# %% ../../nbs/misc/conv_decomposer.ipynb #imports
import torch
import torch.nn as nn
import copy

# %% ../../nbs/misc/conv_decomposer.ipynb #conv-decomposer
from .fc_decomposer import _rank_from_energy, _should_decompose

def _unfold(tensor, mode):
    "Unfold a tensor along a mode into a matrix"
    return tensor.moveaxis(mode, 0).flatten(1)

def _partial_tucker(weight, ranks, n_iter=10, tol=1e-4):
    "Partial Tucker decomposition on modes [0, 1] via alternating SVD (HOOI)"
    U0 = torch.linalg.svd(_unfold(weight, 0), full_matrices=False)[0][:, :ranks[0]]
    U1 = torch.linalg.svd(_unfold(weight, 1), full_matrices=False)[0][:, :ranks[1]]

    for _ in range(n_iter):
        U0_prev, U1_prev = U0.clone(), U1.clone()
        proj = torch.einsum('oihw, or -> rihw', weight, U0)
        U1 = torch.linalg.svd(_unfold(proj, 1), full_matrices=False)[0][:, :ranks[1]]
        proj = torch.einsum('oihw, is -> oshw', weight, U1)
        U0 = torch.linalg.svd(_unfold(proj, 0), full_matrices=False)[0][:, :ranks[0]]
        if (U0 - U0_prev).norm() + (U1 - U1_prev).norm() < tol: break

    core = torch.einsum('oihw, or, is -> rshw', weight, U0, U1)
    return core, [U0, U1]

VALID_METHODS = frozenset({'tucker', 'svd'})

class Conv_Decomposer:
    "Decompose Conv2d layers to reduce parameters and FLOPs"

    def __init__(self): pass

    def decompose(self,
                  model: nn.Module,                       # The model to decompose
                  percent_removed: float = 0.5,           # Fraction of rank to remove [0, 1)
                  method: str = 'tucker',                 # 'tucker' (3 layers) or 'svd' (2 layers)
                  energy_threshold: float | None = None,  # Auto rank via energy retention (0-1)
                  layers: list[str] | None = None,        # Layer names to decompose (None = all eligible)
                  exclude: list[str] | None = None,       # Layer names to skip
                  n_iter: int = 10,                       # Max HOOI iterations (tucker only)
                  tol: float = 1e-4,                      # HOOI convergence tolerance (tucker only)
    ) -> nn.Module:
        "Decompose eligible Conv2d layers using Tucker (3 layers) or SVD (2 layers)."
        if method not in VALID_METHODS:
            raise ValueError(f"method must be one of {VALID_METHODS}, got {method!r}")
        if energy_threshold is None and not (0 <= percent_removed < 1):
            raise ValueError(f"percent_removed must be in range [0, 1), got {percent_removed}")
        if energy_threshold is not None and not (0 < energy_threshold <= 1):
            raise ValueError(f"energy_threshold must be in range (0, 1], got {energy_threshold}")

        new_model = copy.deepcopy(model)
        for name, module in list(new_model.named_modules()):
            if (isinstance(module, nn.Conv2d) and module.groups == 1 
                and min(module.kernel_size) > 1
                and _should_decompose(name, layers, exclude)):
                parent_name, _, child_name = name.rpartition('.')
                parent = new_model.get_submodule(parent_name) if parent_name else new_model
                if method == 'tucker':
                    replacement = self.Tucker(module, percent_removed, energy_threshold, n_iter, tol)
                else:
                    replacement = self.SVD(module, percent_removed, energy_threshold)
                setattr(parent, child_name, replacement)
        return new_model

    def SVD(self,
            layer: nn.Conv2d,                        # The Conv2d layer to decompose
            percent_removed: float = 0.5,            # Fraction of rank to remove
            energy_threshold: float | None = None,   # Auto rank via energy retention
    ) -> nn.Sequential:
        "SVD decomposition into 2 layers: spatial at reduced rank + pointwise expansion"
        W = layer.weight.data
        C_out, C_in = W.shape[:2]
        K = layer.kernel_size

        # Reshape to 2D: (C_out, C_in*K*K), apply SVD
        W_2d = W.reshape(C_out, -1)
        U, S, Vh = torch.linalg.svd(W_2d, full_matrices=False)

        if energy_threshold is not None:
            R = _rank_from_energy(S, energy_threshold)
        else:
            R = max(1, int((1 - percent_removed) * min(C_out, C_in)))

        # Layer 1: spatial conv at reduced rank (C_in → R)
        W1 = (torch.diag(S[:R]) @ Vh[:R]).reshape(R, C_in, *K)
        first = nn.Conv2d(C_in, R, K, stride=layer.stride,
                          padding=layer.padding, dilation=layer.dilation, bias=False)
        first.weight.data = W1

        # Layer 2: pointwise expansion (R → C_out)
        W2 = U[:, :R]
        last = nn.Conv2d(R, C_out, 1, bias=layer.bias is not None)
        last.weight.data = W2.unsqueeze(-1).unsqueeze(-1)
        if layer.bias is not None:
            last.bias.data = layer.bias.data

        return nn.Sequential(first, last)

    def Tucker(self,
               layer: nn.Conv2d,                        # The Conv2d layer to decompose
               percent_removed: float = 0.5,            # Fraction of rank to remove per mode
               energy_threshold: float | None = None,   # Auto rank via energy retention
               n_iter: int = 10,                        # Max HOOI iterations
               tol: float = 1e-4,                       # HOOI convergence tolerance
    ) -> nn.Sequential:
        "Tucker decomposition into 3 layers: pointwise compress + spatial + pointwise expand"
        W = layer.weight.data
        C_out, C_in = W.shape[:2]

        if energy_threshold is not None:
            S0 = torch.linalg.svd(_unfold(W, 0), full_matrices=False)[1]
            S1 = torch.linalg.svd(_unfold(W, 1), full_matrices=False)[1]
            R_out = _rank_from_energy(S0, energy_threshold)
            R_in = _rank_from_energy(S1, energy_threshold)
        else:
            R_out = max(1, int((1 - percent_removed) * C_out))
            R_in  = max(1, int((1 - percent_removed) * C_in))

        core, (U_out, U_in) = _partial_tucker(W, [R_out, R_in], n_iter=n_iter, tol=tol)

        first = nn.Conv2d(C_in, R_in, 1, bias=False)
        first.weight.data = U_in.t().unsqueeze(-1).unsqueeze(-1)

        middle = nn.Conv2d(R_in, R_out, layer.kernel_size, stride=layer.stride,
                           padding=layer.padding, dilation=layer.dilation, bias=False)
        middle.weight.data = core

        last = nn.Conv2d(R_out, C_out, 1, bias=layer.bias is not None)
        last.weight.data = U_out.unsqueeze(-1).unsqueeze(-1)
        if layer.bias is not None:
            last.bias.data = layer.bias.data

        return nn.Sequential(first, middle, last)
