# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/misc/cpu_optimizer.ipynb.

# %% auto #0
__all__ = ['accelerate_model_for_cpu']

# %% ../../nbs/misc/cpu_optimizer.ipynb #fbbccd4a
import torch
import torch.nn as nn
from torch.utils.mobile_optimizer import optimize_for_mobile

# %% ../../nbs/misc/cpu_optimizer.ipynb #6524ac31
def accelerate_model_for_cpu(model: nn.Module, example_input: torch.Tensor):
    model.eval()
    example_input = example_input.to(memory_format=torch.channels_last)
    
    model = model.to(memory_format=torch.channels_last)
    model = torch.jit.script(model)
    model = optimize_for_mobile(model)

    return model
