package:
  name: fasterai
  version: 0.1.6
source:
  sha256: 2f45a04476493797aab1aee39862f4b17cb52404a3b0c769fab0fbf1d68e902a
  url: https://files.pythonhosted.org/packages/8b/5f/53aab637ecf739682ee313a416a1048e184bf4d88e7f89007c32987b16d4/fasterai-0.1.6.tar.gz
about:
  dev_url: https://nathanhubens.github.io
  doc_url: https://nathanhubens.github.io
  home: https://nathanhubens.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library to make neural networks lighter and faster with fastai
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - nathanhubens
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai>=2.2
  run:
  - pip
  - python
  - packaging
  - fastai>=2.2
test:
  imports:
  - fasterai
