package:
  name: fasterai
  version: 0.1.4
source:
  sha256: 2ee33fbfca1c0849cb89ba9a8e1d6c509394edcd529307c44001e933218aa9c7
  url: https://files.pythonhosted.org/packages/fd/5e/1a3c180208c6f5090a2120925785cad99b349da500a4a05855146af26f48/fasterai-0.1.4.tar.gz
about:
  dev_url: https://nathanhubens.github.io
  doc_url: https://nathanhubens.github.io
  home: https://nathanhubens.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library to make neural networks lighter and faster with fastai
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - nathanhubens
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai>=2.2
  run:
  - pip
  - python
  - packaging
  - fastai>=2.2
test:
  imports:
  - fasterai
