package:
  name: fasterai
  version: 0.1.3
source:
  sha256: 32bafa940711d3b2c68009dd897196a3ced0d890d03da30111d660fc390de0eb
  url: https://files.pythonhosted.org/packages/0e/5d/a0735684e5be447cac9858ffbf52dfbbf2798441ebb49fc3356c94c3b92d/fasterai-0.1.3.tar.gz
about:
  dev_url: https://nathanhubens.github.io
  doc_url: https://nathanhubens.github.io
  home: https://nathanhubens.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library to make neural networks lighter and faster with fastai
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - nathanhubens
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai>=2.2
  run:
  - pip
  - python
  - packaging
  - fastai>=2.2
test:
  imports:
  - fasterai
